### ISSUE TITLE
Add Download Data to Vitals dashboard

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1010]
**What needs to be done? Why does it need to be done?**
The user should be able to click on the "Download Data" button in the top right corner of the Vitals dashboard. When they do so, they'll download a CSV of the data of the view that the user is looking at, along with a .txt file with the Methodology. 

![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/daea9efb-f2db-4d84-88a4-ca08f86447b9)

Here's an [example](https://docs.google.com/spreadsheets/d/12s5qE-OIWds_teIodXQ2lLTiIq6ICAm5atBecX4yY8c/edit#gid=111700939) of what the data download would look like if the user is looking at the state-wide view. For the office-level view, the "Metrics over time" tab would show just the performance for that office, and the third tab would change to "Metrics by officer."

The Vitals Methodology for the accompanying .txt file is [here](https://docs.google.com/document/d/1moftAcmQ2JWddxwI99btG0DDSC8fBIChwfysb6Hvam4/edit#heading=h.v6pxhexkocuw). 

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@soniachokshi I have a few questions:

1. CSV does not allow for tabs - so each of these tabs will be a separate csv file, is that what you were expecting?
2. I'm not quite sure what the "Summary" file is. If the user is looking at the state-wide view, the summary file would display exactly as shown in the example you sent? But if the user is looking at an office view, the summary file would show ...?

State	North Dakota
Office(s)	<office name>
Officer(s)	All
Data generated on 3/4/21


3. I would also like to get some clarification on the filenames. Considering they will all be separate files, the filenames are `North_Dakota_At_a_Glance_Summary_3.4.21.csv` and `North_Dakota_At_a_Glance_Metrics_over_time_3.4.21.csv` and `North_Dakota_At_a_Glance_Metrics_by_office_3.4.21.csv`?
