### ISSUE TITLE
Setup SSO for Recidiviz users using GSuite

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#1022]
**Is your feature request related to a problem? Please describe.**
Each state already has a user authentication system. We need to build a system to hook into them. These systems can then be used to prepopulate user information into our system and even set permissions and roles based upon the person’s role in that state.

As a first step we will want to setup SSO for Recidiviz users. 

**Describe the solution you'd like**
Explore the solutions offered by Auth0. We may also want to setup time with their support or sales team to learn about the new products that we could use, like [Organizations](https://auth0.com/docs/organizations).

**Describe alternatives you've considered**
See PRD: https://docs.google.com/document/d/135I8Y-iJTZYj9faVmazjcGFNGtDvHYazBugBOXOeGJE/edit#heading=h.c29ll7o2tvsa

**Additional context**
[Auth0 Organizations](https://auth0.com/docs/organizations)
[Multiple Organization Architecture (Multitenancy) Overview](https://cdn2.auth0.com/docs/media/articles/architecture-scenarios/planning/Multiple-Organization-Architecture-Multitenancy-Overview.pdf?_ga=2.184785185.965597847.1618241807-1310338147.1608588905)
[B2B Auth management](https://auth0.com/docs/architecture-scenarios/b2b)
[Home Realm Discovery](https://auth0.com/docs/architecture-scenarios/b2b/authentication#home-realm-discovery)

**Comment by Catacola** [comment]
Incomplete test user creation flow: https://paper.dropbox.com/doc/Making-test-users-with-SSO--BSFpIvznRT_4bmypPvd9~rnjAg-9fwwTKAFuDAzJ2Z0tFsvH

I discovered a vuln in this approach while building the doc. Nothing to worry about as any fake accounts which would have been vulnerable have been deleted.

**Comment by jessex** [comment]
@Catacola thanks for creating the doc! Can you share more about the vulnerability? If it feels sensitive, you can share that over Slack / offline from Github.

**Comment by phenggeler** [comment]
@jessex - I asked @Catacola to create this ticket to review his proposed SSO testing configuration. 

@Catacola - capturing our Slack conversation, the configuration sounds solid at this point and we can do a further review as the feature release approaches. 

Any other questions at this point? If not we, can close this one out.

**Comment by jessex** [comment]
No outstanding questions from me! Thanks, folks.
