### ISSUE TITLE
Add ACL to the frontend for US_ID Vitals

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#1023]
**Is your feature request related to a problem? Please describe.**
Once we have user restrictions for US_ID users we will need to update the Vitals dashboard to modify the user's experience based on the user restrictions applied.

**Describe the solution you'd like**
A state-agnostic solution that will check the user's restrictions and update the the data that the user is able to access.

**Describe alternatives you've considered**
N/A

**Additional context**
https://paper.dropbox.com/doc/ACL-for-users-with-restricted-access-to-supervision-locations--BKNaFitioZ~S0N663kDPoUaFAg-BFVb8a853aOUKVSwOUL5T

[Issue #1033 working on getting US_ID user restrictions data](https://github.com/Recidiviz/pulse-dashboard/issues/1033)

**Comment by jovergaag** [comment]
@daschi @sychang I believe that this is fulfilled by [#1115](https://app.zenhub.com/workspaces/torch--5ec36552cdfe7bc58f04bdbe/issues/recidiviz/pulse-dashboard/1155). Or are there other restrictions that need to be put in place?
