### ISSUE TITLE
Consolidate domains and unify UI for US_ID between vitals and case triage

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#1024]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, e.g. we don't currently convey...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by jovergaag** [comment]
I think this is done now, correct? @daschi

**Comment by daschi** [comment]
I think so? We've decided not to move forward with using one domain at this time right? Do we need another issue to track that going forward?

**Comment by jovergaag** [comment]
I think it makes sense to close it and create another issue to consolidate domains if we decide to do that in the future.
