### ISSUE TITLE
District dropdown text overflow

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1061]
**What needs to be done? Why does it need to be done?**
Seen on fullstory by an IE11 user. District dropdown options are overflowing below the filter dropdown area.

User agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/6efdac8f-c44e-4842-bcda-9e41dca6529c)

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
This looks like it's an issue within fullstory, this is how it looks on browserstack:

![Screen Shot 2021-04-29 at 10 03 29 AM](https://user-images.githubusercontent.com/5402804/116564175-bba9d480-a8d2-11eb-9705-2bdbe4299d21.png)
