### ISSUE TITLE
Switch to event-based methodology for "Number of recommitments from parole" chart on Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1066]
**What needs to be done? Why does it need to be done?**
Right now, we’re showing a person-based view of the dashboard, showing only the most recent recommitment per person. PA and CSG has flagged that that makes less sense than an event-based methodology, since PA uses short-term incarcerations as gradual sanctions, so they are interested in seeing patterns of people cycling in and out of facilities, which we lose when we only show the most recent recommitment.

The smallest change that helps alleviate this is switching only the top chart from a person-based methodology of selecting the most recent recommitment to an event-based methodology where we show all recommitments. This double-counts people, but captures the impact of people cycling into the system.

This task involves
- Updating the that's pulling from 'event_based_revocations' to pull in **all** recommitment, rather than just the most recent recommitment.
- Updating the methodology copy (TODO)
- Adding a clarifying UI note explaining why the numbers on this chart might look different than the numbers on other charts (TODO)

TODO: Confirm that MO would be ok switching to this methodology as well, review mocks with MO and PA

**Additional context**
We are aiming to have PA fresh data land around week of 5/17, so having the change land by the time we get fresh data may allow for the least change-management churn because all of the data will be updating at once.

**Comment by daschi** [comment]
@sychang I think this is done?

**Comment by sychang** [comment]
Throwback! yeah!
