### ISSUE TITLE
Set up health checks and proactive alerting

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#11]
At the very least, we want to know:
- If the app is unreachable
- If latency is spiking
- If inbound traffic is spiking
- If any dependencies are failing

We should receive proactive alerts for unreachability of the app or of dependencies, and should receive alerts if latency, inbound traffic, or other continuous metrics are above some threshold. We should make use of existing dashboards and alerts via Stackdriver where possible. Ideally, we can get everything through Stackdriver "for free" but even if that is true, this task should ensure that it is all tested and run some chaos testing.

**Comment by jessex** [comment]
@marie-cd: please update this issue with any other thoughts on operational needs for the Pulse Dashboard app.

**Comment by matthewroot** [comment]
We should also have alerting if error rates go above a certain bound.

**Comment by jessex** [comment]
This was effectively completed with previous work, notably the introduction of Sentry. Closing this out!
