### ISSUE TITLE
Build hover tooltips for words that need definitions

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/pulse-dashboard#110]
Provide an on-hover glossary for words that may need some extra clarification. We've been using the Methodology section to do a lot of this right now, but we should move towards documenting the _how_ of our calculations into Methodology, and moving the _what_ that clarifies the specificity of the metric to on-hover glossaries. 

![image](https://user-images.githubusercontent.com/9345233/66946207-725ea080-f01e-11e9-8556-be01e8794741.png)

**Comment by jessex** [comment]
Closing this deprecated UI feature.
