### ISSUE TITLE
Change front-end ACL to require whitelisting statewide users.

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1104]
**Is your feature request related to a problem? Please describe.**
When states have access restrictions, we currently only receive a list of users who should be restricted to certain districts. It is assumed that all other users should have statewide access. This seems like a security hole we need to patch.

**Describe the solution you'd like**
1) Require states to supply a list of statewide users alongside those with restricted access.
2) Use this new designation to set statewide access in our auth layer.
3) For users who manage to sign up but do not have access to any data, create a redirect page with information about who to contact to get their access levels fixed.

Bonus: this will solve the current bug we have where a person promoted from restricted access to statewide access would need manual intervention from us to have their restrictions cleared.

**Describe alternatives you've considered**
Leaving it as is and fixing the few people who need special cases by hand, but that seems to be asking for a problem down the road.

**Additional context**
Will require buy in from at least MO.

**Comment by daschi** [comment]
@Catacola I think this is not an issue anymore, but wanted to check in with you if that seems right? At this point, we've asked MO to provide us with all of the users in the LANTERN_DA_RA_LIST, and I think this was originally created when we were only receiving the restricted users?
