### ISSUE TITLE
Switch over-time Lantern chart to event-based methodology

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1124]
**What needs to be done? Why does it need to be done?**
The top over-time chart in the Lantern dashboard should be switched from person-based to event-based methodologies for both MO and PA. Instead of showing only the most recent recommitment/admission for each person, we will show **all**. This task involves
- [x] Updating the queries to not only take the most recent admission, but count all admissions for all people in the given time period
- [ ] Updating the methodology text to reflect this methodology, and the fact that this chart will show different counts than the rest of the page (TODO: @sychang ). There should be no additional user-facing changes on the chart.

**Additional context**
Main issue #1066

**Comment by Catacola** [comment]
To be clear, we are replacing the chart completely and not creating a toggle, correct?

**Comment by sychang** [comment]
That's correct!
