### ISSUE TITLE
Create a more graceful failure mode in the case of missing metric packages

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#114]
If there is a missing metric file, e.g. a botched export or accidental deletion, attempting to load any view that relies on that package will feature an indefinitely spinning loader, and the logs for the backend server will show errors related to a failure to download-and-cache the file in question. We should consider more graceful failure modes. Possibilities:
* Load the visualizations that don't rely on the missing file and keep the spinner on the other visualizations
* The above, but display an error over the visualizations that don't have the file they need
* Display a general error over the entire view

**Comment by jovergaag** [comment]
We now have nice chart error components displaying an appropriate message, and charts can fail individually rather than crashing the page. Closing!
