### ISSUE TITLE
Make it easier to refresh the metric cache

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#115]
In scenarios like that described in #114, there is a need to cause the backend server to proactively download metric files instead of waiting out the in-memory cache's TTL. For example, in the scenario of that issue, when the missing file is added to its metric package bucket, the backend doesn't just start serving the file immediately, because it cached the partial package already. So you need to effectively perform another deploy or otherwise bounce that backend to invoke a cache refresh. We need an easier, secured way of forcing the cache refresh to speed up recovery from metric-related issues.

**Comment by jessex** [comment]
@jovergaag there have obviously been major architectural changes in our caching. With the spirit of this original issue, do you think that the metric cache refreshing capabilities are currently to your liking? Can we close this out?

**Comment by jovergaag** [comment]
Yes! All of our metric files are now cached in Redis, so they can be refreshed by clicking a button. Closing 'er out!
