### ISSUE TITLE
Consolidate Lantern and Core Stores

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1165]
**What needs to be done? Why does it need to be done?**
As we move towards a unified product interface, the concept of Lantern and Core will become obsolete. The new interface will be using components from both Lantern and Core and rendering them on the same page and within the same framework.

Currently our we have a `RootStore` and some common shared stores, then a `LanternStore` and `CoreStore` with stores/logic applicable to to the associated page. We will need to consolidate these stores and organize them such that any of the stores are accessible anywhere in the project. Ex: As we move toward deploying Vitals for US_MO, we will need to have the `UserRestrictionsStore` available centrally rather than as part of the `LanternStore`.

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
After thinking through this and chatting with @jovergaag, we've decided we don't actually need to refactor the stores. We can deprecate the Lantern directory and stores once everything is moved over to Pathways/Projections, and there are currently no user restriction requirements for ID, TN and ND. 

cc @Catacola @sychang
