### ISSUE TITLE
[US_ID VITALS] QA for launch

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1177]
**What needs to be done? Why does it need to be done?**
This ticket captures all of the final bugs / QA tasks that are **blocking** for the Idaho Vitals launch.

- [x] PercentDelta should show 0% instead of "N/A" when value is 0
- [x] re-enable average line on time series chart
- [x] Make font size consistent for "Overall" and "By metric" percentages in the Summary Table - 14px
- [x] Clicking on an officer who has caseload in more than one office sometimes displays metrics from the Office other than the one clicked through from on the Office view. For ex: from "District 0" page, click on several of the officers and notice that some of then have an Office name other than "District 0" in the breadcrumbs and the metrics are different than were in the table on previous screen
- [x] 30D and 90D Percent Delta values on VitalsSummaryTable do not always match what is on the entity page for Overall
- [x] Sorting by "Office" or "Officer" on VitalsSummaryTable does not work as expected
- [x] https://dashboard-staging.recidiviz.org/community/vitals[name] time series average annotation is incorrect - turns out this officer is no longer with IDOC so they will no longer appear on the Vitals page.
- [x] https://dashboard-staging.recidiviz.org/community/vitals/district-office-4-boise[name] entity_name is strange so the Caseload button is wonky (ask Jen for name) -- this one will also disappear once we filter the list based off case triage officers
- [x] Caseload should open in new window
- [x] Officers should only belong to single district -- separate issue #8452
- [x] District 0 HQ page is broken.
- [x] Remove District 0 HQ

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@daschi FYI about these misspellings as you are working on reformatting the office names
