### ISSUE TITLE
Admitted individuals download data incorrect columns

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1182]
**What needs to be done? Why does it need to be done?**
In Lantern dashboard, when you export the data for the admitted individuals table in MO, the column titles no longer match with the data in the column. For instance, column E is titled 'last recommendation' but is showing data for 'violation record'. 

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang I removed the screenshot here as it contained sensitive data. @daschi Reach out to Serena directly for the screenshot.

**Comment by jessex** [comment]
@jovergaag I am closing and deleting this issue. Editing is not sufficient, as you can see in version history. Please recreate it after it's deleted.
