### ISSUE TITLE
[US_ND VITALS] QA for North Dakota Vitals Launch

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1184]
**What needs to be done? Why does it need to be done?**
This ticket captures all of the final bugs / QA tasks that are blocking for the North Dakota Vitals launch.

- [x] Daniela - In the state-wide view, two district office names are misspelled in the table: Bismark should be Bismarck, and Bittineu should be Bottineau.
- [x] Daniela - Update the timely contacts copy on to reflect the updated methodology: "XX% of clients received initial contact within 30 days of starting supervision and a F2F contact every subsequent 3 months, 2 months, or 1 month for minimum, medium, and maximum supervision levels respectively"
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/21af402f-cd59-4e72-9a8e-52293bdfab42)
- [x] Several officers have only IDs but not names [EDIT: This should be fixed by: https://github.com/Recidiviz/recidiviz-data/pull/8652]
Bottineau: Officer 202 doesn’t have a name in Bottineau (Bittineu in the dashboard currently)
Grand Forks: 155, 166, 141, 207
Bismarck: 800, 53
Devils lake: 182
Williston: 430, 456
Minot: 177, 161, 201
Fargo: 176
Dickinson: 472
Grafton: 436

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@daschi Are you working on these two remaining items? Seems like this should be started sooner than later...lmk if you want me to start on it tomorrow (Thursday)

**Comment by daschi** [comment]
I haven't started on it yet - I'm actually still not sure the best place to update those names. I can work on it tomorrow though!
