### ISSUE TITLE
Remove officer external id from path

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1193]
**What needs to be done? Why does it need to be done?**
Including the officer external ID in the path is a security risk. We need to change the ID to be a Recidiviz internal id, or store the current entity id in the store for vitals rather than in the path.

Note: this is a launch blocker

cc: @sychang

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
Discussed this with @elchao96 on Friday, and we plan to use a SHA256 hash of the email_address and external_id on the frontend. I don't think this will require any backend changes, since the hash would just be used for routing.
