### ISSUE TITLE
Add account-based page-level restrictions 

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1194]
**What needs to be done? Why does it need to be done?**
In all states, a user should be able to see a set of pages based on their account (later, their role). This enables us to roll out new features incrementally and make sure people are seeing the tools that are most relevant to them. 

Here are the allowlists that are relevant in the short-term (~next 4 weeks):
In North Dakota, these are the following accounts who should be able to view the Vitals page upon initial rollout 8/5:
- terhardt@nd.gov
- DSeymour@nd.gov
- pbohn@nd.gov 
- stebourgois@nd.gov 
- cobraun@nd.gov
- dkrabben@nd.gov 
- lapeterson@nd.gov
- mzander@nd.gov
- shall@nd.gov

In ID, confirmed with Bree that access to projections should be limited to the people who currently have access to it:
- Whitney Ascuena-Bolt - wascuena@idoc.idaho.gov
- Janeena White  - jawhite@idoc.idaho.gov
- Kris Sears - krisears@idoc.idaho.gov
- Bree Derrick - bderrick@idoc.idaho.gov
- Dan Moschella - dmoschel@idoc.idaho.gov
- Josh Tewalt - jtewalt@idoc.idaho.gov
- Christine Starr - cstarr@idoc.idaho.gov

No need to prevent any of these users from accessing Vitals.

cc @soniachokshi @Catacola ticket from our discussion friday

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@Catacola Did you start on this already? I might get started on it this afternoon if not.

**Comment by jovergaag** [comment]
@Catacola I'm going to assume you have not started on this. I'm going to pick it up this morning. LMK if I should stop. We'll chat at sprint planning soon anyway...

**Comment by jovergaag** [comment]
@sychang The list you added above is not the same list of users who can currently access projections for US_ID. The list is currently:
![image.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/e899e76a-3c5d-44b3-9b4d-70bfe0a1ee17)

Which should I use?

**Comment by jovergaag** [comment]
@sychang Do we need to restrict access to the goals/explore pages? Or do we leave them wide open?

There is one user listed above that does not currently have an account. Does that user get access to "Practices" ONLY or also to goals and explore? mzander@nd.gov

**Comment by sychang** [comment]
Chatted offline:
- No need to restrict goals / explore
- mzander@nd.gov gets everything
- for ID, remove anyone who is not on the list of 7 (they are all District Managers and they should receive Vitals but not projections).

**Comment by sychang** [comment]
@jovergaag we had a new user join the IDOC leadership team this week, mtransue@idoc.idaho.gov. Could they be added to the list of people who can view everything within ID? Same access level as wascuena@idoc.idaho.gov, bderrick@idoc.idaho.gov, etc. Let me know if I should document this request elsewhere.

**Comment by jovergaag** [comment]
> @jovergaag we had a new user join the IDOC leadership team this week, [mtransue@idoc.idaho.gov](mailto:mtransue@idoc.idaho.gov). Could they be added to the list of people who can view everything within ID? Same access level as [wascuena@idoc.idaho.gov](mailto:wascuena@idoc.idaho.gov), [bderrick@idoc.idaho.gov](mailto:bderrick@idoc.idaho.gov), etc. Let me know if I should document this request elsewhere.

This is fine. I'll make sure they are added to both the interim fix and long term fix lists.

**Comment by Catacola** [comment]
Whitney, Bree, Dan, Christine, and mtransue have had the prelaunch permissions set (yes to projections, no to practice). 

Janeena, Kris, and Josh do not have accounts yet.

**Comment by jovergaag** [comment]
@sychang Please confirm that this is the correct list of US_ND users for vitals launch.

**Comment by sychang** [comment]
Thanks for the tag! After talking to Tom, he gave us the go ahead to allowlist for all the program managers in ND (referenced in #1232) so we can go ahead and add them to the allowlist, which will make the full allowlist:
 
- terhardt@nd.gov
- pbohn@nd.gov
- stebourgois@nd.gov
- cobraun@nd.gov
- dkrabben@nd.gov
- lapeterson@nd.gov
- mzander@nd.gov
- shall@nd.gov
- dseymour@nd.gov
- relshaug@nd.gov
- adanderson@nd.gov
- smkopp@nd.gov
- jknutson@nd.gov
- jgourde@nd.gov

**Comment by sychang** [comment]
And for ID, the list should be all leadership + new program manager + 2 district managers

- Whitney Ascuena-Bolt - wascuena@idoc.idaho.gov
- Janeena White - jawhite@idoc.idaho.gov
- Kris Sears - krisears@idoc.idaho.gov
- Bree Derrick - bderrick@idoc.idaho.gov
- Dan Moschella - dmoschel@idoc.idaho.gov
- Josh Tewalt - jtewalt@idoc.idaho.gov
- Christine Starr - cstarr@idoc.idaho.gov
- jarguell@idoc.idaho.gov
- cbarrier@idoc.idaho.gov 
- mtransue@idoc.idaho.gov

**Comment by jovergaag** [comment]
@sychang adanderson@nd.gov does not exist in our existing list of users or in Auth0. Is this a typo? We do have rsanderson@nd.gov.

Do I go ahead and add adanderson@nd.gov?

**Comment by jovergaag** [comment]
I ended up adding adanderson@nd.gov since that email address is in both this issue and the pre-launch epic. LMK if I need to remove/change it.

**Comment by sychang** [comment]
adanderson@nd.gov is ok to keep! He is a regional program manager. Thanks for checking!
