### ISSUE TITLE
Change default view of dashboard for ID to be Community > Practices

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1195]
**What needs to be done? Why does it need to be done?**
Long-term, users should be able to select a default page of the dashboard that's most relevant to them. In the short-term, this task involves setting the default page to be Community > Practices for all users, since there will be more users accessing Practices than Projections.

cc @soniachokshi @Catacola 
**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
@sychang This is going to be the case for ID as part of this PR (https://github.com/Recidiviz/pulse-dashboard/pull/1192), should we make this update for ND too?

**Comment by sychang** [comment]
Yeah let's do it! What's going to be the interim behavior for people who have ND dash accounts but don't have access to Vitals yet? We can keep their default access as the community > goals page if that's what it was before.
