### ISSUE TITLE
Time series percent delta show "negative" 0%

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1199]
**Describe the bug**
Our `PercentDelta` components are showing a red/negative 0% for values that are -1 < value < 0. For example, a value of -0.4 rounds to 0 but still maintains the red/negative treatment.

@sychang Do we round this to 0 and show the gray treatment - or if the value is between 0 and 1 display one decimal place (-0.4%)

![Screen Shot 2021-08-03 at 11.05.03 AM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/e7dc7848-630a-43e3-a52a-c7ddcfd720b9)

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by sychang** [comment]
Let's round to 0 and show the gray treatment!
