### ISSUE TITLE
Methodology switches state tenants

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1205]
**What needs to be done? Why does it need to be done?**
When I am viewing ND Practices page on production and click "methodology" it opens the methodology page for Idaho practices. Intended behavior: open the ND methodology page.

**Additional context**
Assuming this is for Recidiviz users only, not blocking ND or ID launch, but should double check that's the case.

**Comment by jovergaag** [comment]
@sychang We haven't added ND methodology yet. We can use this issue for that purpose!
