### ISSUE TITLE
Vitals table is missing horizontal lines in portrait on tablet

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1211]
**What needs to be done? Why does it need to be done?**
On iPad, the Vitals table is missing the horizontal lines when in portrait orientation. For some reason, they are there in landscape but not portrait...

**Landscape**
![IMG_0007.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/3a11135e-ea18-42c9-a6a5-c94380c05f42)

**Portrait**
![IMG_0006.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/007f7e52-ab96-4a82-998b-58fd60f4d824)

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
@soniachokshi This is because of the feature requirement to keep the leftmost Office column static while in portrait so we can horizontally scroll the other columns. It's an HTML style that I tried to fix before, but I'm not sure we can actually change it.

**Comment by soniachokshi** [comment]
Ok, nevermind then! I'll just close out this ticket.
