### ISSUE TITLE
Names formatted incorrectly in Vitals

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1226]
**What needs to be done? Why does it need to be done?**
Names got flipped to show "lname,fname" for POs in ID, which is making the read only button show the incorrect name, and causing some name formatting to look off.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/ba0d00cf-e507-47a6-be8b-252f389f1cf4)

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/f11261a8-2fce-477e-8517-a4fe3e4aa066)

**Additional context**
Add any other context about the task here.

**Comment by Catacola** [comment]
This will probably be resolved by https://github.com/Recidiviz/recidiviz-data/issues/8775
