### ISSUE TITLE
[Pen Test Finding] Fix authorization bug allowing users to access other state's data

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1227]
**Describe the bug**
Users are able to copy an auth token into an API request for a state that they are not authorized to view, and receive the other state's data. 

For more details, see the [Cobalt finding](https://app.cobalt.io/recidiviz/pulse-dashboard-and-case-triage-application-august-2021-pt7441/findings/4)

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by jessex** [comment]
We are still awaiting an official severity rating from the pen testers, but we should assume it's likely to be MEDIUM or higher, and should prioritize is fairly highly regardless.

**Comment by jessex** [comment]
This officially has a MEDIUM severity and must be remediated within 60 days, but I would recommend looking within the next couple of weeks, personally.

**Comment by Catacola** [comment]
A fix has been developed. I'm working on the tests now.

**Comment by jessex** [comment]
Confirmed fixed by the pen testers!
