### ISSUE TITLE
Enable users to navigate between Pathways and Practices

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1259]
**What needs to be done? Why does it need to be done?**
Users should be able to navigate easily between Pathways and Practices. To achieve this, we will introduce a left sidebar that will allow users to navigate between Pathways and Practices, and will include links to global pages like methodology and user profile. 

Go to [section in PRD →](https://docs.google.com/document/d/1IvWek2k1qfrfJLCWB1kijUihcln-LKH2e8-WQVHCcFo/edit#heading=h.5brxap3xkn3c)
Go to [mocks in Figma →](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=1420%3A9457) 
Go to [prototype in Figma →](https://www.figma.com/proto/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?page-id=776%3A2729&node-id=1150%3A3256&viewport=250%2C48%2C0.14&scaling=scale-down-width&starting-point-node-id=1420%3A9457&hide-ui=1)

Additional information:
- The new left sidebar component should be named `ViewNavigation`, and be added to the `PathwaysLayout` component.
- The "Practices" icon should link to `/community/practices`, and The "Pathways" icon should link to `/pathways`.
- The Methodology icon will be added as part of another ticket - no need to add it as part of this work.
- The user icon will be moved from the top right corner nav, to the bottom left as part of another ticket - no need to move it as part of this work.

The `PathwaysLayout` is only available when the tenant is set to US_ID, so when you run the app locally using `yarn offline`, click on the profile icon in the upper right hand corner, select Idaho, then View Dashboard. Then manually change your path to `localhost:3000/pathways`. You should see the navigation skeleton on this page. 

Please use the colors and fonts from `CoreConstants.scss`. These are our standardized styles across Recidiviz products. Let Jen know if you need a color or font that is not in that file. Thank you!

**Note:**
Product names, icons, and descriptions are still being finalized. Feel free to use the icons and copy in the mocks as placeholders for now.

**Comment by jovergaag** [comment]
@soniachokshi The PRD and the "id pathways` mocks have a different icon for Methodology. Which should we use?

Also, which mocks should we use for the expanded state? I see that state in "nd pathways" but not in "id pathways".
