### ISSUE TITLE
Allow users to navigate to the Methodology from the sidebar navigation

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1261]
**What needs to be done? Why does it need to be done?**
In the sidebar navigation, we'll include links to other global pages, like Methodology. (In the future, we may add additional pages, like Updates or Help sections.) Our current plan is to build the Methodology page in Webflow, so this will open a new tab and navigate to that page. 

Go to [section in PRD →](https://docs.google.com/document/d/1IvWek2k1qfrfJLCWB1kijUihcln-LKH2e8-WQVHCcFo/edit#heading=h.5brxap3xkn3c)
Go to [mocks in Figma →](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=1525%3A324)

Since we do not yet have the methodology page built out yet, please add the Icon and Link, but do not enable the link yet.

Please use the colors and fonts from `CoreConstants.scss`. These are our standardized styles across Recidiviz products. Let Jen know if you need a color or font that is not in that file. Thank you!

**Comment by jovergaag** [comment]
@soniachokshi The PRD and the "id pathways` mocks have a different icon for Methodology. Which should we use? I assume the icon in the mocks, but just double checking.

**Comment by soniachokshi** [comment]
Yes, sorry for the confusion! Let's use the icon in the mocks. The screenshot in the PRD is updated now as well.
