### ISSUE TITLE
[ID] Build filters on the Pathways Prison page

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1270]
**What needs to be done? Why does it need to be done?**
This epic includes the issues to build the filters onto the Pathways Prison page for Idaho. Go to the [Pathways MVP x States spreadsheet](https://docs.google.com/spreadsheets/d/1jmY_yKjLs7HUeCx3UKFHSCJdhTckuYokWr5fv9EEVfs/edit#gid=510687045) to see which filters will be included on this page. 

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Closing this after discussion with @daschi, for each page we should do:
- epic for a page (e.g., prison page)
- FE ticket for each chart, which will include what it's filtered by
- BE ticket for each chart
