### ISSUE TITLE
Enable D3 deputy director access to Vitals

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1275]
**What needs to be done? Why does it need to be done?**
Add jarguell@idoc.idaho.gov to the allowlist for ID Practices page. He is the deputy director for D3 (right hand man for Cory, so they are in all of the same conversations and he was added to the call today, so we can go ahead and give him access). He should not be able to view anything else.

Note: This isn't urgent for this week. Am communicating to him that we are doing this next week.

**Additional context**
Add any other context about the task here.

**Comment by Catacola** [comment]
The permissions have been updated. I'll reach out to him to let him know he can sign up.
