### ISSUE TITLE
Support People on supervision chart over time

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1277]
**What needs to be done? Why does it need to be done?**
This task involves supporting the chart that shows the number of people on supervision over time on the supervision page.

PRD section: https://docs.google.com/document/d/1IvWek2k1qfrfJLCWB1kijUihcln-LKH2e8-WQVHCcFo/edit#heading=h.k93lttuiqxad
Mocks: https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=1252%3A6748

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
done!
