### ISSUE TITLE
High-Level Security Vulnerability: tar

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/pulse-dashboard#1282]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in the pulse-dashboard project. 

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days (October 1, 2021)

**Additional context**
Please find additional details about this vulnerability here: https://github.com/Recidiviz/pulse-dashboard/security/dependabot/yarn.lock/tar/open

**Comment by jovergaag** [comment]
@phenggeler That dependabot link doesn't work for me. I have access to dependabot but that specific alert is not showing up for me. Is there any additional information in the alert to help me figure out how to resolve it? 

I think I found the info on the vulnerability [here](https://snyk.io/vuln/npm:tar) (i think thats the right one), but it doesn't seem like there's a patch available for it yet. Does the dependabot alert that you see have more info on a resolution?
