### ISSUE TITLE
High-Level Security Vulnerability: immer

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/pulse-dashboard#1289]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days.

**Additional context**
https://github.com/Recidiviz/pulse-dashboard/security/dependabot/yarn.lock/immer/open

**Comment by Catacola** [comment]
It looks like having react-scripts pinned to 3.4.4 is causing the problem:
```
react-scripts@3.4.4 requires immer@1.10.0 via a transitive dependency on react-dev-utils@10.2.1
```

I just looked into upgrading to v4.x and it looks like we get a lot of nice things with it as well like fast reload during dev. I'll look into what it will take to upgrade to v4 later today. If it's too big of a chore right now, I'll see if there's a later version of 3 we can upgrade to.

**Comment by phenggeler** [comment]
Thanks for the research @Catacola.

**Comment by jessex** [comment]
I see that the alert is no longer active, @phenggeler. Do we think that's because a fix was backported into our dependency chain upstream, or did we already apply a change of some sort?

**Comment by phenggeler** [comment]
@Catacola could probably give a better answer, but Dependabot can be a bit noisy with layered dependencies. I will go ahead and close this one for the time being.
