### ISSUE TITLE
Low-Level Security Report

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/pulse-dashboard#1290]
---
due: 2021-12-08
---
**What needs to be done? Why does it need to be done?**
A low-level security report has been made. Please review the attached document and comment on the proposed mitigation section. 

Low-security issues have an SLA of 90 days, so please address this ticket by December 8, 2021. 

**Additional context**
https://docs.google.com/document/d/1V7biSMcxf2ZKL44EiH9D0foM-fT748l4Y0SbsFs9NVo/edit#

**Comment by phenggeler** [comment]
Hi @Catacola - this issue has an upcoming due date of December 8th. Would you be able to pull this into the next sprint? Please reach out to me with any questions.

**Comment by ohaibbq** [comment]
Closing as WONTFIX. Resolution added to the doc.
