### ISSUE TITLE
Create Supervision population over time chart

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1305]
Create the Supervised population (over-time) chart on the Pathways "Supervision" page.

`PagePrison` already has the Prison population (over-time) chart, the supervision population chart will be very similar, but the `compartment="SUPERVISION"`, and it will use the `supervisionPopulationOverTime` metric.

Please add the filter bar as well, and enable the Over Time, Gender, and Supervision Type filters.

**Comment by nasaownsky** [comment]
Note: I cannot see the Prison population (over-time) chart. There is just infinite loading. What data do I need?
