### ISSUE TITLE
High-level security vulnerability: set-value

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/pulse-dashboard#1323]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days. The deadline for resolution is October 17, 2021. 

**Additional context**
https://github.com/Recidiviz/pulse-dashboard/security/dependabot/shared-filters/yarn.lock/set-value/open

**Comment by phenggeler** [comment]
Hi @Catacola - just a friendly ping on this one. The SLA deadline is Oct 17 - do you think it will be possible to address (fix, dismiss, etc) in the upcoming sprint?

Thanks!

**Comment by Catacola** [comment]
Yes! I added this to our prioritized backlog for cosmos yesterday which is why I removed myself as the current assignee. It should get picked up and completed by the middle of next week.

**Comment by phenggeler** [comment]
Ah, great thanks @Catacola!
