### ISSUE TITLE
Pathways/Practices Responsive Layout

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1324]
**What needs to be done? Why does it need to be done?**
For the new Pathways dashboard and the existing Practices dashboard, we need to build a responsive layout that looks and works well on various desktop screen sizes and on tablet. (We have intentionally not optimized for mobile phone, as the likelihood that somebody pulls up this dashboard on their phone is very low.) 

Making the dashboard responsive entails (1) changing the layout of the pages and (2) building a collapsed version of the navigation. In order to ensure a consistent user experience across Pathways and Practices, we will need to update the layout and navigation for both products. 

The mocks for the responsive layout start [here](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=2124%3A2360) – in the [Figma file](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=776%3A2729) under "Responsive Design."

**Comment by jovergaag** [comment]
done!
