### ISSUE TITLE
(Day Zero) Assessment dates sometimes off by a month or a week from CIS

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/pulse-dashboard#1352]
@ohaibbq @Catacola 
(CC @colincadams in case DQ-related)

When going through supervision mismatch data with POs the other day, we found several places where our assessment dates were off. There was a loose pattern of our dates being consistently a little while after the dates shown in CIS, so it seems likely that we're latching onto e.g. the date when an assessment is certified, rather than when it occurred.

Examples from yesterday:
- DOC ID: 121599, we have their last assessment as 8/24/2021, but the actual was 7/13/2021 (CIS shows 7/13/21)
- DOC ID: 100946, our records show an assessment on 7/28/21, CIS shows 7/20/21
- DOC ID: 136175, we have last assessment as 3/19/20, CIS has 2/19/20
- DOC ID: 129845, we think his Supervision Level is ‘HIGH’, they think it’s ‘MODERATE’. They also think the person's risk level is MODERATE, so they think the risk/supervision levels match. We have the client's last assessment on 05/12/21, and a score of 25. ** Serena isn’t confident of her transcription on this one.
- DOC ID: 128895, we have their last assessment as 08/9/21, CIS has it as 08/3/21. ** Serena isn’t confident of her transcription on this one.

**Comment by colincadams** [comment]
Is this a subset of #1351, or do we think this is a separate issue?

**Comment by cawarren** [comment]
Suspect you're right, likely the same issue. Closing this one and bringing the additional examples over there.
