### ISSUE TITLE
Apply 'case update' filtering to discharge, early discharge, and LSU eligibility during ingest

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/pulse-dashboard#1353]
@Catacola @ohaibbq 

_Note: This isn't as urgent as other Day Zero work, it's more a follow-up issue to make sure we incorporate some of the learnings from the week into the tools._

**Is your feature request related to a problem? Please describe.**
Please add the new Case Update filter logic that Damini developed into our logic for determining LSU eligibility, discharge eligibility, and Early Discharge eligibility in the data that Case Triage and emails cue off of.

**Describe the solution you'd like**
Colin and Kris got case updates data parsing, and we found and enumerated a list of common terms in the title field that indicate someone will not be considered eligible for LSU, discharge, or early discharge. 

**Additional context**
The original effort is documented [here](https://docs.google.com/document/d/1MxkPRY0p3xERlbIYabnV45gviVnGyDKAL4DGhlwmTIw/edit#); we'll need to formally start ingesting case updates, and you'll have to ping Damini or Kris for the actual resulting script.

**Comment by jkgerig** [comment]
Closing in favor of Recidiviz/recidiviz-data#9724
