### ISSUE TITLE
[US_ID] (Day Zero) We're missing some UAs that show up in CIS, and were entered in a timely fashion

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/pulse-dashboard#1360]
**Describe the bug**
For Day Zero, we're trying to filter out individuals with a positive UA within the last 12mo from LSU consideration. However, we're finding that our UA data has some strange gaps that we're not understanding. 

Examples:
- DOC ID: 127030, they show up in CIS as having a positive UA on 5/12/21, and the CIS backend also shows that it was entered on 5/12/21 (so not after the diff was sent to us). But, this UA doesn't show up in our ingested data at all.
- DOC ID: 53692, they show up in CIS as having a positive UA on 2/2/21, and this is also not in our data. 

@ohaibbq could you help investigate? We've taken it about as far as Kris can from the CIS side, still not sure what's afoot.

**Comment by jkgerig** [comment]
Fixed by re-run on 2021-10-13.
