### ISSUE TITLE
Add warning banner to login page

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1405]
**Is your feature request related to a problem? Please describe.**
Some states, like MI, require an access warning to be displayed on the login screen. The goal of this task is twofold:
1. See if we can detect a user's domain on the login screen. If we can, display the banner at the top once we detect the user's domain.
2. If we can't, display the banner to everyone

```
Recidiviz applications are restricted to authorized individuals in the performance of their assigned duties.  Any unauthorized use, misuse, or modification of the data in transit or from this system is strictly prohibited.  This system and the equipment are subject to monitoring to ensure proper performance of applicable security features or procedures.  Such monitoring may result in the acquisition, recording and analysis of all data being communicated, transmitted, processed, or stored in this system by a user.  If monitoring reveals possible evidence of criminal activity, such evidence may be provided to Law Enforcement Personnel.
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by sychang** [comment]
Deadline is completing by EO Jan

**Comment by jovergaag** [comment]
This has been configured in staging for both Case Triage and Leadership Dashboard. @phenggeler is going to send the URL to Michigan to get their stamp of approval. Once we receive that, I will enable it on Production.

I was not able to find a way to detect the user's domain on the login screen. This means this is enabled for all users.

**Comment by phenggeler** [comment]
Hi @jovergaag - Michigan has come back to me asking for a slight modification to the language. They've asked that we add the following 2 sentences to the banner:

"Unauthorized use of the system is prohibited and subject to criminal and civil penalties. Use of the system indicates consent to monitoring and recording."

The full banner notification, therefore, will be:

> Recidiviz applications are restricted to authorized individuals in the performance of their assigned duties.  Any unauthorized use, misuse, or modification of the data in transit or from this system is strictly prohibited.  This system and the equipment are subject to monitoring to ensure proper performance of applicable security features or procedures.  Such monitoring may result in the acquisition, recording and analysis of all data being communicated, transmitted, processed, or stored in this system by a user.  If monitoring reveals possible evidence of criminal activity, such evidence may be provided to Law Enforcement Personnel. Unauthorized use of the system is prohibited and subject to criminal and civil penalties. Use of the system indicates consent to monitoring and recording.

They are fine with this in production, so we can go ahead and ship it once ready! Would you please let me know as soon as it is available in production, as I need to send them evidence to close out the first round of MI compliance? We have a deadline of Jan 30 on this one. 

Thanks for all the help!

**Comment by jovergaag** [comment]
@soniachokshi I updated the copy to match the above request. Let me know when you have had a chance to do the design review on this and I'll move it to production!

**Comment by jovergaag** [comment]
Design: https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=4344%3A139

**Comment by jovergaag** [comment]
@phenggeler and @soniachokshi http://dashboard-staging.recidiviz.org has the updated login footer. Take a look and let me know if this is good to send to prod!

**Comment by sychang** [comment]
FYI I just went to staging and I see some text overlap when I do so (I'm on Chrome on a 13 inch Macbook so my screen is a bit smaller)

![image](https://user-images.githubusercontent.com/6633887/151194407-74818673-4694-4055-a48e-b5fa5f0328b5.png)

**Comment by phenggeler** [comment]
@jovergaag - this is awesome, thanks so much. I am going to go ahead and share with MI (they might accept our staging environment as evidence).

I understand there might be some tweaks to the layout/look, but I don't think we need to wait to show this to MI.

Thanks!

**Comment by jovergaag** [comment]
> FYI I just went to staging and I see some text overlap when I do so (I'm on Chrome on a 13 inch Macbook so my screen is a bit smaller)

It's fine on a 15 inch Macbook. Maybe we reduce the L and R padding to reduce the vertical height of the footer? @soniachokshi ?

**Comment by jovergaag** [comment]
@sychang I reduced the left and right margins by quite a bit and it looks fine at what I am estimating is a 13" screen width. Can you take another look at it for me?

**Comment by sychang** [comment]
When it's fullscreen, all good (screenshot below). When it's smaller than fullscreen, it overlaps a bit still but I wouldn't block shipping on this!

![image](https://user-images.githubusercontent.com/6633887/151496690-77887c5b-742d-447c-9b2b-9cc8f8d1dcf4.png)

**Comment by jovergaag** [comment]
This is in production! Closing.
