### ISSUE TITLE
Enable kcliffor@ access to Practices

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1419]
**What needs to be done? Why does it need to be done?**
Enable the deputy district director in D4, kcliffor@idoc.idaho.gov , access to ID Practices.

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang Did you confirm or notify kcliffor@ of this new access? Please close when you see this.

**Comment by sychang** [comment]
I did!
