### ISSUE TITLE
Enable ND practices access to more program managers

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1422]
**What needs to be done? Why does it need to be done?**
These program managers have now been briefed on ND practices and should be allowed to access the entire Recidiviz dashboard, including the Practices page. This task involves adding them to the allowlist.

Brian Miller – brianlmiller@nd.gov – HR representative
Kristin Plessas – kplessas@nd.gov – Sex Offender Lead Officer Minot
Lea Quam – lmquam@nd.gov – Program Manager Transitional Facilities (Parole)
Corey Schlinger – cschling@nd.gov – Program Manager in charge of Pretrial
Anthony Soupir – tsoupir@nd.gov – P/P Training Coordinator (Tony)

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
The permissions have been updated. I will wait until the export tomorrow to verify them in Auth0

**Comment by jovergaag** [comment]
@sychang I spot checked these in Auth0 and they're all looking good! I'll let you close this issue when you see this.

**Comment by sychang** [comment]
Thank ya very mucho!
