### ISSUE TITLE
Pathways TN no data error state crashing page

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1443]
**What needs to be done? Why does it need to be done?**
On Tennessee > System-Level Trends > Prison > Prison Population over time chart, selecting the filters time period=5 years, gender=female, facility=MCCX throws an error because the chart returns no data that meets the criteria (there are no females incarcerated in the MCCX facility). Here is the URL: https://dashboard-staging.recidiviz.org/system/prison/countOverTime?ageGroup=All&facility=MCCX&gender=Female&legalStatus=All&timePeriod=5%20years

Currently, the page crashes and shows the following error:

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/c9c50783-4893-4469-9ea2-f5c55843ef0d)

The intended behavior is that a "no data" error state should be shown with a prompt to reset the filters, similar to what happens on the ID charts when there is no data.

https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=1777%3A454

![image](https://user-images.githubusercontent.com/6633887/141833997-4d9d77c6-bab7-4df6-9ec0-28bd3e361a8f.png)

**Additional context**
cc @soniachokshi @jovergaag

**Comment by jovergaag** [comment]
I have been trying to reproduce this consistently and it seems to be a timing issue. Usually the no data state  is shown but occasionally I get this error. I think it is coming from lines 49-58 of `PopulationTimeSeriesChart`. If there is no data, `historicalPopulation = []`, which means that line 55 `historicalPopulation[0].date` throws an error. 

I'm not sure why we would ever end up in this chart if there is no data so we should 1. try to figure out why sometimes the `ModelHydrator` no data state is not catching this AND/OR 2. guard for instances where `historicalPopulation.length < 1` in the chart.
