### ISSUE TITLE
Enable temporary Pathways access for TN researcher

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1445]
**What needs to be done? Why does it need to be done?**
A meeting with Mary Karpos, Mary.Karpos@tn.gov, is happening at 12pm PT today to walk through Pathways and preview some early insights to share.

This task is to enable access to Mary Karpos access to the staging dashboard for the meeting. After the meeting, we will disable access.

**Additional context**
cc @evangreenlowe

**Comment by Catacola** [comment]
Mary has an account now and has confirmed that she can log on
