### ISSUE TITLE
Add "As of [date]" to prison population by facility chart

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1446]
**What needs to be done? Why does it need to be done?**
On the Tennessee > System-Level Trends > Prison population by facility chart, we want to make sure users know that the data is capturing the latest data that has been transferred to us. 

This task involves adding an "as of [date]" to the title of the "Prison Population by Facility" chart. 

The title string should now say: Prison Population by Facility as of [date].
The styling should be the same as the styling for the "List of people in prison as of [date]" chart. Here is the example of how it looks on the "List of people in prison" chart. 
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/440ac4b3-503b-4096-81f6-49983b0f92a1)

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@nasaownsky If you base this off of the `jovergaag/us_tn-data` branch, you can use the new `prison_population_snapshot_by_dimension` fixture which has the `last_updated` date in it.
