### ISSUE TITLE
[US_TN] Add "Admissions from supervision to prison over time" chart

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1450]
**Is your feature request related to a problem? Please describe.**
Add "Admissions from supervision to prison over time" chart for US_TN. This will require adding a new "Supervision to prison" page (`PATHWAYS_PAGES.supervisionToPrison`) for US_TN.

the `supervisionToPrisonOverTime` metric and fixture can be used for US_TN, with the same enabled filters currently set for that metric (ignore the filters shown in the design).

Once you have a PR up, I will sync the copy from the copy source and push up a commit so don't worry too much about customizing the US_TN page copy to match the designs.

[Design](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=3520%3A11484)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by nasaownsky** [comment]
I'm a little bit confused. There's two files `supervision_to_prison_count_by_month`: one with `us_tn` state code inside (new one), and other with `us_id` (old one). So how should I use different data from two separate files, when they've the same naming?

**Comment by jovergaag** [comment]
> I'm a little bit confused. There's two files `supervision_to_prison_count_by_month`: one with `us_tn` state code inside (new one), and other with `us_id` (old one). So how should I use different data from two separate files, when they've the same naming? @jovergaag

You can just use the new one with `us_tn` for the state_code for both states. We don't ever use the state_code in the data in offline mode so the same fixture file can be used for all states.
