### ISSUE TITLE
Pathways design polish

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1608]
**Is your feature request related to a problem? Please describe.**
These are design polish items for the North Dakota Pathways launch. P0 items are launch-blocking, all others are not.

**Describe the solution you'd like**
- [ ] **P0:** Left axis is cut off on some rate charts.

- [ ] **P0:** The Counts/Rates toggle should be Libre Franklin, 500. Currently, it is the default font. 

- [ ] **P0:** The left column is wider (which looks much better!), but now I think it's too wide. Can we reduce it down to 384px? Right now, it looks like it's about 448px. This might also help move the chart so it's not getting cut off along the right side of the page. Also, the page description (under the title) is not stretching across the full length of the container.

- [ ] P1: The labeling on the District filter is a bit confusing at the moment. The filter says "District" but the line items say "Office." In ND, they do use "offices." Could we rename the filter label to be "Office" and then remove "Office" from each line item? So, they'd just be Beulah, Bottineau, etc.

**Comment by jovergaag** [comment]
Closing since because I moved all of these to #1613
