### ISSUE TITLE
[US_ND] P0 bugs for ND launch

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1613]
**What needs to be done? Why does it need to be done?**
We had a big meeting where lots of people tried to find bugs in the ND page before we launch next week. Of those findings, these are the most important to fix. Please put up a PR with whatever you have finished by the end of your day and I will merge them ASAP them rather than waiting for all of these to be done in a single PR.

- [x] Sorting list of people in the person level tables crashes the page. I think this happens when there is a null value - we should default those to "Unknown". Feel free to temporarily remove some of the dimension values in the fixtures to test this.

- [x] Scrolling down the list of people in the person level tables crashes the page. I think this is also when there is a null value.

- [x] Supervision level filter is too narrow. If you enable the ND filter options - the drop down and selected state are off when selecting "Interstate compact"

![Screen Shot 2022-01-27 at 3.29.01 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/132caba7-e98c-43f6-be10-0efaf44381b5)

- [x] When on the "Supervision to Liberty" page, if you select one of the SUPERVISiON_TYPE filter options, then navigate to "Supervision" page it shows a No Data state because that filter is not enabled on that page and the dimension is not on the metric. Desired behavior: When navigating to a new page that does not have a filter enabled which is currently set to != "ALL", set it to ALL.

- [x] Change "90-day average" wording in the over time chart hover state to say "3-month rolling average"

- [ ] ~~filter out NULL values in the district and facility charts (you can set a few district or facility names to be null in the fixtures to test this. That should prevent this unlabeled bar from appearing on the chart.~~

![Screen Shot 2022-01-27 at 3.38.45 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/9b073693-2113-4888-bf60-e3de3a76e565)

- [x] Left axis is cut off on some rate charts. 

- [x] The Counts/Rates toggle should be Libre Franklin, 500. Currently, it is the default font.

- [x] The left column is wider (which looks much better!), but now I think it's too wide. Can we reduce it down to 384px? Right now, it looks like it's about 448px. This might also help move the chart so it's not getting cut off along the right side of the page. Also, the page description (under the title) is not stretching across the full length of the container.

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@nasaownsky The NULL values in the rows are causing lots of problems with out sums and counts so I'm going to work on a different solution so ignore that item. The only thing left is fixing the filter state when navigating between tabs.

**Comment by nasaownsky** [comment]
> @nasaownsky The NULL values in the rows are causing lots of problems with out sums and counts so I'm going to work on a more system wide solution -- so ignore that item. The only thing left is fixing the filter state when navigating between tabs.

I fixed it already in existing PR. Check that out :)
