### ISSUE TITLE
[for 2/9] Updated standards progress charts and tables

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#1643]
What needs to be done? Why does it need to be done?
Ticket for once we get 2/9 spreadsheet data from TN, creating the following assets for the TT's, Sandra's reports and Jahir's reports:
- For each officer, charts showing completed/remaining/overdue by task (counts and rates) - like in [this folder](https://drive.google.com/drive/u/0/folders/14vJoojabX5VSXK5HjyjKuuS4ClLiifZ2)
- For each officer, a CSV in the format of [this file](https://drive.google.com/file/d/1QTMEXwnh4ewBw_ZkT7rAbxvFoUlIJC93/view?usp=sharing)
- For Jahir's reports and Sandra's reports, charts showing total completed/remaining/overdue tasks by officer (should look something like [this](https://www.figma.com/file/pkhIrK2QaZi37rDpV5slBK/Practices-v2?node-id=618%3A1212))
- For Jahir's reports and Sandra's reports, the table showing # of tasks remaining and overdue per task per officer (should look something like [this](https://www.figma.com/file/pkhIrK2QaZi37rDpV5slBK/Practices-v2?node-id=618%3A1212))

*TTs*
Cirri King
Danielle Jackson
Brianna Bowman

*Sandra's Reports*
Robert Raburn
Jazmin Taylor
Abby Painter
Brandon Bullard
Anna Nordstrom
Ellie Schrage
Tyler Johnston

*Jahir’s reports*
Alvatyse Lang – LANGAL02
Torrey Smith – SMITTO13
Janita Burks – BURKJA02
Regan Bates – RICHRE01
Additional context
cc @soniachokshi

**Comment by macfarlandian** [comment]
Google Drive is updated with these files now. Some things to note: 

I updated the chart designs to more closely match the mocks so hopefully you won't really need to rebuild them anymore? Let me know how that goes

The directories were getting a bit unruly so I created separate Feb 10 (and Feb 7) folders within each group folder that contain all the files for that date. I regenerated the Feb 7 charts to reflect the new designs also in case you need to flip between them
