### ISSUE TITLE
ID Pathways Q1 new release (by 3/14)

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1656]
**What needs to be done? Why does it need to be done?**
We want to launch some new charts to a few users in US_ID before releases them to all ID users. Since we have some pages and charts live for all users, we will need to add the new charts on the currently enabled pages behind a feature flag. 

So, for the Prison, Supervision, Supervision to Prison, and Supervision to Liberty, all of the charts listed below except for the over time charts should only be enabled ONLY if the feature flag is true. Some of these charts have already been enabled in #1541 so you can cherry-pick those commits or build this functionality on that branch, whichever works for you!

The Liberty to Prison and Prison to Supervision to Prison will be controlled by the existing user permissions functionality.

The feature flat will be called `shouldSeeBetaCharts` and will be a computed getter in the `UserStore`. This should return true for all `state_code: recidiviz` users. Otherwise, there will be a `should_see_beta_charts` attribute in the `userAppMetadata` (please update the `UserAppMetadata` typing to reflect this as well).

Let me know if you have any questions!

Timeline:
We'll target this release to rollout by 3/14. We can test with 1-2 ID users ahead of time for data spot checking.

This task involves rolling out a new release of Pathways in ID by EOQ1 that creates feature parity with what is currently developed in Pathways ND:

**Adding the following pages:** 
- Liberty->Prison
- Prison->Supervision

**Adding the following charts:**
Liberty->Prison: 
- Admissions from liberty to incarceration over time
- Admissions from liberty to incarceration by district
- Admissions from liberty to incarceration by prior length of incarceration
- Admissions from liberty to incarceration by gender
- Admissions from liberty to incarceration by age
- Admissions from liberty to incarceration by race

Prison
- Prison population by facility
- List of people in prison

Prison->Supervision
- Releases from incarceration to supervision over time
- Releases from incarceration to supervision by facility
- Releases from incarceration to supervision by age
- List of releases from incarceration to supervision

Supervision
- Supervision population by supervision level

Supervision->Prison
- Admissions from supervision over time
- Time to admission from supervision
- Admissions from supervision by district
- Admissions from supervision by gender
- Admissions from supervision by race

Supervision->Liberty
- Releases from supervision over time
- Releases from supervision by district
- Releases from supervision by race
- Releases from supervision by gender
- Releases from supervision by age

**Adding the following filters:**
Liberty->Prison: 
- Time period
- Judicial District
- Gender
- Race
- Age

Prison
- Facility
- Age

Prison->Supervision
- Time pperiod
- Facility
- Gender
- Age

Supervision
- Supervision level
- District

Supervision->Prison
- District
- Gender
- Race

Supervision->Liberty
- Age
- Race
- District

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang The list of filters that you added here are not the same filters that are being used in ND. Do we specifically want ID to have different filters enabled? Or should we just use the same filters that ND is using?

**Comment by sychang** [comment]
Which ones are different? It's fine to basically have ID have the set that ND is currently receiving + any that ID already has.
