### ISSUE TITLE
[US_ME] Add permissions for users for MVP launch

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1661]
**What needs to be done? Why does it need to be done?**
Add user permissions for leadership group: 
Scott Landry - scott.landry@maine.gov
Susan Gagnon - susan.gagnon@maine.gov
Ben Beal - ben.beal@maine.gov
Sherri Black - sherri.black@maine.gov
Jeff Morin - jeff.morin@maine.gov
Anna Black - anna.black@maine.gov
Ryan Thornell - ryan.thornell@maine.gov

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang Add the list of launch user email addresses here please!

**Comment by sychang** [comment]
@ldfielding is going to confirm the list with leadership this morning. Assigning to Lily to add the names and email addresses once that's confirmed.
