### ISSUE TITLE
Enable navigation between Practices v2.0 and Pathways

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1679]
**What needs to be done? Why does it need to be done?**
Users will be able to switch between Pathways and Practices from the user profile. The existing sidebar navigation should be maintained for ID and ND until Vitals is fully migrated to Practices 

cc @agronomic to add mocks: 

**Additional context**
Add any other context about the task here.

**Comment by macfarlandian** [comment]
what should the URL of the new Practices landing page be?

**Comment by sychang** [comment]
Using a temporary placeholder: dashboard.recidiviz.org/practices

Will go through a naming exercise and update it EOW.
