### ISSUE TITLE
Ensure that the filters are identified as clickable objects

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1695]
**Is your feature request related to a problem? Please describe.**
We are going to try to improve our accessibility in Pathways. The first step is to ensure that the filters are clickable and can be navigated/used with the keyboard instead of only the mouse.

We use [WAVE](https://wave.webaim.org/) to help determine which components on the screen are not accessible. The filters are currently showing errors in WAVE, "Missing form label" Let's try to resolve the errors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by nasaownsky** [comment]
@jovergaag I don't have an access to the deployed version of app, and therefore I am unable to check WAVE outputs. Can you provide me with them? I'll try to sort out in it.

**Comment by jovergaag** [comment]
@nasaownsky WAVE can be used in local offline mode as well. Once it is installed, if you open the extension it should open a panel on the LH side of the browser (in Chrome, if you're using Chrome). Do you see that?

<img width="1783" alt="Screen Shot 2022-03-24 at 9 52 07 AM" src="https://user-images.githubusercontent.com/5872651/159969019-62435132-b01c-4801-9402-bb94e2376433.png">
