### ISSUE TITLE
Pathways - design polish

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1697]
**What needs to be done? Why does it need to be done?**
- [ ] Download data icon is incorrect size. Try to make the existing icon 16x16px. If that doesn't work with the icon imported from web-libraries use the icon below.
- [ ] Change the color of the highlighted bar(s) on the gold charts to #25B894
- [ ] Decrease the width of the LH Nav
- [ ] Make LH Nav icons smaller
- [ ] Change line and dot style in line graphs

[Design with red markup showing changes](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=4570%3A135)

**Additional context**
Add any other context about the task here.

**Comment by agronomic** [comment]
Here is a new icon attached (made sure that there were no half-pixels).
Should be 16x16.
![ic download](https://user-images.githubusercontent.com/11529268/158412992-06d78486-032e-4628-9f7d-c4e51da5aec8.svg)

**Comment by jovergaag** [comment]
> @jovergaag the figma markup says ''thinner sidebar (64px)", but current sidebar width is already 64px. We made this change during one of the previous design reviews: https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=2018%3A7131

OK, that is fine to disregard then. Thanks!
