### ISSUE TITLE
[Pathways] Officer chart redesign

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1717]
**What needs to be done? Why does it need to be done?**
Update the `countByOfficer` chart such that it is a horizontal bar chart instead of vertical bars. The designers have asked that we change the layout so that the page can scroll to show all of the officers, and the bars aren't so small and squished.

This means that the X-axis is the count, and the Y-axis is the officer name. We will want to re-enable the y-axis label to show the officer name. 

The `PageTemplate__body` will scroll and the height of the chart container will dynamically adjust to the height of the chart to fit all of the bars for each officer.

Let me know if you have any questions.

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang @soniachokshi The officer chart is quite heavy and is taking a long time to load for some states. ME loads fairly fast, but states with more officers (like TN) it is a very slow load, and crashes on IE11.

We had talked about showing a banner on the Officer chart or doing something else to alert the user that it may load slowly until we have the new consolidated backend. Do you have any details about how this should be handled? Is this a note on the chart? Banner? Hide the chart on IE11?

Please let me know how I should handle this.

**Comment by sychang** [comment]
Let's hide the chart on IE11 so at least the app doesn't crash. No other changes needed - we can message that it'll be slower to load and add a chart note if we get questions about it even after we message it that way.

**Comment by jovergaag** [comment]
Hiding the chart and section nav entirely on IE11 will be a lot of work. How do you feel about leaving the officer chart section link in the LH nav - then just showing a message that the chart cannot be loaded in IE11, using the same styling as the "No Data" or "Error" state for charts? 

@sychang

**Comment by sychang** [comment]
That sounds good!
