### ISSUE TITLE
Add P&P office linking prior to initially ingested data 

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#173]
**Describe the bug**
Charts containing info about closed cases don't link these cases to officers, and thus offices, prior to start of Recidiviz ingest. 

This affects:

- `Snapshots`
    - `SUCCESSFUL COMPLETION OF SUPERVISION`
        - `1 year` or `3 years`  selected AND [`rates` | `<specific office>` | `map`]
    - LSI-R SCORE CHANGES (AVERAGE)
        - `1 year` or `3 years`  selected AND [`<specific office>` | `map`] selected
- `Revocations`
    - `REVOCATIONS BY MONTH`
         - `1 year` or `3 years`  selected AND [`rates` | `<specific office>` | `map`] (rate is artificially high in these cases because total supervision population won't include closed cases)
- `Free Through Recovery`
         -  `FTR REFERRALS BY MONTH`
             - `1 year` or `3 years`  selected AND [`rates` | `<specific office>` | `map`] (rate is artificially high in these cases because total supervision population won't include closed cases)

**To Reproduce**
View any of the above charts. The best one is Successful Completion of Supervision, Rate, 3 years. 

**Expected behavior**
Charts contain information about location of supervision all the way into the past.

If they can't, they disallow viewing the relevant charts and selections for times > 6 months (until we hit July). 

**Additional context**
 All supervision cases terminated in ND, positive or negative, have an associated terminating officer, recorded in same place as the terminating officer for revocations. Users in ND think it would be reasonable for us to use this for closed cases to see where people were probably supervised. 

In the long term, they'd love if we could lock in place people with their supervising officer at a specific point in the past and where their supervising officer was located at that past point in time.

**Comment by jessex** [comment]
Our latest historical ingest re-run for North Dakota included a data fix to fill in historical officer assignments from a field we did not fully understand previously. With that re-run done and the calculations in the Dashboard, the issues related to this that were listed in the _Known Issues_ doc are no longer apparent. This is done!

🎉
