### ISSUE TITLE
[P1] Enable access for DDs on 3/30

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1732]
Names of DDs bolded at the bottom of the GTM doc: https://docs.google.com/document/d/1UihGqjQRWZIAPjVUHdfKs5IMRL3vQTNWyN7_lq6FKZI/edit#heading=h.24comnn2gfjc

@evangreenlowe to update this doc if you know the full attendee list

**Comment by danawillow** [comment]
Just to clarify, there are three groups:
1. Bolded people from that doc
2. Non-bolded people from that doc
3. People from the doc a few weeks ago

Which group should be part of the initial allowlist?

**Comment by danawillow** [comment]
Thanks! I just uploaded the new list and I'll check tomorrow to make sure it propagated through. After that we can ungate by uncommenting one line in auth0, which I'll plan to do Wednesday afternoon.
