### ISSUE TITLE
Add count view to reincarceration rate by previous stay length

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#174]
**Is your feature request related to a problem? Please describe.**
Users expected to be able to toggle to counts for the `Reincarceration rate by previous stay length` chart. They wanted to know how the reincarceration rates map on to quantities of people.

**Describe the solution you'd like**
Add count toggle. In count mode, the y axis becomes "Number reincarcerated." Each bucket then shows the number of people who, at the given follow up period, were reincarcerated given their previous stay length.  

**Describe alternatives you've considered**
Current situation is not allowing counts, but users pointed out an intuitive count for this chart.

**Comment by jessex** [comment]
Correct, @DmitryJakubovsky, this work relies on a `reincarceration_count` field being added to each row in that particular API response. The work can be started as soon as the fixture file is updated to include this, which I'll try to do today, but it cannot be merged until the calculation change has been deployed upstream.

**Comment by jessex** [comment]
@DmitryJakubovsky I have pushed up a branch with a single commit that adds the `reincarceration_count` field to the fixture file for this chart. You should be able to use this to add a count mode to the chart now!

https://github.com/Recidiviz/pulse-dashboard/pull/new/jessex/reincarceration-stay-length-count
