### ISSUE TITLE
Distinguish between positive and negative discharges in ND

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#175]
**Is your feature request related to a problem? Please describe.**
Having seen the successful supervision chart on the snapshots page, users want to re-look at how we map termination types from ND to our termination types, and how we classify terminations as positive. 

Our possible termination types are: `Absconsion`, `Death`, `Discharge`, `Expiration`, `External unknown`, `Revocation`, and `Suspension`. 

According to our methodology, we count `discharges` and `expirations` as successful completions. 

However, we map to `discharges` 3 types of terminations that seem non-positive to ND folks: 

- Case 15: released from custody (User thought this happens when people are released to prisons)
- Case 17: Returned to Original State-Violation (unknown what happens so unclear if positive or negative) 
- Case 18:  Terminated (User thinks this is used for CCC cases but may not be used any more) 

Can these be moved to a termination type we don't count as successful completion. 

**Describe the solution you'd like**
A termination reason corresponding to negative, possibly negative, or neutral terminations that aren't revocations.  

**Describe alternatives you've considered**
Leaving it as is and convincing ND the impact of the disputed case types on overall numbers is small. If true, that is a reasonably viable option. 

**Additional context**
ND case terminations to our termination type mapping should be double checked. If this is small magnitude impact, may not be worth a change, or worth backdating, but knowing how many people this affects would be helpful.

**Comment by kbinney** [comment]
Note: This maybe should be in a different repo.

**Comment by kbinney** [comment]
I have the #s for how many of each case, keeping internal.

**Comment by jessex** [comment]
@kbinney is this solved by the Case Termination charts we have already built? Or is this something different altogether? Let us know so we can either close this out or add more detail for engineering.

**Comment by kbinney** [comment]
This is something different (and in hindsight, should probably live in data repo). 

Our internal use of "Discharge" as a termination reason has become positively connotated, but some of the mappings we have from ND termination reasons to discharge are not seen by ND as definitively positive. This is an issue about having / mapping the specific listed ND terminations reasons to a termination type that is more neutral or unknown instead of to discharge. For context, this seems to have come up from North Dakota changing their minds about appropriate mappings from their to our termination buckets after they saw how our termination reasons are incorporated into the dashboard (specifically in the positive termination chart).

**Comment by jessex** [comment]
Got it! We should close this issue and file something in recidiviz-data then.
