### ISSUE TITLE
Allow TN users access to staging for QA ahead of launch date

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1776]

**Comment by jovergaag** [comment]
Users to add can be found here: https://docs.google.com/document/d/1vdXgI1S5JUcBVQYpkgvIgG0wZ71Ig5NocYHwhuVsFoc/edit#bookmark=id.udhhq4c2168n

**Comment by Catacola** [comment]
🎆 🇺🇸 🎆
