### ISSUE TITLE
Supervision population in over time chart vs dimension charts don't match

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1779]

**Comment by jovergaag** [comment]
https://docs.google.com/document/d/1vdXgI1S5JUcBVQYpkgvIgG0wZ71Ig5NocYHwhuVsFoc/edit#bookmark=id.yinj3nng68q

**Comment by Catacola** [comment]
Gut instinct is this is in the pathways views. I'm betting there are people who are somehow on supervision in two districts at the same time.
