### ISSUE TITLE
Lots of Unknown ages in prison person level tables

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1790]

**Comment by Catacola** [comment]
A quick query of `state_person` shows 115110 without a birthdate and 460851 with one. This looks like it is an ingest issue.

**Comment by jovergaag** [comment]
@Catacola Yes - this is being fixed in https://github.com/Recidiviz/recidiviz-data/pull/12410. I'll close this issue since its being fixed in the data platform.
