### ISSUE TITLE
[Launch checklist] TN Pathways

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1804]
**Target timeline**
- [complete] Internal staging bug bash: 4/6, launch review can begin
- [complete] 4/6: Soft rollout to TN leadership in staging
- 4/12 Roll out to leadership and district directors in TN

**Relevant links**
- PRD: https://docs.google.com/document/d/1IvWek2k1qfrfJLCWB1kijUihcln-LKH2e8-WQVHCcFo/edit#
- Engineering Design Docs: N/A
- Mocks or staging: https://dashboard-staging.recidiviz.org
- End user documentation and comms doc: (Go-to-market doc: https://docs.google.com/document/d/1UihGqjQRWZIAPjVUHdfKs5IMRL3vQTNWyN7_lq6FKZI/edit#
- Change management schedule: Refer to GTM doc

**What size change is being launched?**
Medium 

**Please link the security review bug:**

**Which states or clients is this change going to? Which non-state organizations will have access?**
Tennessee TDOC users.

**Write a short description of the change:**
Launch pathways to leadership in TN

**Does this change collect or show any new PII (of state staff, individuals under supervision or in facilities, etc.)?** 

_If new PII or PII-handling, privacy review is necessary._

Yes - there will now be a list of individuals shown directly in the tool, where previously, individual names were not visible. [PDD here](https://docs.google.com/document/d/1Z8fxogk1J_15VbGb0BVkstwgRX-j4uoqtKnPLZrfMgk/edit?usp=sharing)

**Will this change require change management (managing end-users from an existing workflow to a new workflow)?**

Yes, refer to [GTM doc](https://docs.google.com/document/d/1UihGqjQRWZIAPjVUHdfKs5IMRL3vQTNWyN7_lq6FKZI/edit#)

**Launch approval checklist. Check box and add date when sign-off is obtained**
- FYI Exec: @clementinej [MM/DD/YY] 
- FYI Product: @cawarren [MM/DD/YY] 
- [x] Eng: @Catacola  [04/11/22]
- [x] Data: @gheidkamp11  [04/11/22]
- FYI Security: @phenggeler  
- FYI Compliance: @phenggeler  
- [x] Comms: @evangreenlowe  [MM/DD/YY] 
- [x] Docs: @sychang PM [04/11/22] 
- FYI Design: @agr0n @soniachokshi 
- FYI Legal: @cawarren 
- FYI Privacy: @cawarren 
- FYI Accessibility: @cawarren 
- FYI Localization: Usually N/A

–––––––––––––––––– GLOSSARY ––––––––––––––––––

**Launch size**: A launch’s size is a rough estimate of its ‘splash’ - with users, with the press, etc. For example: 
- Large launch examples: New product offering or tool, major redesign or re-launch of existing product or tool.
- Medium launch examples: Launching an existing product or tool to a new state, adding a significant new feature in existing product or tool, updating the design in a noticeable way for an existing feature or set of features, 
- Minor launch examples: Small feature additions or changes to existing products or tools, improvements to methodology or ease of use. Generally not noticeable to the majority of end-users.

**Comment by sychang** [comment]
Thanks for kicking this off, @jovergaag ! Because this Pathways rollout is very similar to the past 3 Pathways rollouts in ND, ID, and ME, I've made most of the reviews FYI and only am requesting sign-off from @gheidkamp11 on the data side and @evangreenlowe on the comms side. All others, let me know if you have any questions!
