### ISSUE TITLE
[Workflows] Embed links to contact standards and IOT on client referral view

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1813]
Add direct links to IOT and contact standards in the referral view.

Talk to Serena for links and placement.

**Comment by Catacola** [comment]
@sychang Add doc links

**Comment by sychang** [comment]
@agronomic should jump in if you'd propose a different solution but I propose no UI change but just make the "i" icons next to each criteria clickable such that it opens the following policy doc in a new window (can use this link directly): https://drive.google.com/file/d/1YNAUTViqg_Pgt15KsZPUiNG11Dh2TTiB/view?usp=sharing

<img width="394" alt="image" src="https://user-images.githubusercontent.com/6633887/164595411-5e547580-c9eb-4f14-be4b-4a378357c80b.png">
