### ISSUE TITLE
[Workflows] Make it more obvious you can unselect a denial reason

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1814]
Design and UX work needed here, but otherwise TSIA

**Comment by sychang** [comment]
Mocks from Juan: 

<img width="273" alt="image" src="https://user-images.githubusercontent.com/6633887/164617906-12499630-6116-4f7a-b747-b58be10c4719.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/6633887/164618040-20910008-062b-46eb-9b3b-1dfd96d2a416.png">
