### ISSUE TITLE
Update FE auth so it can call existing backend and new one

### ISSUE THREAD

**Issue by danawillow** [Recidiviz/pulse-dashboard#1833]

**Comment by danawillow** [comment]
@ohaibbq I took a quick look at this and it seems like the auth token that gets passed to the backend is scoped to the logged-in user, rather than to the Pathways frontend. Since our auth0 tenant is the same for Pathways and Case Triage, I think this may just work? What do you think?

**Comment by ohaibbq** [comment]
I think that the token will have a different `audience`, so we'll need to configure a separate secret for the dashboard auth0 configuration.

**Comment by danawillow** [comment]
Got it- that might require the way we configure auth0: https://community.auth0.com/t/access-tokens-with-multiple-audiences/9911

**Comment by ohaibbq** [comment]
The Pathways API routes will be in their own Flask Blueprint, separate from the Case Triage API. This lets us apply a different authorization middleware to the routes.

For now, I think we should re-use the existing Auth0 configuration that the dashboard node server uses, that way the token that the dashboard frontend uses is valid.
