### ISSUE TITLE
[US_ID] P&P leadership pathways access 

### ISSUE THREAD

**Issue by ldfielding** [Recidiviz/pulse-dashboard#1909]
**What needs to be done? Why does it need to be done?**
We need to provide Pathways access to Brian Underwood and Dylan Hobson in ID: 
bunderwo@idoc.idaho.gov
dhobson@idoc.idaho.gov

**Additional context**
ID reports inaccuracies in Pathways supervision data that they're hoping we can debug with Brian & Dylan.

**Comment by jovergaag** [comment]
@ldfielding @sychang Do these two get full access to both Pathways and Operations or just Pathways?

**Comment by sychang** [comment]
Both pathways and operations!

**Comment by jovergaag** [comment]
@ldfielding This has been updated - they will have access starting Monday morning!

**Comment by ldfielding** [comment]
Excellent - thank you @jovergaag!
