### ISSUE TITLE
[US_ME] Pathways access for P&P and facilities leadership 

### ISSUE THREAD

**Issue by ldfielding** [Recidiviz/pulse-dashboard#1929]
**What needs to be done? Why does it need to be done?**
We need to extend ME Pathways access to Maine's 3 Regional Correctional Administrators and 6 CAOs, info below: 

Chris Arbour  chirstopher.arbour@maine.gov
Adam Silberman  adam.silberman@maine.gov
Robert LaPlante  robert.laplante@maine.gov
Amanda Woolford  Amanda.Woolford@maine.gov
Tony Cantillo  Anthony.Cantillo@maine.gov
Jeff Morin  Jeff.Morin@maine.gov
Matt Magnusson  Matthew.A.Magnusson@maine.gov
Lynne Allen  Lynne.Allen@maine.gov
Shane Blakely  Shane.Blakely@maine.gov

**Comment by sychang** [comment]
Got it! Added this as high-priority in the pathways backlog so we should be able to get to it today. Going ahead and assigning to @jovergaag in case you see it before planning meeting.

**Comment by sychang** [comment]
Oops Jen is OOO this week, reassigning to @Catacola

**Comment by Catacola** [comment]
The sync from bucket to cloudsql failed because there was a duplicate row. I fixed the file in the bucket to unblock the users right now and removed the duplicate from the source table so the problem doesn't come back tomorrow.

**Comment by Catacola** [comment]
I've seen two of the new users successfully log in in the past day. Closing
