### ISSUE TITLE
Update jarguell@idoc.idaho.gov 's dashboard permissions

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1932]
jarguell@idoc.idaho.gov is a D3 district director but has a small caseload as well. He should have access to both Vitals and Case Triage, with his default view being vitals. 

What is currently happening: jarguell@idoc.idaho.gov :
- He has a small caseload
- When he goes to dashboard.recidiviz.org, it automatically redirects him to Case Triage
- There is no "back to dashboard" button that lets him navigate to Vitals as we would expect for someone with both Vitals and Case Triage access

What should be happening
- When he logs into dashboard.recidiviz.org, he lands on Vitals. From Vitals, he should be able to impersonate the caseload of any PO.
- When he logs into app.recidiviz.org, he lands on Case Triage
- (He should not have access to Pathways)

**Comment by Catacola** [comment]
`jarguell`'s row in the leadership table had a space at the beginning of this name. Fixed and am reexporting now.

**Comment by Catacola** [comment]
@sychang Did we ever get confirmation that this account is fixed?
