### ISSUE TITLE
`npm` vulnerabilities - June 3, 2022

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/pulse-dashboard#1940]
---
due: 2022-07-03
--- 
    
Please address the Dependabot `npm` [vulnerabilities](https://github.com/Recidiviz/pulse-dashboard/security/dependabot) in this repository.

**Comment by phenggeler** [comment]
@danawillow @sychang @Catacola - A few `npm` package issues. These have a due date of July 3rd. Thanks!

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this month.

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this week.

**Comment by Catacola** [comment]
Summary of work here: https://docs.google.com/spreadsheets/d/1znOu83c5suvngcpkC8t0kJ0wZYuWDH8PMCJ8IJQqbpI/edit#gid=1221932464

**Comment by phenggeler** [comment]
@Catacola - fantastic as always. If you could continue this Google sheet to document decision points, that would be great!
