### ISSUE TITLE
Fix data sorting issue on FE

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#1945]
**Describe the bug**
The BE is no longer sorting data before exporting it to the GCS bucket. Fix that.

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by jovergaag** [comment]
I think that continuing to sort in the data platform is preferable to sorting in the FE. Sorting the time series data in the FE is a pretty big performance hit.

**Comment by Catacola** [comment]
This was fixed in #11327 and CPed into prod in #11330
