### ISSUE TITLE
[Pathways][US_MO] Remove the NOT_HISPANIC filter option for US_MO

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1957]
**What needs to be done? Why does it need to be done?**
One is actually OTHER, and the other is NOT_HISPANIC. We should combine these on the backend then remove one of them in the FE.

Update: BE work has been finished. NOT_HISPANIC has been removed from all views for US_MO. The work here is to remove the NOT_HISPANIC filter option for US_MO from the race filter. If you see NOT_HISPANIC in any other filter options, please remove it there as well since that dimension value no longer exists in the Pathways views.

**Additional context**
Add any other context about the task here.

**Comment by danawillow** [comment]
It looks like this was already done in https://github.com/Recidiviz/pulse-dashboard/pull/1961/files#diff-b628918a2c50c0d5c6d314a9ea7fbabb60b25511414fad7b0ca8dbeb24293fb0, can you confirm @jovergaag?
