### ISSUE TITLE
[Pathways] "Liberty to Prison" is broken in offline mode

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#1960]
**What needs to be done? Why does it need to be done?**
The "Liberty to Prison" page is broken in `offline` mode because of the diffing logic. This will need to be fixed before Ilya starts working with us again since he only works in offline mode.

**Additional context**
Add any other context about the task here.

**Comment by danawillow** [comment]
Good catch! I'll take a look at that today.
