### ISSUE TITLE
Pull MAUs and WAUs for TN Workflows

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#1984]
The following questions should be answered for the strategy review
- How many monthly active users were there in TN in April? May? June?
- How many weekly active users does Workflows have in TN

These are likely metrics we'll add into the impact dashboards (to-be-scoped as part of generalizing workflows). One time numbers needed for now.

For additional context, here are the queries we used to run the numbers for case triage before we had the ID dashboard, in case they are useful for constructing the TN query:

Number of POs who are receiving a PO report
https://www.google.com/url?q=https://console.cloud.google.com/bigquery?sq%3D688733534196:58bb69d4497d46998ef7af8997ed2d86&sa=D&source=calendar&ust=1656832574649425&usg=AOvVaw2OaHMmzJEvgKMSt9CUpyzA

Case Triage Signups
https://www.google.com/url?q=https://console.cloud.google.com/bigquery?sq%3D688733534196:25a94d6cd1e544c6bb7486466fa94ffb&sa=D&source=calendar&ust=1656832574649425&usg=AOvVaw2TVFLO3n0kugOxLewjgZk-

Case Triage DAUs
https://www.google.com/url?q=https://console.cloud.google.com/bigquery?sq%3D688733534196:b1c386dd121d4b6ba5591c64ce37992f&sa=D&source=calendar&ust=1656832574649425&usg=AOvVaw3KHxOzSzNcU-7Pa5NjXV7-

Case Triage WAUs
https://www.google.com/url?q=https://console.cloud.google.com/bigquery?sq%3D688733534196:fab2a1b806a149b58b9d4e85f014a57d&sa=D&source=calendar&ust=1656832574649425&usg=AOvVaw2eU7TnPWTS77dOAuNGt8_n

Case Triage MAUs
https://www.google.com/url?q=https://console.cloud.google.com/bigquery?sq%3D688733534196:f9141186b2674e42bc61ff3369b100a8&sa=D&source=calendar&ust=1656832574649425&usg=AOvVaw0ysWwInlEFr1UtLt-NSeOR

**Comment by Catacola** [comment]
Numbers pulled directly from Auth0 dash.

TN users active in the last:
- 24 hours: 9
- 7 days: 39
- 30 days: 84

**Comment by Catacola** [comment]
Query for MAU by month:
```
SELECT count(distinct id)
FROM `recidiviz-123.pulse_dashboard_segment_metrics.users_view`
WHERE context_page_url = 'https://dashboard.recidiviz.org/workflows'
AND DATE(received_at) BETWEEN '2022-03-31' AND '2022-05-01'
```

April: 42
May: 13 <-- Seems suspicious. Will come back to if I have more ideas
June: 78
