### ISSUE TITLE
Configure webpack alias for src/lib/static

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#2]
Ported from @matthewroot's issue https://github.com/Recidiviz/recidiviz.com/issues/25 into this new repo.

When recidiviz.com was rebuilt as a React application in https://github.com/Recidiviz/recidiviz.com/pull/22, the existing JS and CSS code was moved to `src/lib/static` as most of that code was third-party or modified third-party. One minor problem as a result is that `import` statements identifying relative paths to dependencies in our React components become unwieldy, like this:

```import stateSelect from '../../../lib/static/js/stateRecidivismRandom';```

To improve this, we should use webpack's [resolve.alias](https://webpack.js.org/configuration/resolve/#resolve-alias) to define `import` paths like so:

```import stateSelect from 'Static/js/stateRecidivismRandom';```

I spent some time attempting to get this configured in https://github.com/Recidiviz/recidiviz.com/pull/22 but abandoned my efforts due to complications with Jest. In case anyone else wants to pick up this issue, here are a few tips:
1. Update `webpack.config.js` to add `resolve.alias` for `src/lib/static`
1. Add `eslint-import-resolver-webpack` package to help `eslint` resolve the aliased paths
1. Add to .eslintrc ("settings": {"import/resolver": webpack,})
1. Update `package.json` with configuration for Jest under the `jest.moduleNameMapper` property (note: this was the part that wasn't completely working for me): `"^Static(.*)$": "<rootDir>/src/lib/static$1”)`

**Acceptance Criteria**
1. A webpack alias for `src/lib/static` is available
1. There are no webpack compilation errors with aliased path(s)
1. Aliased path is successfully resolved during linting by `eslint`
1. Aliased path is successfully resolved during test runs by Jest

**Comment by matthewroot** [comment]
This issue should have been closed with #15 as it is no longer necessary. We might want to use webpack aliasing for something in the future but we can set that up when the need arises.
