### ISSUE TITLE
[US_ND] Create EarlyTerminationOpportunity.ts

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#2091]
We now define much of the config around an opportunity in a single class. See `src/PracticesStore/Opportunity/CompliantReportingOpportunity.ts` for an example.

The goal of this task is to create the `EarlyTerminationOpportunity` class.

Assume the earlyDischargeRecord will look like this and only exist for eligible clients:
```
{
  stateCode: str;
  externalId: str;
  formInformation: {
    judgeName: str;
    sentencingDate: date;
    sentenceLengthYears: num;
    chargeName: str;
  };
  reasons: {
    pastEarlyDischarge: {eligibleDate: date};
    eligibleSupervisionLevel: {supervisionLevel: str};
    eligibleSupervisionType: {supervisionType: str};
    notActiveRevocationStatus: {};
  };
} 
```

**Comment by Catacola** [comment]
@jovergaag This has been updated with the latest `reasons` shape according to https://github.com/Recidiviz/recidiviz-data/pull/14248/files

**Comment by jovergaag** [comment]
@Catacola What is the `notActiveRevocationStatus` any ideas? I assume there will be something in the object at some point?

**Comment by Catacola** [comment]
Actually there won't be. The key existing without anything in the object means they're not on active revocation status. In the future, when we do almost eligible, the object will contain details about their active revocation status if they have one
