### ISSUE TITLE
[Workflows] Update denied reason list to have checkboxes

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#2110]

**Comment by soniachokshi** [comment]
Mocks for the new denied reasons dropdown are **[here in Figma -->](https://www.figma.com/file/bHFeiTm7TswGqP3AOTYFSa/Workflows-Generalization?node-id=71%3A1343)**  

Some things to note:
- The copy in the button has changed from "Not eligible?" to "Update eligibility." 
- If the user selects one or more ineligibility reasons, the "Eligible" checkmark is cleared. 
- If the user selects the "Eligible" checkmark, all ineligibility reasons are unchecked / cleared out.
- The selected ineligibility reasons are reflected in the side panel at the top of the list, as seen [here](https://www.figma.com/file/bHFeiTm7TswGqP3AOTYFSa/Workflows-Generalization?node-id=105%3A514).

**Comment by soniachokshi** [comment]
cc @agronomic in case any questions come up next week while I'm out
