### ISSUE TITLE
[Workflows] Update global navigation icons

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#2112]

**Comment by soniachokshi** [comment]
For North Dakota, the global nav icons will be as follows: ![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/319269b0-1e1d-4014-909e-a28568a5ed84)

See full global nav mocks in Figma [**here -->** ](https://www.figma.com/file/bHFeiTm7TswGqP3AOTYFSa/Workflows-Generalization?node-id=2%3A17)

The SVG is attached![workflows_icon.svg](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/7bd5c1c8-7fb0-4881-9ce5-22a544638a3c)

**Comment by soniachokshi** [comment]
cc @agronomic in case any questions come up next week while I'm out
