### ISSUE TITLE
[US_ID] Demo mode access for Whitney (IDOC)  

### ISSUE THREAD

**Issue by ldfielding** [Recidiviz/pulse-dashboard#2120]
**What needs to be done? Why does it need to be done?**
Whitney from IDOC is giving a presentation at APPA at the end of August during which we'd like for her to be able to demo Case Triage, using demo mode with fake data. To facilitate that, we'd like to give her access to dashboard-demo.recidiviz.org. Whitney's email is: wascuena@idoc.idaho.gov. 

**Additional context**
Add any other context about the task here.

**Comment by ohaibbq** [comment]
This should be done now! @sychang @ldfielding Can you verify that Whitney is able to sign in and access the demo at https://app.recidiviz.org?

**Comment by ldfielding** [comment]
Whitney can sign in! Closing as completed. THANK YOU @ohaibbq
