### ISSUE TITLE
[Workflows demo] Add one almost eligible example to demo dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2140]
There are currently two examples of people who are eligible for Compliant Reporting in the demo dashboard at dashboard-demo.recidiviz.org. This task involves adding at least 2 clients who are "almost eligible" for CR. If there are two clients. One client should be almost eligible but for needing to be on minimum supervision for another X days, and another is almost eligible but for one more fee payment.

Assigning to Ian for now, but can reassign when we get to it!

**Comment by macfarlandian** [comment]
This is done! there are two almost-eligible clients in the demo data now (one for each officer) and I have made sure state engagement folks can access the feature. If anyone else needs access just ping me, closing this in the meantime

**Comment by sychang** [comment]
The demo app is currently not letting me select an officer. To repro:
- Landing on https://dashboard-demo.recidiviz.org/workflows/compliantReporting
- Try clicking on either of the two officers
- The dropdown closes but no clients show up

Any hypotheses why?

**Comment by macfarlandian** [comment]
yes it seems that the deploy today broke this but it has been fixed! sorry bout that

**Comment by sychang** [comment]
Selection working again! Hmm now I'm not able to see the almost eligible folks:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/6633887/185238420-ef59dcba-afd7-4d74-9e74-54fe21c7d717.png">

**Comment by macfarlandian** [comment]
huh your feature flag was missing, should be good now

**Comment by sychang** [comment]
All set, thanks!
