### ISSUE TITLE
[Workflows] Ensure we're logging all relevant interactions for impact metrics

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2148]
PRD: https://docs.google.com/document/d/1Dz0X_wHLy1aV1P1jmR2uDgVu5lKANS83iWkNXx7ezVE/edit#

Ensure we have the logging in place to set up impact metrics for this Workflows-specific dashboard: https://docs.google.com/document/d/1Dz0X_wHLy1aV1P1jmR2uDgVu5lKANS83iWkNXx7ezVE/edit#heading=h.n1r8666utoho

**Comment by jovergaag** [comment]
@sychang This ticket is for event logging only right - we don't expect to have the dashboard up and running for launch? I just checked with Ian, and he thinks it will be very difficult to get the dashboard up and running until we have events flowing.

**Comment by sychang** [comment]
Documenting after chatting with Jen offline - correct, this is just to make sure we are logging the right things so we can retroactively stand up an impact dashboard. We'll be creating new epics and tickets for actually getting the Looker dashboard live.

**Comment by jovergaag** [comment]
- [ ] frontend_caseload_search 
Still not showing ND data yet because we don't have staff. Here is the query to use to QA this once we have staff
```
        SELECT 
            s.*,
            d.state_code
        FROM `recidiviz-staging.pulse_dashboard_segment_metrics.frontend_caseload_search` s
        LEFT JOIN recidiviz-staging.reference_views.dashboard_user_restrictions d
        on s.anonymous_id = d.user_hash
        WHERE context_page_url LIKE '%://dashboard-staging.recidiviz.org/%'
        and d.state_code='US_ND'
        order by timestamp desc
```

- [ ] frontend_opportunity_status_updated
No data yet, which is a little surprising
```
       SELECT 
            s.*,
        FROM `recidiviz-staging.pulse_dashboard_segment_metrics.frontend_opportunity_status_updated` s
        WHERE context_page_url LIKE '%://dashboard-staging.recidiviz.org/%'
        and opportunity_type = 'earlyTermination'
        order by timestamp desc
```

- [ ] frontend_profile_opportunity_link_clicked
No data yet
```
       SELECT 
            s.*,
        FROM `recidiviz-staging.pulse_dashboard_segment_metrics.frontend_profile_opportunity_link_clicked` s
        WHERE context_page_url LIKE '%://dashboard-staging.recidiviz.org/%'
        and opportunity_type = 'earlyTermination'
        order by timestamp desc
```

- [ ] frontend_profile_viewed
We don't seem to be using this anywhere. I'm not sure where the person external id and client hash are being generated so at this point i have not been able to confirm if there are ND clients

- [ ] frontend_referral_form_printed
```
       SELECT 
            s.*,
        FROM `recidiviz-staging.pulse_dashboard_segment_metrics.frontend_referral_form_printed` s
        WHERE context_page_url LIKE '%://dashboard-staging.recidiviz.org/%'
        and opportunity_type = 'earlyTermination'
        order by timestamp desc
```

- [ ] frontend_referral_form_viewed
I see some events from the fake CLIENT_1 - nothing yet from real clients
```
       SELECT 
            s.*,
        FROM `recidiviz-staging.pulse_dashboard_segment_metrics.frontend_referral_form_viewed` s
        WHERE context_page_url LIKE '%://dashboard-staging.recidiviz.org/%'
        and opportunity_type = 'earlyTermination'
        order by timestamp desc
```

- [ ] frontend_surfaced_in_list
We are seeing ND `earlyTermination` events!

**Comment by jovergaag** [comment]
@macfarlandian Can you confirm that as long as we are seeing events in these segment tables that this is enough to start building the outcomes tracking dashboard off of? I believe it is, but just want to double check.

**Comment by macfarlandian** [comment]
I believe so, yes!
