### ISSUE TITLE
[Workflows] Queries to help widen the funnel outreach

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2151]
[This is the brief](https://docs.google.com/document/d/1aFEHjelaZWiRKkjahTbV9Ek9OAObg2iaKyVch_gzh_w/edit#heading=h.4htxwjwfgc3g) that we're following to reach out to users in TN and widen the funnel through GTM. Specifically, we're targeting a few groups of people

Reengaging users who haven't logged in in 30+ days

- Highlighting when there are new clients that have become eligible on officers's caseloads to bring them back into the tool and get clients reviewed quickly
- For people who are almost eligible, working with their officers to help them become eligible ASAP.
- The Looker dashboard gives us a lot of information to do this outreach (shoutout @macfarlandian), and having a few additional queries will enable us to engage on a regular basis will enable the outreach to be self-service. 

Needed queries are defined in this doc: https://docs.google.com/document/d/1aFEHjelaZWiRKkjahTbV9Ek9OAObg2iaKyVch_gzh_w/edit#heading=h.4htxwjwfgc3g

Additional context
Adding these queries to the Workflows Impact dashboard scope so we can support these in future for all Workflows and not require 1-off queries

**Comment by elianalauder** [comment]
In addition, would it be possible to trace the users submitting forms mapped to the POs who's clients they are submitting on behalf of?

**Comment by sychang** [comment]
@elianalauder that use case should be covered in this doc by the following. If you're looking for something additional, feel free to specify!

For each Workflows user (email address)
- Last login date
- A list of all officers they have ever searched in the tool
- A list of all clients they have viewed but not completed referral forms for
- A list of all clients they completed referral forms for who have not been officially transferred (furthest funnel stage reached is “form completed”)

**Comment by sychang** [comment]
Adding a request here to pull a list of all users in districts 10, 50, and 61. These are the users we will launch "almost eligible" to and want to do targeted engagement with.

**Comment by macfarlandian** [comment]
just want to clarify what the actual deliverable is for this ticket: a one-time data pull? a bunch of saved queries in BigQuery that someone else is going to run as needed? something else?

**Comment by clayciat** [comment]
per @sychang 's email "....the ideal deliverable is a set of saved queries that someone else can run on any given day to get the most up-to-date lists!"

**Comment by macfarlandian** [comment]
I have opted for the "mega-query" approach here just to keep the number of different queries from proliferating and getting difficult to manage. Some of these queries are quite long so I have saved them in BigQuery and will link them here: 

[User list](https://console.cloud.google.com/bigquery?sq=984160736970:27db0e1b88094f29a3ce1db4e6dea134)

[Almost-eligible clients](https://console.cloud.google.com/bigquery?sq=984160736970:ecc0a1dafdf84c23846f0cfe5134e592)

[Currently eligible clients](https://console.cloud.google.com/bigquery?sq=984160736970:60226d594a4a4e88860b80b9bd2ed6a2)

[Users marked as "denied"](https://console.cloud.google.com/bigquery?sq=984160736970:3a114652897d4339b0d23e5be5fbe4d4)

[Officers with unseen caseloads](https://console.cloud.google.com/bigquery?sq=984160736970:0df4e929d47e4d3ca008da35ccc1ad8c) (not exactly the same as "never searched" but the closest we can get)

[User activity and incomplete referrals](https://console.cloud.google.com/bigquery?sq=984160736970:4d4c43bff2ce49c4ba4f976ba2e556c6)

This should satisfy the linked requirements but I'm not closing the ticket yet ... will let @sychang verify and accept as she sees fit

**Comment by macfarlandian** [comment]
Probably a better and more accessible option is to create a connected Google Sheet. Each of the above queries has its own tab in [this sheet](https://docs.google.com/spreadsheets/d/1bLZEoYCRd8fefX6cL2J57-n7GxH4mpXblYljDkp3wf8/edit?usp=sharing)

**Comment by sychang** [comment]
Can access! Will run through this with Kim Thursday to confirm this gives us all the information we need for outreach and close the ticket once confirmed! Thanks!
