### ISSUE TITLE
[Workflows] Move clientUpdates into subcollections per tenant

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#2152]

**Comment by jovergaag** [comment]
https://github.com/Recidiviz/pulse-dashboard/pull/2149#discussion_r938333947

**Comment by macfarlandian** [comment]
I think what we want here is a subcollection for opportunities. The structure I would propose is this: 
- **collection:** `clientUpdatesV2`
  - **id:** `<client GUID>`
    - **document**: `{ ...whatever }` (probably nothing for now but in Case Triage we had some generic client-level updates so presumably that will be supported here eventually as well)
    - **collection:** `opportunities`
      - **id:** `compliantReporting`
        -  **document:** `CompliantReportingUpdateRecord`
      - **id:** `earlyTermination`
        -  **document:** `EarlyTerminationUpdateRecord`
      - etc
