### ISSUE TITLE
[US_ND] [Workflows] Form automation missing input for "crime names"

### ISSUE THREAD

**Issue by clayciat** [Recidiviz/pulse-dashboard#2194]
Ex.
Client: DXzs0GW2ycn_0JDF

**Comment by daschi** [comment]
from @justkunz 

> This is an IC Probation case, so that might not be an issue since they will not use this form for ET

**Comment by clayciat** [comment]
@daschi So for IC Probation cases, we should not expect to have data for "crime names"?

**Comment by justkunz** [comment]
I think we have the crime names for many of the IC Probation cases, but I would expect that hydration rate to be lower than the in-state probation cases.

**Comment by clayciat** [comment]
@justkunz Thanks! I'll close this ticket then.

**Comment by clayciat** [comment]
We are only missing "crime names" for a subset of IC Probation cases as the hydration rate for this data is lower than in-state probation cases. The current solution to display "<fill>" text is sufficient.
