### ISSUE TITLE
[US_ND][Workflows] Last thing the user inputs in form is not persisted when downloading form

### ISSUE THREAD

**Issue by clayciat** [Recidiviz/pulse-dashboard#2196]
When a user inputs text into the form, the last string they enter is not being saved when the “Download PDF” button is clicked. E.g In the phone number field, I first typed in “320740735” and then I erased that and typed in “4045754”. But when I download the PDF, the first string that I entered is what’s displayed.

![Screen Shot 2022-08-18 at 12.02.23 PM.png](https://images.zenhubusercontent.com/62e94cec581c5fa8bb1619c4/0558824b-e631-4c06-b39b-0b551e4b3ae5)

![Screen Shot 2022-08-18 at 12.02.37 PM.png](https://images.zenhubusercontent.com/62e94cec581c5fa8bb1619c4/4ae52e99-bc7f-49bf-899e-09bb0934f3f8)

**Comment by ohaibbq** [comment]
should be fixed in https://github.com/Recidiviz/pulse-dashboard/pull/2186
