### ISSUE TITLE
Add ineligibility reason - “On supervision for an offense resulting in the death of a person”

### ISSUE THREAD

**Issue by clayciat** [Recidiviz/pulse-dashboard#2265]
We thought this would exclude them from date calculation but per one of the Program Managers they will still have a date calculated.

**Comment by jovergaag** [comment]
@clayciat It would be nice to have this added to the copy doc, so that we have all the copy in one place. It will also require a code (Lily made up the codes for the other reasons.

**Comment by justkunz** [comment]
Is this something we think should be incorporated into the TES eligibility criteria?

**Comment by clayciat** [comment]
@justkunz Yes, I would think so but I'll defer to @ldfielding to confirm.

**Comment by ldfielding** [comment]
I think we could incorporate into eligibility criteria, unless it's complex to determine which offense codes fall under "resulting in the death of a person"?

**Comment by justkunz** [comment]
If we end up seeing the denial reason used somewhat frequently then we can prioritize adding this logic into the eligibility criteria. That way we'll also have labeled examples for the ineligible offense types.
