### ISSUE TITLE
[Workflows] Add the "Edit and collaborate" text and default timestamp at the top of the form

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#2291]
In TN, there is text on the top left of the form page that says "Edit and collaborate on the document below." And by default, it shows when the data was prefilled by TDOC data. If a user updates the form, that timestamp updates.
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/2397c626-2f1e-4a8b-9e8f-013c6d53a2da)

In ND, the top of the form does not have that text on the left. And it has no default timestamp on the right that shows when the data was prefilled. Can we add both of those to the top of the form to match between the states?
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/346b4540-1b2c-4b41-9047-2c7658afed2a)
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/d73de016-2301-4b61-a5c1-aa51932a4568)

**Comment by daschi** [comment]
@soniachokshi Until the `dateToday` field is added to early termination query (see: https://github.com/Recidiviz/recidiviz-data/issues/14967), I'll update the "Prefilled with data from ND DOCR on {date}" to just use today's date. I think this just means it could potentially be out of sync if something goes wrong with the view exports and we're displaying older data.
