### ISSUE TITLE
Streamline the generic code for bar charts

### ISSUE THREAD

**Issue by itsjon** [Recidiviz/pulse-dashboard#233]
**What needs to be done? Why does it need to be done?**
In https://github.com/Recidiviz/pulse-dashboard/pull/231, I started deduplicating bar chart code. My focus was on de-duping without changing any behavior, but the code itself could still be streamlined/made more readable.

**Additional context**
n/a

**Comment by jessex** [comment]
This has been done in recent updates, including in #404. Closing this out!
