### ISSUE TITLE
Replace stray jQuery usage with React components/patterns

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#24]
There is some jQuery dating back to a previous version of the app that lives on among a few of the views. This should be ripped out in favor of standard React patterns and components.

**Comment by jessex** [comment]
@DmitryJakubovsky I plan to add more tasks to the project board on my Tuesday but if you have time tomorrow and nothing else to work on, then this would be a good piece of tech debt to work through. If there are any usages of jQuery still in the codebase (I see a few imports of jQuery in the `src/` directory) then we should remove them:

- If it's still in the codebase but the code is unused, just delete the code that references jQuery
- If it's still in the codebase and it is currently being used, replace the jQuery usage with some React-friendly approach
- If it's still in the codebase and it is currently being used and there's no obvious way to remove it, document clearly on this issue why it can't be removed

Once all references have been removed, if they all can be removed, then let's remove the jQuery dependency from the repository altogether.

**Comment by Wmaileq** [comment]
Some investigations were made. 
Now jquery used by this packages:
bootstrap-datepicker (not used, removed)
datatables (not used, removed)
boostrap (used, so i will remove jquery functionality and replace bootstrap components with react-bootstrap).
