### ISSUE TITLE
Consolidate similar code in BarCharts.js

### ISSUE THREAD

**Issue by itsjon** [Recidiviz/pulse-dashboard#241]
**What needs to be done? Why does it need to be done?**
As of https://github.com/Recidiviz/pulse-dashboard/pull/240, there are a couple functions in `components/charts/revocations/BarCharts.js` that have been extracted from chart components and turned into more reusable code. While the reusability is good, these functions are similar to each other and could be further deduplicated.

**Additional context**

**Comment by jessex** [comment]
This has been completed over the course of recent updates, including in #404. Closing this out!
