### ISSUE TITLE
Add guardrails to datasets.filterMostRecentMonths

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#249]
**Describe the bug**
This function does not validate some assumptions that are implied by its implementation. Namely:
1. That the given list of data points has been sorted, and
2. That the given month count is greater than or equal to the given list of data points.

This function can produce non-sensical behavior if those assumptions are violated.

**To Reproduce**
1. Write a test case in `datasets.test.js` which provides a list of, say, 7 unsorted data points, and a month count of 12
2. Log the output of the function to console
3. See that it returns 5 unsorted data points, which is nonsensical

**Expected behavior**
The function would have raised errors for the violated assumptions instead of returning nonsensical output

**Comment by DmitryJakubovsky** [comment]
@jessex Do you think that throwing error is the best way to resolve this problem? Many chart components depends on this function, so how they should react on this exception?

**Comment by jessex** [comment]
Good question, @DmitryJakubovsky.

Ideally, if a single chart experiences this issue, it would have some way of displaying that it has experienced an error and consequently refuse to load the chart, instead of displaying malformed/nonsensical data. We don't have any such mocks for this sort of thing, but I think displaying an appropriate error message instead of the chart itself would be sensible. For example, a message like, "Encountered an error processing the data points for this chart with the selected filters applied. Please contact support@recidiviz.org for assistance." It would be centered in the current position of the chart and use a font, size, and color consistent with surrounding elements. How does that sound? Let me know if you have other ideas.

**Comment by DmitryJakubovsky** [comment]
As I understood, we should delegate it directly to charts. So should we do anything with `datasets.js`? Or just check [`chartDataValues.length < months`](https://github.com/Recidiviz/pulse-dashboard/blob/master/src/components/charts/snapshots/DaysAtLibertySnapshot.js#L61) in every char?

I think that functions from `datasets.js` make their work good, and this data becomes nonsensical only in a chart component.

**Comment by jessex** [comment]
No, I don't think we should delegate it directly to charts, because the function in `datasets` does not produce sensible output internally. See the example from the description above: A function which is supposed to filter and sort data can, under certain cases that don't live up to certain assumptions, just return an unacceptable number of unsorted data points. To me, that indicates that the function should have internal validation, and callers should handle its output/errors accordingly.

**Comment by jessex** [comment]
This is no longer relevant!
