### ISSUE TITLE
Current month data overall doesn't match current month data by officer

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#276]
**Describe the bug**
Selecting 1 month shows seemingly contradictory data between overall charts and by officer charts: 

Examples:

-  Revocations by month chart shows no revocations, but individual officers have non zero numbers of revocations
- Case terminations by type chart shows no data, but case terminations by officer chart has data

**To Reproduce**
1. Go to 'REVOCATIONS'
2. Click on '1 month'
3. Scroll down to 'CASE TERMINATIONS BY TYPE'

**Expected behavior**
I'd expect the total number of revocations in 'Revocations by month' to approximately match the total number of revocations in 'Revocations by officer' and the total number of terminations in 'Case Terminations by type' to match the total number of revocations in 'Case Terminations by Officer`

**Screenshots**
Can provide internally if useful

**Additional context**
The cause of the discrepancy here may also be affecting supervision release numbers in the COVID report. North Dakota asked us how we are defining supervision release numbers for the COVID report: the release numbers there seem low.

**Comment by jessex** [comment]
@jjdressel11 since you've done some ND data exploration recently, would you mind tackling this one in the near future as well? If you have bandwidth today then great, if not then early next week is reasonable, too.

**Comment by justkunz** [comment]
I believe this issue is caused because the case termination tables haven't been exported in April yet. So the by officer/period table is showing March data, and the terminations by month chart has no data because there is no row for April 2020 in the export. Looking at the views in BQ, there should be 3 terminations for April (2 expirations, 1 death), and the two views agree with each other.

**Comment by jessex** [comment]
Thanks for the quick triage, @justkunz! It's clear that we need a better way to know that the dashboard data export has not been done, especially around month boundaries. I'm going to file an issue related to that now. In the meanwhile though, I think we can close this @kbinney? Production looks sane and consistent again.
