### ISSUE TITLE
GAE deployment and production app management

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#3]
Ported from @matthewroot's issue https://github.com/Recidiviz/recidiviz.com/issues/23 into this new repo.

https://github.com/Recidiviz/recidiviz.com/issues/22 rebuilt recidiviz.com into a single page application using React. Currently this application is not deployable to GAE and also has no way to manage the application in production.

The app uses `webpackDevServer` to serve the app in development but we must use something more robust in production. [PM2](http://pm2.keymetrics.io/) is one viable option here. As part of this issue, a yarn script should be added to start the app in production, at a minimum.

The app will also need to be configured for deployment to GAE. @jessex can add additional details on recommended approach.

**Acceptance Criteria**
1. Application can be deployed to GAE
1. ~~Able to manage application in production~~
1. ~~Yarn script added for starting application in production~~

**Comment by jessex** [comment]
Comments also ported from the original issue:

>Note: PM2 is probably unnecessary at this point given that we're not doing any server-side rendering right now and just need to serve up the webpack-compiled index.html. This issue can probably be accomplished purely by configuring GAE. I'm going to scratch out AC2 & 3.

>Note to self for later: https://docs.travis-ci.com/user/deployment/google-app-engine/

**Comment by jessex** [comment]
Another thought: let's strive for both a staging and a production deployment.

**Comment by matthewroot** [comment]
Planning to address this week.
