### ISSUE TITLE
Make the "Revoked Individuals" list sortable by column

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#312]
**Is your feature request related to a problem? Please describe.**
No specific problem, but a requested "upgrade" to the current MO dash that increases the user-friendly problem-solving because they can do things like sort by officer and risk level.

**Describe the solution you'd like**
Next to each column heading, add "sort" icons to indicate that it is possible to sort the chart by that particular column. 

**Describe alternatives you've considered**
N/A - an alternate would be not addressing this and letting the table remain unsortable.

**Comment by jessex** [comment]
@sychang I want to clarify some of the finer details here now that this is in code review:
- As currently implemented in the PR, you can click a column header 3 times to cycle through: it starts in the default sort (sorting across multiple columns, as is today), then clicking it once sorts the table by that column in ascending order, then clicking it again sorts in descending order, then clicking one more time goes back to default. Does that sound right to you? I imagine we do want to have the ability to take the table back to the default sort, but we should be clear if that's the intent.
- I am guessing you want the sort icons to _always_ be next to a column header, right? As currently implemented in the PR, they don't appear until you click, and there's no visual cue that a given column header is clickable until you try.
  - Related, what should be the UI/UX for those icons (up and down arrows) if we go with the 3-state approach above? One idea would be the two arrows are always there but start out light grey, then you click into ascending order and the top one gets dark, then click into descending and the bottom one gets dark, then click back to default and both go light grey. But I'm not a designer, of course.
- Do you want to be able to sort across multiple columns simultaneously or only one? What we have in the current PR is just one, and I think it would be a good bit of complexity to make it multiple, and I'm not sure what multiple column sort would mean, so I assume single column is right.
- As currently implemented in the PR, the only sortable columns are officer and risk level. Did you want to be able to sort on more? On all of them?

@sychang let me know if you'd rather hop on a screenshare to walk through!

CC @DmitryJakubovsky

**Comment by sychang** [comment]
- Yes, click 3 times to cycle through ascending, descending, and default
- Yes, the sort icons should always appear in the header. Your UX suggestion works, where default is both light grey, then top arrow becomes dark grey for ascending, then flip to bottom arrow becomes dark grey for descending, then both return to light grey for default.
- Single column sorting is good, no need to add multi-column sorting
- We want to be able to sort on all of them. For violation record, let's try sorting by **total number of violations**.
