### ISSUE TITLE
[MO] Labels on page of chart exports showing what filters the user has selected

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#313]
**Is your feature request related to a problem? Please describe.**
User experience enhancement when exporting a table.

**Describe the solution you'd like**
Add labels on the page of chart exports showing what filters the user has selected, e.g., most severe violation = technical, supervision type = parole, time period = 1 year. 

**Describe alternatives you've considered**
N/A

**Comment by jessex** [comment]
I'm not sure I get this one, @sychang. The `methodology.txt` file in the .zip that you download in the Lantern view does include all of this information. Can you be more specific about what functionality is missing?

**Comment by sychang** [comment]
I believe this is asking to add the filters at the top of the exported image itself, in addition to the methodology.txt file so the image would look something like this:

<img width="950" alt="Screen Shot 2020-05-04 at 1 56 09 PM" src="https://user-images.githubusercontent.com/6633887/81002562-0a7f7400-8e0f-11ea-8017-6fa7a4891672.png">

**Comment by jessex** [comment]
Hm, okay! Previously @cawarren and I had discussed and rejected that idea. So I'm guessing it is back now and our previous overrule of it in favor of methodology.txt has been overruled based on feedback?
