### ISSUE TITLE
[MO] Add a visual cue for rate charts that are not statistically significant

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#314]
**Is your feature request related to a problem? Please describe.**
We don't currently convey when a rate chart has a sample size too small to be statistically significant. This can lead to misleading conclusions (e.g., if 3 of 3 individuals in a category exhibit some behavior, it would be harmful to conclude that 100% of all individuals in that category would exhibit the same behavior).

**Describe the solution you'd like**
For middle charts showing percent of people revoked by district (in rate mode), risk, race, gender, give a visual cue for a rate chart where the denominator is below 100 for the rate to be meaningful. 

**Describe alternatives you've considered**
Harder alternative: Ideally we’d build in a significance test here, and cue differences that are significant based on ones that are not. This would include a power calculation as well. 

**Additional context**
Mentioned a few times as feedback from LSC in the MO launch demos.

**Comment by sychang** [comment]
Mocks: https://docs.google.com/presentation/d/1G5mUPPqRAxkraq3RJkqzh1QKjp64jC9cV_EDK41_i6M/edit?usp=sharing

**Comment by jessex** [comment]
Making sure I understand: this treatment should be displayed when the denominator for a given calculation is less than 100? And it should only be for the charts below the grid and above the caseload table that display rates? You mention risk level, race, and gender charts, but what about the district chart in rate mode?

And in your mock slides, I don't fully understand item 3. Is it that if a _single_ bar in a given chart has a denominator which is too small, the you see an indicator next to the title and on hover it tells you which bar has the insignificance? Or is it if an entire sample size adds up to less than 100 across all bars?

**Comment by jessex** [comment]
For whoever works on this, here is the Chart.js doc on adding pattern styling: https://www.chartjs.org/docs/latest/general/colors.html#patterns-and-gradients

In short, we would use the [Patternomaly](https://github.com/ashiguruma/patternomaly) library to meet the UX in these mocks.

**Comment by sychang** [comment]
Correct on the question about denominator for a given calculation less than 100. I missed the district chart in rate mode - it should apply there as well.

For mock slide 3, it should be any single bar where the denominator is less than 100. So in that given mock, the Asian, Native American, and Pacific Islander bars should be called out.

**Comment by jessex** [comment]
That chart you showed isn't in the Lantern view, just to be pedantic. The chart that is in the Lantern view that includes race data has a breakout of Race x Risk Level, so there are around 30 different bars in the chart (not looking at it right now, estimating). Is there a limit to how many bars we would list? This is even more extreme in the district chart in rate mode, where there are nearly 50 districts. In some filter states that are very niche, you may expect that nearly all 50 bars have denominators below 100. Do we list all of them?

Related: what is the copy for this tooltip?

**Comment by sychang** [comment]
Ah got it, updated slide 4 with a proper chart and clarified:

There should be a warning indicator _next to the overall chart title_ if at least one category in the chart has a denominator <100 (but > 0). There **will not** be an indicator next to every bar.

Copy: Some categories in this chart may not be statistically significant due to having a sample size smaller than 100. Those categories are represented with line shading.
