### ISSUE TITLE
[MO] Include SMI in the supervision-level dropdown

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#318]
**Is your feature request related to a problem? Please describe.**
SMI (seriously mentally ill) is a supervision-level classification in MO that users should be able to filter by. It was mentioned multiple times in the MO demo and flagged as high-priority.

**Describe the solution you'd like**
Include "SMI" in the supervision-level dropdown in the filter bar at the top and update the charts and calculations accordingly.

**Describe alternatives you've considered**
N/A

**Additional context**
Calc issue filed at #3187

**Comment by jessex** [comment]
Is there a corresponding issue in recidiviz-data for the calc support, @sychang?

**Comment by sychang** [comment]
Done, at #3187
