### ISSUE TITLE
[MO] Include the filters selected in the revocation plot in the filter bar

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#320]
**Is your feature request related to a problem? Please describe.**
 (i.e., technical row) in the filter bar that sticks to the top of the page.  
Currently the filter bar shows what the dataset in the current page is filtered to, but does not include any selections made in the revocations chart. Users may forget what data they are looking at as they dig deeper because the sticky filter bar does not include the filters selected in the matrix. 

**Describe the solution you'd like**
Include the matrix selection in the stick top filter bar. 

![image](https://user-images.githubusercontent.com/6633887/81442657-a07e0c00-9139-11ea-903e-89c0121ba03a.png)

Behavior:
- If a single bubble is selected, the chip should say "[Violation type], [Number of violations] violations"
![image](https://user-images.githubusercontent.com/6633887/81442414-2f3e5900-9139-11ea-8418-f7ee310b9d79.png)

- If an entire row is selected, the chip should say "[Violation type]"
![image](https://user-images.githubusercontent.com/6633887/81444221-6a8e5700-913c-11ea-9b38-5f766efa61f3.png)

Clearing the filter selection should deselect the matrix selection, as well.

**Describe alternatives you've considered**
An alternate is to not put the selection in the top filter bar, but as a subtitle or note in each chart on the page.

**Additional context**
Currently, there would only be one filter at a time that appears in the bar because users can make one selection at a time. In the future, we may want to support selecting multiple bubbles or rows in the matrix, so building in the flexibility to add multiple filter chips could help future-proof this change.

**Comment by jessex** [comment]
Just a heads up: you've got a typo in misdemeanor, @sychang. 😛 

Clarifications:
- I'm guessing this addition to the bottom of the filter bar should not show _at all_ when nothing in the grid is selected, right?
- You want that "Clear All" link to undo the selection in the grid, right? But not to change anything in the rest of the filter bar?
- Is there shrinking behavior on scroll for this, as there is for the existing part of the filter bar?
- Assuming the previous one is no, there would be no animation behavior, but if there is shrinking then I am guessing we want it to animate/smooth the shrink the same as the rest of the filter bar?

**Comment by sychang** [comment]
- Correct, nothing should show _at all_ when nothing in the grid is selected
- Correct, "clear all" should undo the grid selection by not change anything in the rest of the filter bar. If that feels confusing, we can remove it from this initial version because there should only be one selection at a time for now
- There is no animating behavior for the new filter itself, but the presence of this additional filter _should not_ prevent the original filter bar from shrinking during scroll.
