### ISSUE TITLE
[MO] Change the methodology language to reflect the updated doc

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#321]
**Is your feature request related to a problem? Please describe.**
Minor updates to the current methodology to create more consistency with user language and clarify some methodology pieces.

**Describe the solution you'd like**
1. Change the headings and labels on the middle charts to avoid use of the phrase “revocation rate.” On revocations chart, hover over should say “percent revoked” rather than “revocation rate.” 

2. Once confirmed by @jjdressel11 , in defining most serious violation, add the text "For the purpose of this chart, the violation category of “escape ” is combined with absconding, since escape violations are relatively rare. Escape is listed separately in the violation record column of the “Individuals revoked” table at the bottom of the page."

Update the copy per this doc: https://docs.google.com/document/d/1hAMvVy3NLRKA3pevDbQv7eEA6oEPwVQ7rZTgZC3sgjs/edit?ts=5eb591c0#

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jessex** [comment]
@sychang I want to confirm that the district chart is still supposed to say "Revocation rate" when in rate mode. That's what the language doc states but the apparent inconsistency makes me want to clarify.

**Comment by sychang** [comment]
Good catch. Let me confirm in the methodology doc and ping things thread, my guess is we will want that one changed as well, it might have been missed in the doc.
