### ISSUE TITLE
[Nav Redesign] Create updated views from existing charts

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#325]
**Is your feature request related to a problem? Please describe.**
We will roll out the navigation redesign feature iteratively, in a way that will not break functionality for the app between commits, in case a release needs to go out in the interim.

The mini-PRD only goes so far as reorganizing existing charts into new views that match the updated conceptual hierarchy--it does not yet propose new charts. This first task sets up the new views that will be displayed in the app, but does not yet make them visible until a later task.

**Describe the solution you'd like**
1. Create new views, still nested under tenants but following a predictable package layout
    1. src/views/tenants/us_nd/community/goals.js, src/views/tenants/us_nd/community/explore.js, src/views/tenants/us_pa/community/explore.js, etc.
1. Compose the views with the existing charts, laid out in the order specified by the PRD
1. Ensure the Facilities page explore bar uses county of residence as the district, and ensure the two called-out charts have proper warning icons displayed for district toggling
1. Add ability to suppress goal display with a prop, for relevant charts (charts that currently display goals but are also going to be displayed on explore pages)
1. Add ability to hard-code filter options, for relevant charts (charts that are moving into a goals page)
    1. This shouldn’t require any component changes, actually, just a different pattern in the new views. Just pass in an array with a single hard-coded value, e.g. [36] for metricPeriodMonths, [‘ALL’] for supervisionType. They won’t be toggled because there will be no explore bar for that page, so the useEffect hook will never be invoked after initial page load
1. Make sure the new views are whitelisted in .eslintignore

**Describe alternatives you've considered**
N/A

**Additional context**
This is a child of #324.

**Comment by DmitryJakubovsky** [comment]
I added a few wrappers for maximum reuse components.
