### ISSUE TITLE
[Nav Redesign] Adjust app navigation elements (non-Lantern)

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#326]
**Is your feature request related to a problem? Please describe.**
We will roll out the navigation redesign feature iteratively, in a way that will not break functionality for the app between commits, in case a release needs to go out in the interim.

The mini-PRD only goes so far as reorganizing existing charts into new views that match the updated conceptual hierarchy--it does not yet propose new charts. This second task updates the actual navigation elements, building on #325. It updates the sidebar (visible only in the non-Lantern views for now), updates app routes for the non-Lantern views, 

**Describe the solution you'd like**
1. Match the sidebar UI spec in the PRD
1. Remap the app routes to an organizational hierarchy matching the nav hierarchy
    1. dashboard.recidiviz.org/community/goals, dashboard.recidiviz.org/community/explore, dashboard.recidiviz.org/facilities/explore 
    1. This only applies to the non-Lantern views for now. A later task handles the Lantern views
1. Point the new app routes at the new views
1. Ensure the existing logic for specifying available views for a state can handle this nesting (_shouldn’t_ be an issue)
1. Decide on the default landing points for each existing state
1. Remove the legacy views and routes
1. **Do we want existing app routes to be kept around but redirect to a particular page to ensure bookmarks and links aren’t broken?** How would they be mapped? To relevant explore pages?

**Describe alternatives you've considered**
N/A

**Additional context**
This is a child of #324.

**Comment by jessex** [comment]
@kbinney there is a question for you, bolded in the description.

**Comment by kbinney** [comment]
Keeping existing app routes and redirecting would be great. 

I'd map: 

- dashboard.recidiviz.org -> dashboard.recidiviz.org/community/goals
- dashboard.recidiviz.org/snapshots -> dashboard.recidiviz.org/community/goals
- dashboard.recidiviz.org/revocations -> dashboard.recidiviz.org/community/goals
- dashboard.recidiviz.org/reincarcerations -> dashboard.recidiviz.org/facilities/goals
- dashboard.recidiviz.org/programEvaluation/freeThroughRecovery -> dashboard.recidiviz.org/programming/explore

**Comment by kbinney** [comment]
Currently, the collapsed dashboard shows page icons users can switch between. The nested sidebar (new version described in this PRD) will work as follows:

- The top level headings (Community, Explore, Programming) will have an icon like the current sidebar. We will use the same icons. 
    - The “Snapshots” icon will become the community icon
    - The “Reincarceration” icon will be the facilities icon
    - The “Free Through Recovery” icon will be the programming icon
- The blue half circle will be next to the icon of the current top level heading
- The current subpage (Goals/Explore) will be indicated via bolding and a right carrot 
- When collapsed, the side bar should show only the icons and the blue half circle (This is the same as the current behavior)
- When a user mouses over the sidebar, only the sub options should be “clickable” and they should indicate this via changing the bolded option. The blue half circle and carrot do not change until the user clicks on a new page
    - For example, if you are on Community -> goals, there is a blue circle next to “Community,” a carrot next to “Goals”, and “Goals” is bolded. 
    - When the user mouses over Community -> explore, the half circle and carrot don’t change place, but “Explore” is bolded and “Goals” is not
    - Clicking should bring the user to the current bolded option
    - When the mouse is between options, the nearest clickable option should be bolded. As the headings (Community, Facilities, and Programming) are not independent pages, they should not be bolded nor clickable. As the user moves their mouse from “Community -> Explore” to “Facilities -> Goals,”  when the mouse gets closer to the second than the first, “Explore” will be unbolded and “Goals” will become bolded
    - The logic as to which version of the sidebar (full, icons only, fully collapsed) to show given the page size should not change from the current version

1. Side bar when on the community goals page 

<img width="200" alt="Screen Shot 2020-05-18 at 9 55 13 PM" src="https://user-images.githubusercontent.com/19810267/82277554-25e19780-9956-11ea-9505-89444a1f2bb1.png">

2. Collapsed version of the side bar on the same page

<img width="50" alt="Screen Shot 2020-05-18 at 9 55 23 PM" src="https://user-images.githubusercontent.com/19810267/82277553-25e19780-9956-11ea-9d78-cbf36ad3b100.png">

3. Mousing over the options while on the Community goals page. Clicking would bring the user to the Facilities -> goals page.

<img width="200" alt="Screen Shot 2020-05-18 at 10 14 54 PM" src="https://user-images.githubusercontent.com/19810267/82277548-25490100-9956-11ea-93c0-de6a04df40a8.png">

**Comment by DmitryJakubovsky** [comment]
@jessex @kbinney
I need to clarify one moment. Not when I open the site from iPad Pro I see only top-level icons and I cannot go to another page, because with the current behavior side menu only opens when hovering over, what I can't do with iPad.
 
![image](https://user-images.githubusercontent.com/64428485/82325230-87037c80-99e3-11ea-9933-781e57de1f6e.png)

Do you have any thoughts on this?

**Comment by kbinney** [comment]
Analytically, our users don't use ipads to access the site, so this isn't critical and I'd still like to optimize for the web version. 

The group of 3 horizontal lines next to `Reincarcerations` is actually a menu icon. Clicking them on web opens the sidebar fully, so the open on hover behavior isn't required. Does clicking on that icon open the menu on iPad? If so, no behavior change is needed. I'm asking our designer about a different icon or placement of that icon to make it more intuitive to users.
