### ISSUE TITLE
[Nav Redesign] Adjust app navigation elements (Lantern)

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#328]
**Is your feature request related to a problem? Please describe.**
We will roll out the navigation redesign feature iteratively, in a way that will not break functionality for the app between commits, in case a release needs to go out in the interim.

The mini-PRD only goes so far as reorganizing existing charts into new views that match the updated conceptual hierarchy--it does not yet propose new charts. This fourth task rolls the Lantern view into the navigation hierarchy that has already been rolled out for the non-Lantern views by #326.

**Describe the solution you'd like**
1. If desired, change from dashboard.recidiviz.org/revocations to dashboard.recidiviz.org/community/matrix
    1. Could keep around existing route and have it redirect if desired
1. No sidebar still, just change the relevant config and link from top-left logo
1. Update package layout for MO to match the rest of the app, i.e. src/views/tenants/us_mo/community/matrix.js

**Describe alternatives you've considered**
N/A

**Additional context**
This is a child of #324.

**Comment by jessex** [comment]
@kbinney, can you confirm the details described in the solution, as it pertains to the Lantern view, specifically items 1 and 2?

**Comment by kbinney** [comment]
I think this is right from conversations with Serena, but looping in to confirm with her. 

@sychang  - does this fit with our conversations?

**Comment by sychang** [comment]
1. Yes, if possible, let's go with subbullet option "i" to keep the existing route so MO users don't have to relearn what the URL is and change the name from "matrix" to "revocations". The MO user flow would then be: "dashboard.recidiviz.org/revocations" which redirects to "dashboard.recidiviz.org/community/**revocations**"

2. Yep

**Comment by jessex** [comment]
Sounds good. Thanks!
