### ISSUE TITLE
Gracefully handle timeouts and API failures

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#33]
Chart components that fail to load data through the API, as of writing, display a blank chart and no indication otherwise that there has been a failure. As of #32, charts will not display until the API call has succeeded. However, we need to also have some sort of view to ensure a reasonable experience when a failure occurs.

**Comment by jovergaag** [comment]
We now have an Error component with a nice message, and get notified via Sentry on failures. Closing!
