### ISSUE TITLE
[TO ESTIMATE] Add "choose a date range" as an option for "Time Period" filter

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#335]
**Is your feature request related to a problem? Please describe.**
We currently allow users to change the time period on the dashboard to view data for 1 month, 3 months, 1 year, and 3 years. However, we don't allow users to choose a custom date range, so they can't easily answer questions such as:
- How many people were revoked in November 2019?
- What was the district with the highest percent of individuals revoked between May and August 2019 (they might be interested in that date because it coincides with a key policy change)?

**Describe the solution you'd like**
At the bottom of the "Time Period" filter on the Lantern dashboard, add an option to "Choose a Date Range"

![image](https://user-images.githubusercontent.com/6633887/81889091-5b5a3f80-9568-11ea-8dd3-bd3454ab9f4b.png)

TODO: Needs UX work on date picker and how to display the custom date range once selected (unless we happen to already have a component to select a date range elsewhere in the codebase that we can reuse).

Once a date range is picked, update the charts to represent that date range. The subtitles of the charts should also be updated to reflect the time range. For example, if the date range is May 1, 2019 to August 30, 2019:
- The "Number of people revoked to prison per month" chart should begin on the left at May 1, 2019 and end on the right at August 30, 2019
- The subtitle should say "May 1, 2019 to August 30, 2019." Previously, it would have said something like "Last 6 months (12/1/2019 to present)" if the time period selected was "6 months."

![image](https://user-images.githubusercontent.com/6633887/81889900-47174200-956a-11ea-83a5-121db3318cb5.png)

**Describe alternatives you've considered**
When "1 month" or "3 months" are selected, allowing users to view the "previous month" or "previous 3 months." That requires a bit more UX revision than this option.

**Additional context**
Requested by MO stakeholder: "It would be nice to have the time period filter to be customizable or at least in one month increments. I can’t pull the April numbers now just for April as it will only do it for May. I have to set the filter to three months and then look at each individually to see what month they were revoked. It might be helpful as well when exporting that it pulls the date of the expiration into the spreadsheet or at least the month and year."

**Comment by sychang** [comment]
Will get a set of mocks over later today - a question for @jessex. Are there any constraints we would want to put on the selectable date ranges because they would introduce additional complexity? Example cases:
- Picking a time period in the current month (today is May 26, 20 but use wants to see May 1, 20 - May 15, 20)
- Picking a time period shorter than 1 month in general, not in the current month (March 15 - April 3)
- Any other edge cases you can think of, or any range we would _not_ want them to select?

**Comment by jessex** [comment]
The main one, as discussed on #339, is that we can't trivially support sub-month granularity for our full metric suite without work on the calculation side. So you can only select ranges that go from one month to another, i.e. everything starts on the first of a month and ends on either the last day of a month or the current day if the interval ends in the current month. So we can do April 2020 - May 2020, we can do May 2019 - May 2020, we can do December 2018 - May 2020, and we can do just May 2020. But we can'd do the cases you described in those first two bullets.

Another probably obvious one is that we wouldn't support start or end months that are more than 3 years ago, unless we also wanted to update the filters and our configured calculation jobs to calculate further back than this on a regular basis.

Other than those, everything else is just sanity checking: no start or end months in the future, no start months after end months.

And no, we do not have anything in this app yet to leverage for a date picker design. You could take a look at what's in the Covid Dashboard if that's helpful, but there has been issue getting that date picker to work fully in Firefox.

**Comment by sychang** [comment]
Out of scope for getting MO to steady-state, but to consider as a part of UP infrastructure unification.
