### ISSUE TITLE
[Lantern] For the line plotting number of revocations over time, add a trend line

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#337]
**Is your feature request related to a problem? Please describe.**
We do not currently show the trend in revocation for the time period shown. We would like a way for users to easily see if revocations are generally trending up or down for the time period selected.

**Describe the solution you'd like**
For the time period selected, add a trend line running across the full horizontal length of the chart, similar to the charts with trend lines on the existing ND dash.

![image](https://user-images.githubusercontent.com/6633887/81891621-80ea4780-956e-11ea-9eb2-5323d6591c74.png)

**Describe alternatives you've considered**
N/A

**Additional context**
TODO: There is an open followup item to discuss what a "significance test" would mean for this and decide whether one is necessary (this could add a non-trivial amount of work, pending the outcome of the discussion).

**Comment by jessex** [comment]
Clarifying questions:
* We want this visible in all time periods? What about when only a single month is visible?

**Comment by sychang** [comment]
Currently, it's not actually possible when time period = 1 month, right? If that's the case, then we would not show the trend line when only a single month is showing. We would want it visible in 3mo, 6mo, 1yr, and 3yr time periods.

Additional context:
There is a separate feature request on the list that asks for the data to be broken down week over week when the time period = 1 month, which could later enable the addition of a trend line when the time period = 1 month.

**Comment by jessex** [comment]
If by not actually possible you mean not possible to show a trendline for a single month, then I think the answer is _yes_ insofar as it is illogical to display a trendline for a single data point. Just wanted to make sure you didn't have some other UX in mind other than simply not showing the trendline in that state.

**Comment by jessex** [comment]
@Wmaileq you should be able to reuse the trendline functionality used in the charts used by the ND view.
