### ISSUE TITLE
[Lantern] For revocation rates by risk level, reflect the difference between low, medium, and high risk levels

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#338]
**Is your feature request related to a problem? Please describe.**
In the revocation rates by risk level chart, we don't currently explain what defines "low risk," "medium risk," and "high risk."

**Describe the solution you'd like**
On hover, add text that explains what classifies "Low risk," "Medium risk," and "High risk."

TODO: Get finalized copy for the hover text. If the hover copy becomes too long, we may opt for the alternates

**Describe alternatives you've considered**
1. Adding an index reflecting the difference between revocation rates for low, medium, high risk. 
2. Adding the definitions in the methodology.

**Additional context**

**Comment by jessex** [comment]
@sychang we will need finalized copy for this tomorrow so @DmitryJakubovsky can be unblocked.
