### ISSUE TITLE
Make landing page consistent with recidiviz.org

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#34]
We need to generally improve the landing page ("/") for the app, both authenticated and unauthenticated. This should likely copy the styling/layout of recidiviz.org once it has been overhauled, which should happen within the next couple of weeks (as of writing, July 24, 2019).

**Comment by jessex** [comment]
recidiviz.org has indeed been overhauled!

For this particular issue, we want to make the entire dashboard app visually consistent with the redesigned recidiviz.org. The favicon, the landing page, the color palette, the type faces, the logos, etc. The whole thing.

**Comment by jessex** [comment]
@jjdressel11 when I tried out both of the fonts (Libre Baskerville and Poppins), they didn't go really well with any of the current texts in the dashboard, paragraph or title or sub-title. Further, I didn't find a great place to reuse the dark green background anywhere on the dashboard, unless we wanted to really go all in, e.g. dark green for header, sidebar, and footer. I think we should use the dark green text for the top left logo text and I think we should adjust blue links and red goal lines to match the blue and red from the site.

However, that's all to do with the app experience of the actual views like Snapshots and Revocations and so forth. The landing page of the dashboard is a different thing entirely that deserves its own attention.

**Comment by jjdressel11** [comment]
I think it's okay that the fonts are different and that we don't have the dark green background anywhere on the dashboard. The use cases are significantly different (communicating information about who we are as an organization for a first-time visitor vs. communicating criminal justice analytics on an ongoing basis). I think that the landing page should definitely have more consistency with the website, but within the dashboard app we should keep the consistency to smaller elements (logos, using the dark green text color where it fits, using the same red as our logo for goal lines, etc.)

**Comment by jessex** [comment]
I think we should close this now that we've essentially replaced the landing page with the Auth0 login hosted on recidiviz.org. Sound good, @jjdressel11?

**Comment by jjdressel11** [comment]
Yep - closing!
