### ISSUE TITLE
Enable "Admission Type" filter

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#347]
PRD: https://docs.google.com/document/d/1314bPlAqvQGLFSUc9WNSZ7OUK52G3AoEKG6vPH3tgo8/edit#

The Revocation Matrix today provides directors of probation and parole an easy way to understand who is being pulled back into prison for violating terms of their supervision (‘revocations’). However, it only shows the most severe type of revocation - reincarcerating someone for the remainder of their sentence. In reality, there are many different types of reincarceration, and these users should be able to filter the revocation matrix to see results for any subset of them.

The admission types in PA are:

- All
- SCI - short-term sanction
-- 6-month
-- 9-month 
-- 12-month
- Revocation
- PVC
- Inpatient D&A
- D&A Detox
- Mental Health

**Comment by sychang** [comment]
PRD: https://docs.google.com/document/d/1314bPlAqvQGLFSUc9WNSZ7OUK52G3AoEKG6vPH3tgo8/edit#

Mocks: To update in PRD

**Comment by jjdressel11** [comment]
Admission Type filter has shipped in production for US_PA !!!
