### ISSUE TITLE
PA Admissions by "Agent" chart

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#350]
PRD: https://docs.google.com/document/d/1FLWWXBzarLtXNvt-DPHDsiGQmsSarcK7xaXagReZn_Q/edit#

We would like DOC leaders to be able to easily identify anomalies and standout agents to identify and understand anomaly agent behavior and properly allocate resources. The agency can work with individual districts and/or agents to address anomalies or set new agency policy to correct imbalances.

This will be a new middle chart in the Lantern dash:
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/d3946f3e-9d2c-47d4-ba7e-8983f2eebf7a)

**Comment by jovergaag** [comment]
@Wmaileq let me know if you have any questions on this. I will work on getting the fixture data updated to support this ASAP.
