### ISSUE TITLE
[Core] Add red/blue color to avg LSI-R score change in map mode

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#360]
**Is your feature request related to a problem? Please describe.**
The LSI-R score change (average) chart shows whites in Map mode (see below) for negative score changes.

![Screen Shot 2020-05-27 at 10 04 18 AM](https://user-images.githubusercontent.com/19810267/83031020-14595900-a002-11ea-9998-852f28d19baa.png)

**Describe the solution you'd like**

The positive/negative coloring  would be red / blue like in the Admissions versus releases chart (see below). Ideally, for the LSI-R score change chart, positive changes would be red and negative changes would be blue. Higher magnitudes = darker colors. 
![Screen Shot 2020-05-27 at 10 07 47 AM](https://user-images.githubusercontent.com/19810267/83031036-191e0d00-a002-11ea-8002-70ed2f8209c9.png)

**Describe alternatives you've considered**
Alternative would be positive is blue and negative is red (also a reasonable solution, but loses the good/bad association with red and blue) or all blue with color intensity matching value magnitude (not a great UX)

**Comment by jessex** [comment]
To be clear, @kbinney, this happens on the existing maps today. Nothing about the redesign introduces this behavior, it already exists. You probably know that but the first sentence in the issue description implies that this might be related to the redesign, so I want to be clear.

**Comment by kbinney** [comment]
Oops thanks for clarity. I checked the live dashboard and didn't see the white circles, but checking again I see I just missed them in the live version with real data. I'll edit the description.

**Comment by DmitryJakubovsky** [comment]
@kbinney, should we apply this color changes to all charts with similar maps?

**Comment by kbinney** [comment]
There are only a few charts with maps containing positive and negative numbers, which is where the red/blue color scheme applies. 

This one (LSI-R score change), and the Admissions versus release graph, which already uses the red/blu color scheme. Charts with only positive numbers should stay colored all blue, so this one is the only one that should change. 

If there are other specific charts that you think need this applied, let me know and I can review.
