### ISSUE TITLE
[Core] Add period information to maps in goal pages

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#361]
**Is your feature request related to a problem? Please describe.**
Most of the charts in the two goal pages have a map view option. However, without the explore bar at the top, the user may not be able to deduce the time period for the data when a chart is in Map mode on this page. 

See below for chart in map mode from goals page. 

![Screen Shot 2020-05-27 at 9 55 02 AM](https://user-images.githubusercontent.com/19810267/83029856-25559a80-a001-11ea-8a7f-cf3b2fa860ec.png)

**Describe the solution you'd like**
Add period information to the map view for the 4 charts on the community goals page and the one chart with map view on the facilities goal page. The charts show 3 years of information so the period should read "Month/1/year - present" with the month & year from 3 years ago / the first data point of the x axis in chart mode. For example, if 3 years of data started in June 2017, the period would be (6/1/2017 - present). See below for another chart that has this period information. 

![Screen Shot 2020-05-27 at 9 59 26 AM](https://user-images.githubusercontent.com/19810267/83029867-28508b00-a001-11ea-8423-d95268d41b3b.png)

**Describe alternatives you've considered**
The preferred alternative if the above isn't possible would be to remove the map view option entirely from charts on the goal pages. 

**Additional context**
This issue follows the nav redesign of the dashboard.

**Comment by jessex** [comment]
This should be straight-forward, @DmitryJakubovsky. We just make display of that period label component optional based on whether or not the map view is being shown for the relevant charts (all charts that have map view available and are in a _Goals_ view).
