### ISSUE TITLE
[Lantern] Violation chart UI fixes

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#365]
**What needs to be done? Why does it need to be done?**
In the Violation chart of the Lantern dash, there are a few small UI issues that MO recently flagged:
1. "Absconding" and "substance use" are categories of technical violations, so we want them to be categorized in **blue** as technical violations (they are currently in orange, incorrectly classified as law violations). Municipals, misdemeanors, and felonies should continue to be classified in orange. Note: We want to preserve the progression of severity in the chart and thus **do not** need to switch the ordering of absconsion and municipal bars (as a result, we will no longer have all blue bars on the left and orange on the right).
2. The methodology currently says "The yellow bars represent different categories of law violations” but the law violation bars are actually orange. Update that sentence of the methodology to say "The orange bars represent different categories of law violations.”

**Screenshots**
![image](https://user-images.githubusercontent.com/6633887/83434969-1015ad00-a401-11ea-8ee8-6f2e70208634.png)

**Additional context**
For #2, an alternate is to change the law violation bar color to yellow to match the methodology, but we'd have to ensure accessibility-friendliness if we go that route.

**Comment by jessex** [comment]
I could be wrong but I _believe_ this coloring scheme was specially requested initially by CSG. @jjdressel11 might recall.
