### ISSUE TITLE
[Lantern] Include "Weapon" in the "Relative frequency of violation types" chart

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#371]
**Describe the bug**
The "Relative frequency of violation types" chart is missing weapons violations (weapon_count field in the revocations_matrix_distribution_by_violation file). 

**To Reproduce**
1. Open dashboard
2. Scroll to middle charts and click "Violation" tab
3. All violations except "Weapons" are shown.

**Expected behavior**
"Weapons" should be added as a bar in the violation chart.

Two questions to answer by 6/4 (cc @jjdressel11 if you know):
- Where should the "Weapons" bar be ordered in the chart if we are showing least to most severe from left to right?
- Confirming this counts as a technical violation and should be blue (as opposed to law violation and orange)?

**Screenshots**
N/A

**Comment by DmitryJakubovsky** [comment]
@sychang  Can I start this issue or should I wait answers?

**Comment by sychang** [comment]
Sorry for the delay - I have the answers so you should be unblocked now:
- Weapons is a technical violation and should be a **blue** bar
- The weapons bar should be located in between "Special conditions" and "Substance use"
