### ISSUE TITLE
[Core] New design for ND explore bar

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#378]
**Is your feature request related to a problem? Please describe.**
The current "Explore bar" for the North Dakota dashboard takes up a fair amount of vertical space and lacks labels for the selections. This has worked for users so far, but it's not an ideal experience. 

**Describe the solution you'd like**
Proposing a new look for the filter bar similar to the Lantern filter bar. Mock attached below. 

**_The filter options left to right should be:_**

- Count vs rate
- Time
- Supervision type
- Office

![slim.png](https://images.zenhubusercontent.com/5b4f4cdccce7d56699051bb8/ef663ddf-506c-4659-9d74-4891c5743117)

Note: **in the mock, the time period and supervision type selections have a switched order from what I want.** The mock also has a different navigation structure than the live dashboard, so below is a modified mock with the filter bar in the live version, but with too much gray space between the filter bar and the important notes bar

As the page is narrowed, the size of the text of the filter titles should get smaller to take up less space, similar to the Lantern bar behavior. 

![Screen Shot 2020-06-05 at 2.04.59 PM.png](https://images.zenhubusercontent.com/5b4f4cdccce7d56699051bb8/dc238b66-aad4-4f4d-ab7e-be8aa7690055)

**Comment by jessex** [comment]
@DmitryJakubovsky, just to summarize: we basically want the non-Lantern explore bar to look and function (e.g. scrolling, animation smoothing) like the Lantern explore bar, but with its own set of options in its own order, and taking into account the fact that there is a sidebar in these views.
