### ISSUE TITLE
Update rate charts to show "exits"

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#395]
**Is your feature request related to a problem? Please describe.**
After using the Lantern dashboard, MO expressed that the rate charts as they are calculated today have limited usefulness to them because internally, they are using "exits" as the denominator in calculating revocation rates, rather than standing population, because it is a truer indicator of revocation rate.

**Describe the solution you'd like**
Show revocation rates out of exits _in addition to_ our current "percent revoked" out of total standing population so the rate charts become more useful to MO. Pending discussion, this can break down into a few tasks:

Calculation/data updates: From MO, "there is a chapter in our Offender Profile that provides counts of supervision closings, which are simply counts of offenders by the date of close (CYC_END_DT) for a field sub-cycle (SUB_CYC_STATUS = 'F')  in body status (TAK158)."

Dashboard updates:
- Update "District" chart to have a third toggle option taking the revocation rate with exits as the denominator
- Update the other middle charts (risk level, gender, race) charts to have a toggle similar to the "District" chart that shows rate with exits as the denominator. 
- Because we will now have more than 2 options and will have this visual pattern in the future, update the toggle UI to be separate chips to more closely match the rounded chip design in the mocks.

District chart toggle chips:
![image](https://user-images.githubusercontent.com/6633887/85741270-e4b47400-b6c7-11ea-97a8-e4091710b91d.png)

Risk level toggle chips:

**Describe alternatives you've considered**
- We could entirely replace the way we are calculating rates today with exits as the denominator. This would require only calculation and no UI changes, however we still want the existing calculation methodology represented on the dashboard, since many other states calculate their revocation rates based on standing population and we want to keep a consistent methodology across dashboards
- We could take no action and not update the calculation - in that instance, MO would likely stop using the rate portion of the charts.

**Additional context**
- Are there corresponding updates needed to the historical analysis?

**Comment by jessex** [comment]
@sychang just to be clear:
>Update the other middle charts (risk level, violation, gender, race) charts to have a toggle similar to the "District" chart that shows rate with exits as the denominator.

This wouldn't make sense for the Violation chart where the denominator is a fundamentally different entity. But it does make sense for risk level, gender, and race. Right?

**Comment by sychang** [comment]
Correct, fixing to remove violation

**Comment by sychang** [comment]
To discuss: Given all the recent discussion around the legal definition of revocation, this change might not actually match MO's legal revocation definition. Given that, what changes need to be made for this to make sense? Is there a scenario in which this request is obsolete given our current methodology?

**Comment by sychang** [comment]
Closing after discussion - even with this update, it is clear we will not be able to perfectly match MO's legal definition of a revocation, because that was never the intentional goal. We would end up creating a partial solution that adds yet more complexity to the dashboard. The notion of creating both a standardized definition of a metric as well as accommodating for state-specific definitions is something that is being scoped as part of UP / advocacy product workstreams, so this will be revisited as part of those discussions.
