### ISSUE TITLE
MO District revocation rates: Remove inactive districts

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#396]
**Is your feature request related to a problem? Please describe.**
On the District chart of the Lantern dashboard, the presence of "inactive districts" severely skew the scale of the chart such that it's difficult to tell the difference between the active districts. Here is an example of what the chart looks like with an inactive district at the far left where the rate appears to be 100% but the sample size is less than 5 (other districts with a sample size in the thousands).

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/2817a6cd-c3ae-46fd-b440-65ec9b22401f)

**Describe the solution you'd like**
Identify and remove bars for "inactive districts" from the District chart on the Lantern dashboard so the chart scale adjusts accordingly to better convey the relative weights of the rates in other districts. There is no additional visual treatment or information needed beyond removing the bars. 

Update the methodology text to add a sentence at the end discussing inactive districts: "This chart shows the total number of people revoked to prison from each district during the time period selected in the "Time Period" drop down menu. The districts are positioned in descending order from left to right, with the district with the highest number of people revoked at the left. If a person’s district is unknown (meaning they were not under active supervision in any district within 2 years prior to the revocation), they are not included in the district counts or rates. If a person’s district is inactive, they are not included in the district rates."

**Describe alternatives you've considered**
N/A

**Additional context**
This issue is prioritized 4th out of 17th in MO's ongoing support feature request list (#3313).

Attaching this issue to the historical analysis epic in case it impacts any fields.

**Comment by jessex** [comment]
We don't want the ability to toggle them on or off, we just want these inactive districts gone?
Can you provide a list of inactive districts?

**Comment by sychang** [comment]
Correct, we want the inactive districts removed entirely from the chart. MO mentioned we should be able to tell whether a district is inactive from the data but let me follow up with them to get an explicit list.

**Comment by sychang** [comment]
Current status: Waiting on Justin to get a list of inactive districts.

**Comment by sychang** [comment]
From Justin on inactive districts: There is a table (MASTER_PDB.LOCATIONS) in the warehouse that contains a field (LOC_STOP_DT) that is updated when a location is closed.

**Comment by sychang** [comment]
Closing this in lieu of a longer-term holistic scoping effort for keeping districts fresh and well-mapped, to be scoped into UP.
