### ISSUE TITLE
[Lantern] Add support for most recent recommendation to caseload table

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#401]
**Is your feature request related to a problem? Please describe.**
The caseload table in the Revocation Analysis Matrix view currently has a column for most severe recommendation in a given case. Through https://github.com/Recidiviz/recidiviz-data/issues/3358 we are also going to add support for the most _recent_ recommendation. We want to visualize both in the caseload table.

**Describe the solution you'd like**
A new column should be added to the caseload table, taking its data from a new key-value pair to be added to the caseload table's API response via https://github.com/Recidiviz/recidiviz-data/issues/3358. 

The sort functionality for this new column should be the same as for most severe recommendation.

**Describe alternatives you've considered**
The main alternative is to replace most severe recommendation with most recent recommendation, but we think providing both will give better context. 

**Additional context**
This cannot be released until https://github.com/Recidiviz/recidiviz-data/issues/3358 has been completed and released. But eng work can start on the frontend now (just need to update the fixture file)

**Comment by jessex** [comment]
@sychang a few questions:
* What should the column headers be for the two columns after this update?
* What should the revised column order be?
* Are there any methodology or other copy updates to make, e.g. in Additional Info for the caseload table?
* Anything else to be aware of?

**Comment by sychang** [comment]
- Column headers (let me know if there are any issues with abbreviation)
1. Existing column: "Most Severe Officer Rec." 
2. New column: "Most Recent Officer Rec."

- Column order should be Most Recent on the left and Most Severe on the right, preserve relative ordering with the rest of the chart (so they should both still fall between "risk level" and "violation record")

- Methodology copy update for the caseload table:
Change the section title from "Officer Recommendation" to "Most Severe Officer Recommendation" (keep original body)

Add a section titled "Most Recent Officer Recommendation" with the body text saying:
"The recommendation listed on the last violation report before the person was revoked, including any supplemental violation reports."

- None that I can think of right now!

**Comment by DmitryJakubovsky** [comment]
@jessex, are you already add the column with the most recent recommendation? I do not have access to the `Recidiviz/recidiviz-data` repository, so do not know the current status of this issue. Also, fake data doesn't have this column too.

**Comment by jessex** [comment]
@DmitryJakubovsky that work is being done this week, so you can feel free to move forward with this task. Don't worry about renaming the column header in the fake fixture data: assume for now that the column header will be unchanged and that all you need to change is the caseload table column text and the methodology copy text, both as outlined in Serena's most recent comment. 

Thanks!
