### ISSUE TITLE
Backfill "Officer (Agent)" chart to MO

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#409]
**What needs to be done? Why does it need to be done?**
PRD: https://docs.google.com/document/d/1FLWWXBzarLtXNvt-DPHDsiGQmsSarcK7xaXagReZn_Q/edit#

We would like DOC leaders to be able to easily identify anomalies and standout agents to identify and understand anomaly agent behavior and properly allocate resources. The agency can work with individual districts and/or agents to address anomalies or set new agency policy to correct imbalances.

This will be a new middle chart in the Lantern dash:

**Additional context**
This will be a backfill feature of #350

**Comment by sychang** [comment]
To discuss: If this is fairly trivial to do once PA is supported, or we'd want to do it to standardize dashboards across states, can prioritize this. If it would take 1+ weeks of work, not worth prioritizing because this was the lowest on MO's prioritization list (it is a PA-led request).

**Comment by ageiduschek** [comment]
We do not think there is any additional work to backfill for MO on top of PA - closing this out.
