### ISSUE TITLE
Enable admission type filter for PA Lantern view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#423]
**Is your feature request related to a problem? Please describe.**
We want users to be able to perform the same in-depth analysis that the Revocation Matrix view permits for revocations with other forms of reincarceration to prison, as well. This will require a new dimension of exploration in the app, the admission type.

**Describe the solution you'd like**
We want to add a new admission type filter to the Revocation Matrix (Lantern) view for Pennsylvania. We will eventually backport this to other Lantern states, such as MO, so it's important that this be a general-purpose component with configurable options in the dropdown.

As noted [in the PRD](https://docs.google.com/document/d/1314bPlAqvQGLFSUc9WNSZ7OUK52G3AoEKG6vPH3tgo8/edit#heading=h.nqrxyvvw7hz4), we want this new filter to be on the far right, and we want it to have the options listed there, in order. This includes the notion of nested options, as you can see in the case of the 
SCI options: selecting "SCI - All Short Term" should auto-select all of the nested "SCI" options. In the view, there will not be a specific value for "SCI - All Short Term" in the new column to be titled `admission_type`. Instead, there will be values for each nested SCI selection and if "SCI - All Short Term" is selected then it should sum up all of the SCI values accordingly.

There are other minor associated text changes called for in the PRD, e.g. the "Update Chart Titles" section.

**Describe alternatives you've considered**
There's no obvious alternative.

**Additional context**
This is a child of the [parent epic](https://github.com/Recidiviz/pulse-dashboard/issues/347).

**Comment by jessex** [comment]
@DmitryJakubovsky, there will need to be a new `admission_type` column added to all of the associated revocation matrix fixture files. This will require adding a new column to the fixture files in such a way that whether this new filter is selected or not, the numbers are sensible. Similar to last time, I have a Python script that should help you and this one actually already lives in the repository at `server/core/demo_data/add_dimensions_to_fixtures.py`. In short, it takes in a fixture file, a new column you want to add, and the numeric column whose value should be redistributed across the values of the new column. 

However, we want this new column to also feature an explicit value of 'ALL' that all of the redistributed values sum up to. Right now, that script will produce rows for all of the new `admission_type` values and all of their values will be distributed in a reasonable manner. We then want to make sure that a new row is produced for each conceptual set of rows with `admission_type='ALL'` whose value is the sum of all of the relevant rows with the same columns but different admission types.

To do this, you'd probably want to modify this block in the script:
```
for dimension in args.dimension_values:
            new_data_point = data_point.copy()
            new_data_point[args.dimension_label] = dimension

            for key in values_to_update:
                updated_value = values_to_update[key][dimension]
                new_data_point[key] = updated_value

            print('AFTER:  ', new_data_point)

            new_data_points.append(new_data_point)
```

The block also sum up all of the values that it sets in the split numeric column, and then at the end of this block, it should create a new data point that starts as `data_point.copy()` but then sets the numeric column with that summed value and sets the new column with 'ALL'.

Let me know if you'd like to discuss this further or if you need any help modifying the fixture files!

**Comment by DmitryJakubovsky** [comment]
Hi, @jessex! I need some help with fake data. I am creating a new file based on e.g. `revocations_matrix_distribution_by_gender.json` and if I am adding the `admission_type` field with all values described in the PRD then file size increases 14 times. Do you have any ideas to resolve this problem? Thx!

**Comment by jessex** [comment]
Hey, @DmitryJakubovsky: I have a design doc circulating in the team here for a long-term approach to the data complexity issue but that work won't be approved and then done for a few weeks more. In the meantime, I would suggest not putting all of the values from that column in the fixture file, maybe only 1 or 2. You could also remove some of the districts from across all of the fixture files, e.g. every district about "20".

If that's not workable then we can set up Git LFS as an intermediate step so that we can store larger files temporarily.
