### ISSUE TITLE
[Lantern] Allow users to select multiple districts

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#424]
**Is your feature request related to a problem? Please describe.**
MO has the concept of "regions," which consist of multiple districts. They would like to view the Revocations Matrix for a a region at a time and be able to compare regions.

**Describe the solution you'd like**
User should be able to select multiple districts in the district filter, e.g., 01 and 02, and then have all charts include data from both districts. For example, if there were 4 revocations from District 01 in June and 4 from District 02 in June, when 01 & 02 are selected, the number of people revoked should be 8.

This will operate by the same logic as the multiple location selection feature in ND (#3351), which includes no  de-duplication logic and work limited to the front-end.

On the front end, the UI needs to support the selection of multiple options in the dropdown and needs to show that multiple offices are selected in the preview. The UX can be the same as the ND dashboard, with the styling consistent to the Lantern UI and the upcoming "Admission Type" filter feature (#423). 

Mock style from #423:
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/552f5ffb-b818-4d1b-abf6-6c7e0af3c278)

When multiple districts are selected, "X selected" should be shown in the dropdown menu. Note, this is different from ND, where "X item selected" is the copy.

**Describe alternatives you've considered**
We could add additional dropdown options to represent regions, which would be pre-grouping the districts together. This could be a future addition but is low priority. 

**Additional context**
This is conceptually the same as #399.

**Comment by DmitryJakubovsky** [comment]
@sychang, are multiple districts supposed to be accessible only for MO, or in general?

**Comment by jessex** [comment]
In general. This feature should be available for MO and PA.
