### ISSUE TITLE
[Core] ND dashboard crashing on certain filter selections

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#428]
**Describe the bug**
The dashboard crashes (screen goes blank) when certain filters are selected. 

**To Reproduce**
1. Go to the dashboard and select North Dakota as your state in the profile. 

The behavior can be seen on

- Community explore when one month is selected. 
- Facilities explore when any county of residence is selected. 
- Programming explore when one month is selected. 

**Expected behavior**
Loading the page with selected filters applied

**Additional context**
Identified by Julia while doing demo to new team members

**Comment by jessex** [comment]
Sorry for the regression here, @kbinney! I have merged the fix and deployed to production. We should be all clear now. Let me know if you'd like to send out release notes (I also included an off-by-one pixel layout fix, but it's not an eventful [release](https://github.com/Recidiviz/pulse-dashboard/releases) overall).

**Comment by kbinney** [comment]
Thanks for the quick fix! I think no release notes needed
