### ISSUE TITLE
Separate "Supervision Level" dropdown for PA

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#431]
**Is your feature request related to a problem? Please describe.**
More details and context in this doc: https://docs.google.com/document/d/1ndwZw8PSAIJfLQkuUZmWEKeeqVH6S2PxaGeGXRsuKds/edit#heading=h.6pe088gkbuk8.

PA would like to see supervision levels in addition to case types in the admissions plot.

**Describe the solution you'd like**
Add a Supervision Level dropdown to the right of the Case Type filter. The dropdown should contain the following options:

- All (selected by default)
- Enhanced supervision
- Maximum supervision
- Medium supervision
- Minimum supervision
- Special circumstance supervision
- Monitored supervision

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/0af352fe-05fb-4c13-9bfe-e0816c0efa18)

**Describe alternatives you've considered**
PA originally proposed for us to include the supervision levels under the "case type" dropdown, but that does not map well to our schema, since there can be multiple case types per supervision period, but only one supervision level per supervision period. After discussing with @ageiduschek we decided it was best to keep them as separate dropdowns.

**Additional context**
N/A

**Comment by ageiduschek** [comment]
The task is tracking the front end work for this feature. Should be implemented for PA but not MO right now.

**Comment by jessex** [comment]
@Wmaileq, I plan to update the .txt `revocations_matrix_*` fixture files to include this new column on Wednesday, so you should try to avoid taking on this task until then. Alternatively, if you run out of other tasks in the meantime, you can add that column to the older/deprecated .json fixture files and temporarily point the backend of the app at those .json files to test.

**Comment by jessex** [comment]
@Wmaileq I pushed up a branch [here](https://github.com/Recidiviz/pulse-dashboard/pull/new/jessex/updated-revocation-matrix-fixtures-sep-2020) that includes a single commit which updates the fixture files for the revocation matrix to include a supervision_level dimension, and removes the outdated .json versions of those files. You should be able to use that for this ticket now.
