### ISSUE TITLE
Update bubble chart with PA-specific violation types

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#433]
**Is your feature request related to a problem? Please describe.**
PA has a different set of violations from MO that they would like to track in the violations history bubble chart of the Admissions Plot.

**Describe the solution you'd like**
The options on the y-axis of the Admissions Plot bubble chart should be as follows, from top to bottom:
- Low tech.
- Med. tech.
- Elec. monitoring
- Subs. use
- Absconding
- High tech
- Summary offense
- Misdemeanor
- Felony

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/935e4a37-107b-4fbd-b34e-cf9c2a10959c)

**Describe alternatives you've considered**
N/A

**Additional context**
These will match the violations shown on the Relative Frequency of Violation Types chart (#434)

**Comment by jessex** [comment]
@DmitryJakubovsky: similar to #432, the main thing here is that we want the `RevocationMatrix` chart to be capable of having different possible row values for different states. We want PA to have the rows listed in order as described in the description. Again, do not worry about making sure there are rows for all of these specific violation types in the revocation matrix fixtures--we'll just accept that demo mode for PA will have incomplete coverage for now. 

Another thing to note is that this is a few more rows than are currently in the revocation matrix for MO, so we want to make sure that the overall layout/styling of the chart and view continues to work for both states.
