### ISSUE TITLE
Update Lantern Violation chart with PA-specific violation types

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#434]
**Is your feature request related to a problem? Please describe.**
PA has a different set of violations than MO that it's tracking on the Admissions Plot. We would like to reflect these violations in the UI.

**Describe the solution you'd like**
In the "Relative Frequency of Violation Types" bar chart, violations on the bar chart (and their colors), from left to right on the x-axis, should be:
- Low tech. (blue)
- Med. tech. (blue)
- Elec. monitoring (blue)
- Subs. use (blue)
- Absconding (blue)
- High tech (blue)
- Summary offense (orange)
- Misdemeanor (orange)
- Felony (orange)

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/96fd8f1f-0dac-42cb-8b1a-64789889ee29)

**Describe alternatives you've considered**
N/A

**Additional context**
These are the same violation types and ordering as #433.

**Comment by jessex** [comment]
@DmitryJakubovsky: again, similar to #432 and #433, the main change here is that we want the `RevocationsByViolation` chart to be capable of graphing different types of violations for different states. We want PA to have this ordered set of violation types as shown in the mock above. And again, we don't yet need to update the revocation matrix fixture files to have all of these as possible values. We just want to make sure that PA and MO have the right values, that the chart is capable of supporting both, and that the layout/styling continues to work in spite of there being different amounts of bars per state.
