### ISSUE TITLE
[Lantern] Restrict Lantern district filters for users based on user metadata

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#437]
**Is your feature request related to a problem? Please describe.**
Full details in PRD: https://docs.google.com/document/d/1bxSg8JgQHFFZZDSjBUKM-fOtU-8r3FVieQD5J81crkA/edit#heading=h.c29ll7o2tvsa

The current Lantern tool is currently restricted to Department of Corrections agency leadership. MO leadership would like to enable regional- and district-level supervisors to be able to access the tool because they are best-positioned to drive operational change in their correctional system. Supervisors are in charge of one particular district or a region (a group of districts), so we want to only show them Lantern data for their own district/region. 

**Describe the solution you'd like**
Enable distribution of the Lantern tool beyond MO agency leadership to District Administrators and Regional Supervisors. We would like to do this by restricting the “district” functionality of the Lantern dashboard to the district(s) that a particular supervisor is in charge of. 

District administrators should see the same Lantern dashboard that exists today as if their district filter was selected. They should not be able to change the district that is selected. For simplicity, the UI can remain the same, but with the default district selected and the page filtered accordingly. If a user clicks the dropdown, their district will be the only option present:
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/63af7a3f-9cd5-43ee-a4cc-46b327495c9d)

Regional supervisors should see the same Lantern dashboard that exists today, with the default showing all of the districts in their region, with copy updated from “All districts” to “All districts in region,” and the ability to select individual districts in their region (in the below example, districts 01, 02, 03, and 04 belong to the regional supervisor’s region and those should be the only four districts that appear in the dropdown). With multi-district select functionality (#424), regional supervisors can select multiple districts at the same time. They should not be able to select a district or region that is not their own.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/2341c1d1-60ee-4471-90b2-7d7f26649049)

This requires the following frontend changes:
* The ability to filter which options are selectable in the district dropdown based on the kind of user
* The ability to change which districts count as "ALL" based on the kind of user
* The ability to determine the kind of user based on the user_metadata, similar to how we determine the user's state_code. This should be accomplished by checking for two new fields in the metadata:
- If there is a `region` field in the user metadata, we should look at a static, state-specific mapping from region to districts (with MO's mapping defined in the parent epic) and then limit what's in the dropdown to just those districts and make sure that the ALL option only includes those districts
- If there is a `district` field in the user metadata, we should limit what's in the dropdown to just that district and make sure that's what their data is filtered to at all times

**Describe alternatives you've considered**
UI alternate
- We could update the district UI to remove the dropdown for district supervisors and replace it with static text indicating the district. This is a minor UX improvement (prevents a potential dropdown click because it more clearly indicates that they cannot change districts) but does not appear to justify the additional design and FE work. Open to discussion.

**Additional context**
Full context in [PRD](https://docs.google.com/document/d/1bxSg8JgQHFFZZDSjBUKM-fOtU-8r3FVieQD5J81crkA/edit#). Feel free to drop any detail comments directly in the doc for easier discussion.

This is a child of the parent epic #430.

**Comment by DmitryJakubovsky** [comment]
Hi @jessex! Can you add me to contributors for a few minutes for pushing the branch?

**Comment by jessex** [comment]
I'm a bit confused, @DmitryJakubovsky. I have not changed your permissions and you have been pushing branches successfully since you started on the project. Are you seeing an error while trying to push a branch to the repo?

**Comment by DmitryJakubovsky** [comment]
Oh, sorry! I think it was my mistake. Now everything is all right!
