### ISSUE TITLE
[Core] Export does not download a file on some ND dashboard charts

### ISSUE THREAD

**Issue by kbinney** [Recidiviz/pulse-dashboard#446]
**Describe the bug**
When export chart or data is selected from the export selector, nothing happens. No image or data downloads. 

**To Reproduce**
1. Go to the "Community goals" page of the ND dashboard. 
2. Click on Export -> Export Image from any chart

**Expected behavior**
We expect the image of the chart or data in the chart to download

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: MacOS Mojave
 - Browser [e.g. chrome, edge]: Chrome
 - Version [e.g. 22]: 84.0.4147.125

**Additional context**
Interacting with the Explore bar seems to make export possible. I found that when I loaded the dashboard, navigated to Community-> explore and then tried to download the revocation counts chart, nothing happened. If then I changed time time  period to something other than 3 years then back to 1 year, I could download the chart.

Switching a chart to map mode also seems to "unlock" export. On first load, nothing will export on community goals until I switch to map mode for a given chart. Then I can export from the map and the graph when I return to it, but only for that chart. 

Of note, a few charts do not have this problem, though most do.

On community explore, the below charts don't export until switching to map mode or using explore bar:

- Revocation admissions by month
- Prison admissions due to revocation
- Admissions by type
- revocation admissions by race
- successful completion of supervision
- LSI-R score changes

The below charts' export work immediately: 

- Revocation Admissions by Officer
- Revocation admissions by supervision type 
- revocation admissions by violation type
- case terminations by termination type
- case terminations by officer

On first load, nothing will export from the facility goals or explore page. After making a selection on the explore bar, export works for all charts on Facility Explore. Switching from graph to map mode for a given chart also enables export. 

On first load of the Programming page the below charts don't allow export:

- FTR Referrals by Month
- FTR referrals by LSI-R
- FTR referrals by race
- FTR referrals by gender
- FTR referrals by age

The below work on the first try:

- FTR referrals by participation status
- Map mode for Ftr referrals by month

**Comment by jessex** [comment]
I've figured out why this is happening, should be a straightforward fix. Will work on it today!
