### ISSUE TITLE
Add Intercom support for Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#452]
**Is your feature request related to a problem? Please describe.**
Before merging, we should ensure that @chrispmlee gets a chance to clone the branch and test locally.

We are trying to set up a universal doc center and support channel for Recidiviz products via Intercom. This will enable users to have a unified portal to contact us with questions / feedback and access Recidiviz product documentation. Lantern is the first test product for the integration.

**Describe the solution you'd like**

Here are directions from the Intercom website to get started with the code necessary. The authentication should not be needed in order to see the instructions (Please let @chrispmlee know otherwise).
https://app.intercom.com/invites/6318f2cd-dcf0-478e-a074-65371ae5af53

We are interested in capturing the current State_ID (i.e. whether it's North Dakota, Washington, Idaho, etc.) so that we can appropriately show user's the correct documentation. This should be included as a custom attribute.

The portal should look something like this when active:
![image](https://user-images.githubusercontent.com/4443744/93273629-2c99e300-f76d-11ea-8301-73626b26b697.png)

**Describe alternatives you've considered**
N/A

**Additional context**
@chrispmlee  would like to test Intercom before deploying 👍

**Comment by ageiduschek** [comment]
@chrispmlee to update this when there's an update from Intercom

**Comment by chrispmlee** [comment]
@jessex updated ticket

**Comment by jessex** [comment]
@chrispmlee it looks like your link to the documentation _does_ require authentication. We need that link to be publicly accessible.

**Comment by jessex** [comment]
Pinging @chrispmlee again. Can you copy and paste some documentation that doesn't contain sensitive information into the ticket? 

Also, can you send an Intercom invite to jen@recidiviz.org? I'm not sure who will end up implementing this at this point.

**Comment by jovergaag** [comment]
I have confirmed with @chrispmlee that the widget is only to be available on the MO and PA dashboards. I will coordinate with Chris to get him set up for some testing before we merge this. [#492](https://github.com/Recidiviz/pulse-dashboard/pull/492)

**Comment by ageiduschek** [comment]
Still need to figure out how to cycle the app id.

**Comment by chrispmlee** [comment]
Working w/ Intercom now. They currently do not permit a new app_id for a workspace. May have to uproot and start over with a new intercom workspace, but do not know what that will entail yet. Waiting on their response.

**Comment by ageiduschek** [comment]
Functionality fixed, needs some styling updates.
