### ISSUE TITLE
Create new "Custodial Authority" dropdown for PA Admissions Plot

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#453]
**Is your feature request related to a problem? Please describe.**
PRD section: https://docs.google.com/document/d/1ndwZw8PSAIJfLQkuUZmWEKeeqVH6S2PxaGeGXRsuKds/edit#heading=h.cdi9de1qo0x9

Unlike in other states, PA does not have the concept of a "Supervision Type" because they do not have discretion over probationers since they are determined by the court.

In addition, there are multiple custodial authorities that have discretion over individuals admitted to PA DOC facilities. We would like to add a "Custodial Authority" dropdown to enable functionality for PA to look at revocation trends based on the actual authoritative body that is deciding to revoke. It also solves for PA's desire to separate special probation cases out from other case types, since "we don’t have a lot of discretion over because they’re determined by the court."

**Describe the solution you'd like**
Add a dropdown at the far right of the top filter bar of the Lantern dashboard for "Custodial Authority." It should include the following categories:
- All (default)
- Parole board
- Courts
- DOC
- Other state
 

**Describe alternatives you've considered**
Initially, "Special Probation" was a scoped as a case type, but doing so complicates the methodology because right now, we only categorize each person as having one case type by ranking the case types and picking the most serious one that each person falls under. It doesn't make sense to rank special probation as being more or less serious than these other categories - it's merely an implementation detail regarding who (courts vs parole board) has final say over this person.

Alternate options:
a) rank it as most serious which means we will hide a bunch of sex offense / domestic violence cases,
b) rank it as least serious, which will make it look like only a tiny fraction of the people are on special probation,
c) rank it somewhere in the middle which will probably create the most confusing results,
d) do not show special probation as a category at all or

Scope:
d) - least amount of work - no additional calculate and minimal front end changes required
a) b) and c) - all same amount of work. Involves some more calculate and BQ view changes and same front end lift as d)

**Additional context**
Add any other context about the feature request here.

**Comment by ageiduschek** [comment]
Front end ready, waiting on optimization PR to land. Backend work still needs to happen.
