### ISSUE TITLE
[PA] Add "Custodial Authority" dropdown to Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#454]
**Is your feature request related to a problem? Please describe.**
PRD section: https://docs.google.com/document/d/1ndwZw8PSAIJfLQkuUZmWEKeeqVH6S2PxaGeGXRsuKds/edit#heading=h.cdi9de1qo0x9

Unlike in other states, PA does not have the concept of a "Supervision Type" because they do not have discretion over probationers since they are determined by the court.

In addition, there are multiple custodial authorities that have discretion over individuals admitted to PA DOC facilities. We would like to add a "Custodial Authority" dropdown to enable functionality for PA to look at revocation trends based on the actual authoritative body that is deciding to revoke. It also solves for PA's desire to separate special probation cases out from other case types, since "we don’t have a lot of discretion over because they’re determined by the court."

**Describe the solution you'd like**
We want to add a new "Custodial Authority" dropdown to the Admissions Plot (Lantern) view for Pennsylvania. 

This new filter will be on the far right (further right from the Admission Type filter) in the same style as the existing dropdowns. The following are options for the filter, with "All" being the default.

- All
- Parole board
- Courts
- DOC
- Other state

Describe alternatives you've considered
See this [discussion](https://docs.google.com/document/d/1ndwZw8PSAIJfLQkuUZmWEKeeqVH6S2PxaGeGXRsuKds/edit?disco=AAAAKH6hQAE).

Additional context
This is a child of the parent [epic](https://app.zenhub.com/workspaces/-lantern--5f2cdf04d4d9670013da86ed/issues/recidiviz/pulse-dashboard/453).

**Comment by ageiduschek** [comment]
This has been removed from the scope of the PA beta.
