### ISSUE TITLE
Time Period dropdown label is missing a space

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#455]
**Describe the bug**
The Time Period dropdown label on the Lantern dashboard is missing a space.

**To Reproduce**
1. Visit dashboard.recidiviz.org and navigate to the MO view (or view in staging)
2. See the time period filter label as "TimePeriod"

**Expected behavior**
"TimePeriod" should be "Time Period"

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/9ab03612-aa80-488d-ac46-122a398912ab)

**Additional context**
N/A

**Comment by jjdressel11** [comment]
Fixed already in https://github.com/Recidiviz/pulse-dashboard/pull/442
