### ISSUE TITLE
Update methodology for PA beta dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#467]
**What needs to be done? Why does it need to be done?**
PA-specific changes to the Lantern methodology need to be reflected in the PA dashboard before beta launch.

Copy doc: WIP, https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit?usp=sharing

**Additional context**
N/A

**Comment by ageiduschek** [comment]
@sychang to create new doc this week and start updates this week, some methodology pending violations work next week

**Comment by sychang** [comment]
Created a skeleton copy doc for PA: https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit?usp=sharing

TODOs:

- [ ] Serena: Update with PA-specific categories and info where relevant
- [ ] Serena: Pull in methodology from exits docs
- [ ] [next week] Tag Julia for review

**Comment by sychang** [comment]
Done and reviewed by Julia, Anna, and CSG: https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit#
