### ISSUE TITLE
Front-end for Agent chart

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#490]
**What needs to be done? Why does it need to be done?**
We would like DOC leaders to be able to easily identify anomalies and standout agents to identify and understand anomaly agent behavior and properly allocate resources. The agency can work with individual districts and/or agents to address anomalies or set new agency policy to correct imbalances.

This will be a new middle chart in the Lantern dash:
![image](https://user-images.githubusercontent.com/5872651/97757646-63784e00-1aba-11eb-9820-ecf78374eea2.png)

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang Can you verify where you want this to be? Where in the lineup of District, Risk Level, etc.

Also, we are only enabling the 'Admission Count' chart for now so do not add the standing population and rate of exists charts?

**Comment by sychang** [comment]
This should be below district and above risk level.

We should be able to do admission count and admission rate of standing population, similar to how the district chart looks in prod right now. No rate of exits yet.

**Comment by Wmaileq** [comment]
@jovergaag started here, but it depends on #572

**Comment by jovergaag** [comment]
@Wmaileq I am working on the fixture data right now...hopefully it will be merged for you before your next workday starts!

**Comment by jovergaag** [comment]
@sychang I believe I asked this already but just want to confirm again - enable this for both MO and PA? Also - this should be called 'Admissions by officer' for MO?

**Comment by jovergaag** [comment]
@sychang Do we want this filterable by district? The district is in the x-axis label so confirming if we want to filter by district or not.

Also - once we start to use district names instead of IDs, will we use the name or the ID in these labels? If using names, these labels may become quite long...

**Comment by jovergaag** [comment]
I just spoke with @sychang. 
* Confirmed that this chart is for both PA and MO and to adjust titles accordingly. 
* Confirmed we do want to filter by district.
* Confirmed that we want to truncate the officer ID and only display officer name in the data label.
