### ISSUE TITLE
PA Lantern dashboard copy changes

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#495]
**What needs to be done? Why does it need to be done?**
All mentions of "Officer" should be updated to "Agent"

All mentions of "Gender" should be updated to "Sex"

This applies to PA only. Each state moving forward will have some state-specific copy tweaks like this.

**Additional context**
This change should be updated prior to the beta.

**Comment by jovergaag** [comment]
@sychang Is this only for PA or for both MO and PA? There are also mentions of 'Officer' on the ND dashboard, I assume we leave those?

**Comment by sychang** [comment]
Chatted offline, for PA only!

**Comment by sychang** [comment]
One additional copy change that was identified: On the bubble chart x-axis, they copy that currently says "# of violation reports and notices of citation" should be changed to "# of violation reports" for PA only because PA does not use notices of citation.

**Comment by sychang** [comment]
Additional copy changes from dashboard comb-through for PA only: https://docs.google.com/document/d/1o1mJD0Cbb8B9M-Dt10uWkbPbhzbnSNN3XO9_gQ4bEmQ/edit#bookmark=id.yqeyg2enys5w
