### ISSUE TITLE
Ensure consistent visualization card height

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/pulse-dashboard#50]
When we have rows with multiple cards per row, the card heights can be different heights when the content inside (for example, header text) is of different lengths. Ensure height consistency in a way that is dynamic and responsive.

**Comment by jessex** [comment]
After the attempt in #308 and conferring with product, we decided to keep this as is. There will be a larger redesign coming not too long from now that will render this irrelevant, anyway.
