### ISSUE TITLE
[Refactor] Add top level component container classnames

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#508]
**What needs to be done? Why does it need to be done?**
Add class names to top level component containers. This makes it much easier to navigate the DOM and track down bugs.

I suggest that we follow the [BEM naming convention](http://getbem.com/naming/). This makes it immediately apparent when looking at an html element what you are looking at, and keep stylesheets very readable. 

Since at this point I think we should move forward with top level class names, the top level `RevocationMatrix` container would be `.RevocationMatrix`. If we were to build this out and add classnames to the children (not necessary at this point), we could use `.RevocationMatrix__cell` or `.RevocationMatrix__row--header`

**Additional context**
Add any other context about the task here.

**Comment by Wmaileq** [comment]
Will we continue to place styles in the assets/styles folder or should they be near/on the same level as the component?
Is this task includes refactor of styles or should I just put class names as the first step of styles refactor?

**Comment by jovergaag** [comment]
Hi @Wmaileq! Great question. For now, let's go ahead and leave them in the assets directory where they are now. I'm thinking that this will be our first step in a larger styles refactor, just to get some classnames on the nodes to make things easier moving forward in the short term. 

I've been talking with the rest of the team and we are discussing ideas around how to standardize our frontend developer experience across the multiple apps. One thing that we may end up choosing to do is to use React Styled components for all apps. Once we decide that the styled components are the direction we want to go, then we will undertake a larger styles refactor. But for now, let's just get some classnames on things as a first step.

**Comment by Wmaileq** [comment]
@jovergaag Ok, thanks!
Styled components is the great choice!
