### ISSUE TITLE
[Design] How to avoid synchronization requirements between calculation and frontend changes

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#509]
**What needs to be done? Why does it need to be done?**
Typically, end-to-end feature development has been able to avoid requiring synchronized deploys between the data platform and this app. However, on occasion, we have made calculation changes, e.g. adding new dimensions to existing calculations, in such a way as to require that the Dashboard be changed to consider the new data points/fields and have that change deployed prior to the calculation change, to avoid regressions. Sometimes, such as in #498, we have failed and caused production issues.

We should draft a proposal for how to either a) avoid these situations require synchronization entirely, or b) if impossible, creating guardrails that ensure we don't accidentally misstep and cause production-facing issues. This may include testing enhancements, new standards around calculation changes, code changes in how the app handles/filters data points, etc.

**Additional context**
This should be closed when there is a design doc with a proposal that is approved by the Lantern team and any other relevant stakeholders.

**Comment by jovergaag** [comment]
I propose that we close this issue. There is not a design doc, but protections have been put in place that now protect the FE from dimension value changes, and the Lantern team has worked through a process to make changes like these.

Just this morning, the staging deploy contained a new dimension value. The dimension value validations in the API caught the new value, and stopped the cache from being refreshed. It raised an error to Sentry with detailed information about why the refresh cron job failed. The cache remained in tact with good data, and thus protected the FE from an error.

I feel that these validations are sufficient! Thoughts on closing @jessex ?

**Comment by jessex** [comment]
That's fantastic, @jovergaag! That's exactly the kind of setup I was hoping for, ultimately. I think there could be further improvements but I think the spirit of this is accomplished and we can close it.

I also think we need to bootstrap some architectural documentation on how this app works, particularly how we handle data from end-to-end, but that's a separate matter.
