### ISSUE TITLE
Update font-weight for "Using this Chart" instructions

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#511]
**What needs to be done? Why does it need to be done?**
The font-weight for the "Using this chart" section in the Revocations Matrix is 300, which is a bit hard to read. Let's update it to 400. 

**Additional context**
It looks like there's an override in the CSS to make the font-weight 300. Removing it would probably just fix this issue.

![font-weight.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/f1c11797-f64e-4f0d-a84d-c9743b312d48)

**Comment by sychang** [comment]
Here are the additional design tweaks from the comb-through today. Most are applicable to MO and PA. P2 means it's not strictly launch blocking but nice-to-have. https://docs.google.com/document/d/1o1mJD0Cbb8B9M-Dt10uWkbPbhzbnSNN3XO9_gQ4bEmQ/edit#bookmark=id.fsirc8endsrt
