### ISSUE TITLE
Order violations in violation record column by severity

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#520]
**What needs to be done? Why does it need to be done?**
The ordering of the violation record column of the individual caseload table in the Lantern dashboard should be ordered from most- to least-severe. This update should be made for all Lantern states (currently MO and PA). Currently, all violations involving law citations are being sorted incorrectly by the frontend.

For example, one entry is "2 med_tech, 1 low_tech, 1 absc" but the correct ordering would be "2 med_tech, 1 absc, 1 low_tech"

The frontend currently uses the following list to order the violations in a way that is not state-specific nor comprehensive (not all MO violation types are represented). 
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/7f1c16df-0263-4e2a-a41c-628b1f58b94a)

**Additional context**
This is not strictly launch blocking for the PA beta launch. Assigning to @jjdressel11 to add more detail and then to reassign to frontend.

**Comment by jjdressel11** [comment]
The violations in the `violation_report` column that are sent to the FE are ordered by severity. This issue actually has two parts:
1. Making sure the violations in each person's Violation Record column are ordered correctly by severity (this issue).
2. Implementing a correct sort function to allow sorting by the severity of the violation record. This part may require state-specific understandings of violation severity orders. (Filed https://github.com/Recidiviz/pulse-dashboard/issues/524)
