### ISSUE TITLE
PA dashboard copy and UI QA

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#523]
**What needs to be done? Why does it need to be done?**
Items emerging from QA of the staging dashboard after copy changes:
- On hover, "Low risk" on the sex and race risk level charts has a double space (but medium and high risk are WAI)
- In bubble chart "Additional info", the title for “Number of violation reports filed” rather than “Number of violation reports and notices of citation filed”. In general, all mentions of "notices of citation" should be removed from the PA dash (but kept in the MO dash)
- In district chart "Additional info", the title of the count chart should change from "What the count chart shows" to "What the “Admission count” chart shows"
- In district chart "Additional info", the title of the rate chart should change from "What the percentage chart shows" to "What the “Admission rate of standing population” chart shows"
- In violation chart "Additional info", The sentence "For example, if a single violation report lists both an employment violation and a reporting violation, both are counted." should be changed to "For example, if a single violation report lists both an absconsion violation and an electronic monitoring violation, both are counted." (updated to represent PA-specific violations types)
- In QAing this, realized a bug in the MO methodology for the violation chart "Additional info", "20/100=10%." should say "20/100=20%" to now match the PA methodology.
- In admitted individuals "Additional Info", "Officer" --> "Agent"
- In admitted individuals "Additional Info", Risk level description should change from "Risk level is defined based only on the Community Supervision Screening Tool and/or the Community Supervision Tool (if relevant) and no other assessment (i.e., Prison Intake Tool). Those without Community Supervision Screening Tool/Community Supervision Tool scores are counted in the Unassessed category. " to "Risk level is defined based only on the LSI-R tool and no other assessment. Those without LSI-R scores are counted in the Unassessed category. LSI-R scores above 54 are not counted."
- In admitted individuals "Additional Info", "Last Officer Recommendation (Including Supplemental)" should change to "Last Recommendation." The text in that paragraph should say: "Last recommendation: The recommendation listed on the last violation report before the person was admitted."
- In admitted individuals "Additional Info", Violation record text should change from "A summary of all reported violations in violation reports filed within one year prior to the last reported violation before the person was admitted." to "A summary of the most severe reported violation on each violation report filed within one year prior to the last reported violation before the person was admitted."

**Additional context**
N/A

**Comment by jovergaag** [comment]
Wow, not sure I missed so many of those! Should be better now.
