### ISSUE TITLE
Revocations matrix UI polish from product launch review

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#532]
**What needs to be done? Why does it need to be done?**
During @cawarren 's launch review of the PA revocations matrix , he came across a few non-launch-blocking UI issues in this doc: https://docs.google.com/document/d/1xO_8rO4Jweh7fOPbWioDmk_51n13Dw4jIkwmCWiEjxw/edit

**Additional context**
This is not launch blocking for the PA beta. Additionally, some of these are relevant to only the MO dashboard, whereas others are relevant for both.

**Comment by jovergaag** [comment]
I ended up creating separate issues for a few of these. There are still two issues that haven't been captured in separate issues and assigned to Vlad - the ones under the 'Areas for further consideration'. We will need more detail there. I'll change this to be an epic encompassing all of the smaller issues.

**Comment by jovergaag** [comment]
I don't think I did the Epic transition correctly... But this points to the other two issue now.

**Comment by jovergaag** [comment]
Clearly my epic is not configured correctly. I'll figure it out next time. The two subtasks have been merged...closing this.
