### ISSUE TITLE
Change base branch from 'master' to 'main'

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#537]
**What needs to be done? Why does it need to be done?**
Ensure that the following continue to work:
deploys
Travis
Firebase(this shouldn't require any config change but should verify)

**Additional context**
Add any other context about the task here.

**Comment by jessex** [comment]
Want to make sure you're aware of the investigations we did on the data platform for this: https://github.com/Recidiviz/recidiviz-data/issues/3651

tl;dr: There was enough identified complexity that we opted to wait a bit in anticipation of Github adding more automation for the switch to main.
