### ISSUE TITLE
[Tech-debt] ExportMenu should accept only datasets and labels fields, rather than the whole chart object

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#540]
**What needs to be done? Why does it need to be done?**
ExportMenu component should not accept chart node, it should accept only datasets and labels fields.

Also, please rename `TenantExportMenu` to `ChartCardExportMenu`. 

**Additional context**
Add any other context about the task here.

**Comment by Wmaileq** [comment]
Depends on #538
