### ISSUE TITLE
Demo Mode fixture data is missing supervision_level=ALL rows

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#546]
**Describe the bug**
Demo mode only - ND looks fine, but the Lantern States dashboard is not showing any data other than in the `CaseTable` unless the supervision level filter is applied. At one point our data changed and we started sending `supervision_level = ALL` rows through the API so we changed the filters. The fixture data did not follow. 

Update the fixture data so that it matches the apiData, including `supervision_level='ALL'` rows for all necessary fixtures.

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by Wmaileq** [comment]
@jessex As we are using optimized file formats now, i think `add_dimensions_to_fixtures.py` will not work. Can i just download new fixture data from elsewhere or should i write script to add new fields in optimized files?

**Comment by jessex** [comment]
Yes we're using the optimized format now and unfortunately that script will no longer work. Our tooling has not caught up on this yet so we may need @jovergaag to take care of this one, actually.

**Comment by Wmaileq** [comment]
> The way I've updated the new optimized metric files the couple of times I have done so in recent weeks was by transforming the optimized files back into the non-optimized files, using those scripts I have, and then transforming back into the optimized format. It's a cumbersome process ripe for improvement.

@jessex Thought of it too. But where can i find script for transforming non-optimized into optimized?

**Comment by jovergaag** [comment]
@jessex @Wmaileq I can take this one over. @jessex I'll get in touch with you directly for the non-optimized scripts to get this fix in. As I've been poking around the backend repo I've seen a few of the metric views/files that might be able to be combined (maybe?) which would cut back significantly on the data sent to the frontend. In that case we may not need the optimized format. Discussions to be had about that.

In the meantime, I can just put up a quick fix for the non-optimized fixtures.
