### ISSUE TITLE
IE11 - Export data and image formatting/styling issues

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#550]
**Describe the bug**
From IE11, there are 2 issues when exporting data/images:
1. When the revocation matrix image is downloaded, the matrix background color is incorrect. Ensure that the downloaded image background color is white such that the downloaded image matches the rendered matrix.
2. When downloading either data or image, the date string in the 'methodology.txt' file has extra characters in it.

**To Reproduce**
1. Go to any Lantern page
2. Click on 'Export Image' from the export menu
3. Open the downloaded image and notice that it doesn't look quite right.

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

**Comment by jovergaag** [comment]
@Wmaileq This is higher priority than your other tech-debt issues. Thank you!

**Comment by Wmaileq** [comment]
Working on it right now with IE11

**Comment by jovergaag** [comment]
@Wmaileq What time zone are you in? Just curious what your working hours are and how they overlap with us here in CA.

**Comment by jessex** [comment]
I'm pretty sure Vlad is in GMT+3 (is that right, Vlad?), which puts him at 10 hours ahead of Pacific time. Generally speaking, you should anticipate that on most days, feedback you provide on PRs won't be seen until the next morning that Vlad is back online.

**Comment by Wmaileq** [comment]
@jovergaag @jessex yes, GMT+3, but as i have no Windows PC in office i usually transfer IE11 work to home, where i have one :)
