### ISSUE TITLE
UI treatment to indicate data for months that are in progress

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/pulse-dashboard#56]
Since we are showing data for current months, the values for that month will seem low every month until the very end of the month. We need a visual treatment to indicate that a month is still in progress and that the values on the chart aren't what the end of the month will look like.
Some ideas:
- an "In progress" label under current month labels
- an "as of: DATE" to indicate the last time the data was refreshed
- greyed out or projection for where we think the month values will end up given the current values and rates of change

**Comment by jessex** [comment]
We have this now, via a greyed out portion between the most recent month and the current month. It has not been consistently applied across all time-series charts, but that's a matter for specific use cases to be filed. Closing this.
