### ISSUE TITLE
[Tech-debt] Do not fetch revocation_matrix_cells twice

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#564]
**What needs to be done? Why does it need to be done?**
We are currently fetching `revocation_matrix_cells` twice, once for the matrix chart and once for the district filters. Instead, hold this data in a context and allow both components to access it.

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@Wmaileq This is also higher priority than the agent chart and export menu

**Comment by ageiduschek** [comment]
Finished, will land this week
