### ISSUE TITLE
Sum rows where reported_violations >= 8 in revocations charts views

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#581]
The revocations matrix only shows reported violations up to 8, which means the values are summed and displayed in the '8+' column of the matrix. Clicking on one of the matrix cells in the '8+' column filters all of the data in the revocations charts below.

The revocations charts views have rows with `reported_violations` larger than 8, so the summing and filtering on those values is being done manually which is tedious and bug prone. These rows are also significantly increasing the size of the metric files.

For all of the metrics files for the revocations charts, sum all values where reported_violations >= 8 and include in a single row.

**Comment by jjdressel11** [comment]
This is a backend bug. Closing this in favor of https://github.com/Recidiviz/recidiviz-data/issues/4648
