### ISSUE TITLE
Add nested sub offices to district dropdown

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#593]
**What needs to be done? Why does it need to be done?**
PA would like to add sub-offices to their district dropdown. Hierarchically, sub offices are the equivalent of a "district" in MO, whereas a "district" in PA is equivalent to a "region" in MO. Adding the sub offices for PA would get us to match the geographic granularity that we are getting in MO.

UX: The sub offices should be nested under each district name (changing district numbers to names is in another ticket) similar to the UX for two levels of hierarchy of the admission type filter. The behavior is as follows:
- If a district is checked, all sub offices below that district should be checked by default (but can be unchecked). If a district is unchecked, all sub offices in that district should be unchecked.
- At least one filter must be selected at all times
- The default is "All districts"

Data: The districts and sub office options should be as follows:

    1. Philadelphia
        1. Countywide
        2. Northeast
        3. Northwest
        4. Specialized
        5. West
    2. Pittsburgh
        1. Greensburg
        2. North Shore
        3. Pittsburgh DO
    3. Harrisburg
        1. Harrisburg DO
        2. Lancaster
        3. York
    4. Scranton
        1. Scranton DO
    5. Williamsport
        1. Williamsport DO
    6. Erie
        1. Erie DO
    7. Allentown
        1. Allentown DO
        2. Reading
        3. Wernersville
    8. Mercer
        1. Butler
        2. Franklin
        3. Mercer DO
    9. Altoona
        1. Altoona DO
    10. Chester
        1. Chester DO
        2. Norristown
    11. CO

**Additional context**
The only launch-blocking task here is adding nested sub offices for PA. Two steps of additional work could be done to improve the experience overall (but can be forked off to separate tasks or done later):

First, standardize the way we represent regional hierarchies across all states to future-proof ourselves. All states we have encountered so far have at least 2 levels of regional hierarchy (e.g., "region" / "district" in MO and "district" / "sub office" in PA).

Second, this nesting UX can be propagated to MO as well, where regions in MO may be added and nested according to this grouping (more info in this [map](https://doc.mo.gov/media/pdf/pp-regions-printable-map))

- Western Region: 1, 4, 4C, WN, 4W, 19, 24
- North Central Region: 2, 5, 6, 20, 27, 29, 32, XCRC, MCC, MTC, WMCC, WRDCC
- Southwest Region: 9, 10, 10N, 10R, 13, 21, 30, 33, 42, 43, 44, ATC, CTCC, FRDC, JCCC, OCC, SCCC, OCC
- Northeast Region: 3, 11, 16, 17, 18, 26, 38, BCC, CCC, NECC, WERDCC
- Eastern Region: 7B, 7C, 7S, 8C, 8E, 8N, 8S, EP, ERV, TCSTL
- Southeast Region: 12, 14, 15, 22, 23, 25, 31, 36, 37, ERDCC, FCC, MECC, PCC, SECC
-

**Comment by ageiduschek** [comment]
!!
