### ISSUE TITLE
[fullstory] Chart not loading error on IE11

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#597]
**What needs to be done? Why does it need to be done?**
From a fullstory log, an IE11 user in PA was seeing the full Lantern dash with no issues, but then selected "General" Case type and the charts on the page failed to load. They refreshed the page but still got the same issue. They were using IE11.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/97a4969b-db42-40c7-83d7-e0e584c579f6)

Note, the same user returned on a different browser and got the charts to load successfully. No other sessions that I am aware of had the same chart loading issue.

**Additional context**
I can go back and grab more info about the session if needed.

**Comment by jovergaag** [comment]
I'm quite sure this is related to the IE11 memory leak. I have been watching the memory in IE11 and each time a filter is used, the heap memory increases. Even with a refresh (or a hard refresh) the memory does not clear out so when the browser tries to fetch the data again it has no memory left. 

This is after having been using the app for about 12 minutes, you can see the memory fluttering around, then I refreshed and you can see the slight in crease in memory, then the app renders errors for each chart. Notice the memory is flat lined at 1.8GB.
![Screen Shot 2020-11-05 at 2.19.14 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/ae59e1d8-98d7-4291-8af6-3a21edd2ea03)

The error in the console is not `Out of Memory` as I would expect, but it is `TypeError: Unable to get property revocations_distribution_by_district of undefined or null reference`

**Comment by jovergaag** [comment]
closed with #728!!!

@sychang @ageiduschek @daschi The issue that started it all...is finally closed!

**Comment by ageiduschek** [comment]
YESSSS CONGRATS!!

**Comment by sychang** [comment]
OMG HOLLAAAA so incredible <3
