### ISSUE TITLE
Remove all references to SEX_OFFENDER

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#610]
**What needs to be done? Why does it need to be done?**
This is cleanup following #609. Once the backend value change has been deployed, remove all references to SEX_OFFENSE in the code base, including fixtures.

We basically want to revert what was done in #611 and use SEX_OFFENSE instead of SEX_OFFENDER in charge_category field.

**Additional context**
Add any other context about the task here.

**Comment by ageiduschek** [comment]
This data will be live in prod later today

**Comment by Wmaileq** [comment]
> This is cleanup following #609. Once the backend value change has been deployed, remove all references to SEX_OFFENSE in the code base, including fixtures.

As we are migrating from SEX_OFFENDER to SEX_OFFENCE, we need to remove all references to SEX_OFFENDER, and only SEX_OFFENCE should left.
