### ISSUE TITLE
Swap the axis of the data export for specific charts

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#616]
**Is your feature request related to a problem? Please describe.**
Data exports for the following charts are difficult to read due to the single row/multiple column format. Let's swap the axis of the export so that it is more rows than columns.

Apply this change for the following exports:
-revocationsByDistrict
-revocationsOverTime
-revocationsByViolation
-revocationsByOfficer
-revocationsByGender
-revocationsByRace
-revocationsByRiskLevel

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by Wmaileq** [comment]
I am in here, refactoring `downloads` functions too.
