### ISSUE TITLE
UI polish for all charts on Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#625]
**What needs to be done? Why does it need to be done?**
General UI polish for the Lantern dashboard involves applying the following updates, which are detailed in [this Figma file](https://www.figma.com/file/UTbkeYLUl6hD9EbLHEGJQk/MO-dashboard?node-id=57%3A97):
- Remove the x-axis label
- Remove the y-axis line and vertical gridlines
- Left-align the y-axis label to the the chart title
- Move the legend to the top right of the chart and update styling
- Adjust the spacing, padding, and font style, and font sizes

These updates will be applied to the following charts, for both the Missouri and Pennsylvania dashboards:
- Number of admissions per month
- Admissions by district
- Admissions by risk level
- Relative frequency of violation types
- Admissions by gender and risk level 
- Admissions by race and risk level

For example, this is what the new risk level chart should look like
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/02acc976-22e4-4cd3-b649-acd512286e27)

**Comment by sychang** [comment]
@soniachokshi do we want this applied to the top admissions by month chart as well?

**Comment by jovergaag** [comment]
Due to other higher priority work - I let the PR that is currently open for this issue get stale. That PR needs to be rebased and we can take another look at it!

**Comment by sychang** [comment]
Going to close this issue for now - will revisit this when we pull more unified torch components in with Lantern
