### ISSUE TITLE
Change all Lantern dashboard fonts to Libre Franklin

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#626]
**What needs to be done? Why does it need to be done?**
Change all fonts on the Lantern dashboard from Roboto to Libre Franklin. This is a first step at unifying designs cross Recidiviz products.

Here's an example of how the fonts should look.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/32862a9f-a278-4112-8217-b28fabca607f)

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang I just want to confirm that we are only changing the font on the Lantern layout - and leaving the ND dashboard with Roboto? That is how Vlad implemented it, just want to confirm that is correct.

**Comment by sychang** [comment]
Yes, we can leave the ND dashboard as is. Thanks!
