### ISSUE TITLE
Remove statistical significance indicator from agent/officer chart

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#627]
**What needs to be done? Why does it need to be done?**
We originally added the "not statistically significant" indicator on charts to warn users not to make generalizations about the data if the denominator of a rate calculation was less than 100. With the officer/agent chart, the denominator is an agent's supervision caseload, which is often less than 100. Because the chart is showing per-agent/officer metrics, there is no risk of users making generalizations, so we will remove the statistical significant warning entirely.

This task involves, for the agent chart in PA and officer chart in MO:
- Removing this warning icon from the chart
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/871bc2d7-23f0-4d08-b166-7285b7ab5970)
- Remove the hatch pattern on bars
- Remove the note from hover state about "Indicates the group is too small to make generalizations"

 ![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/42e071ee-1cce-4cd4-8f40-07ba11a8b327)

The statistically significant indicator should remain on the other charts on the page.

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@Wmaileq Feel free to either branch off of the existing officer chart branch for this, or add commits to it. We are still waiting on the backend before merging this chart.

Another option is to put the chart behind a flag in the other chart, so that we can get that code into master, and just remove the flat when the data is ready.
