### ISSUE TITLE
For Gender & Race charts, move the tooltip so it doesn't cover the bars 

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#636]
**What needs to be done? Why does it need to be done?**
For the Gender and Race charts, the tooltips have a lot of information and support accessibility by disambiguating the different colors in the chart. However, often, the tooltip covers the bars that it is referencing, which makes the chart difficult to read and understand.  See examples below: 

![Screen Shot 2020-11-30 at 10.40.56 AM.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/3ab59738-bc0c-4e40-a7d9-bbba25ce264b)
![Screen Shot 2020-11-30 at 10.39.55 AM.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/0f70280c-a8c8-468d-9cad-54237de491ad)

Let's ensure that the tooltip doesn't cover the bars that it's referencing. The tooltip can be anywhere where there is space near the bars that it is referencing (above or to the side of the bars). 

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Closing because we are changing the design of this chart.
