### ISSUE TITLE
UI Polish for Revocations Matrix

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#637]
**What needs to be done? Why does it need to be done?**
Make the following UI polish tweaks to the Revocations Matrix to make it more aligned and easier to read:
- Update padding and alignment, see [Figma file
](https://www.figma.com/file/UTbkeYLUl6hD9EbLHEGJQk/MO-dashboard?node-id=40%3A999)
- For the “About this Chart” make all of the text aligned on the left, move the bubble and chip to the right side

Before:
![revocations matrix - before.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/0e80464e-16f2-4b9b-972c-0cecc6f92a7e)

After:
![revocations matrix - after.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/6105ca7e-e504-4e89-905e-b872c6a0f0f0)

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@soniachokshi When you say padding and alignment here - do you mean on the labels and on the filter buttons (`Chip`)?
