### ISSUE TITLE
Modify API to reduce memory pressure on client

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#643]
We are currently drowning in data on the client, which is leading to very long load times and occasionally errors on IE11. We need to modify how data is fetched on the client to reduce the amount of data that the browser is holding at any given time, and modify the API to support that.

Design Doc here: https://paper.dropbox.com/doc/Design-Doc-Lantern-API-Modification--BAllSU0oNTgblMVgU167JFdYAg-UygLJo7RkX3Ff4aUmQQIL

**Comment by jessex** [comment]
Is this one all wrapped up, @jovergaag?

**Comment by jovergaag** [comment]
@jessex There is one final issue - imporoved error reporting on the API which is in the to do list for this week's sprint. Then we're all finished!
