### ISSUE TITLE
Question: should we set the GAE backend min instances to 1?

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#65]
At present, the backend of the app is hosted on App Engine with no minimum instance count set. This means that the app scales down to 0 instances at times of low traffic volume (which still sometimes occurs while we are still ramping up usage across states). So the Google Frontend takes in the request and performs a cold start of a GAE instance to serve the traffic. The first global request to the app after such a cold start triggers a proactive fetch-and-cache of metrics from the metric store, which means that first request takes on the order of a few seconds. Subsequent requests for that user and other users are then blazing fast.

If we want to avoid that cold start from ever happening, we'd set min instances to 1 so that the backend server is always up and the calculations are being regularly refreshed in the background. The downside is increased cost, so we should try to estimate that cost increase or give this a limited run to see how it goes.

**Comment by jessex** [comment]
We configured the staging and production backends to have `min_instances = 1` while dealing with some memory issues after rolling out the revocation matrix feature for Lantern states (which has significantly more data requirements than the previous views).

We were interested to see if this would cut down on data load times by ensuring that there would always be a single instance up and running, thus it would always have data cached and no one request would incur a roundtrip to Google Cloud Storage. However, it does not always achieve the desired effect: as documented [here](https://cloud.google.com/appengine/docs/standard/nodejs/configuring-warmup-requests), "_if your app is serving no traffic, the first request to the app will always be a loading request, not a warmup request_." Given usage patterns, the first user early in the morning, for example, may trigger a loading request instead of a warmup request, which seems to "wake up" the one running instance and cause a roundtrip to GCS.

So more investigation is needed to figure out how to completely avoid cold starts.

**Comment by jovergaag** [comment]
@daschi I know you did some research on this recently. Just wanted to bring this issue to your attention if you want to add your findings.

**Comment by daschi** [comment]
In staging we've seen that `min_instances = 1` is working and keeping one instance alive, and we also have the cron jobs that are pinging the app once a day to refresh the redis cache. From what I understand I *think* we are avoiding cold starts because of these two things, but would be interested in chatting with you both about it to check assumptions.

**Comment by jessex** [comment]
So looking at [this graph](https://console.cloud.google.com/appengine/instances?project=recidiviz-dashboard-staging&serviceId=default&versionId=20210127t143743&graph=AE_INSTANCES), it looks like the server is now regularly sitting at 1 _created_ instance but at 0 _active_ instances except when there is some flutter of activity. The graph is not painfully obvious, but from reading the "How Instances are Managed" [GAE doc](https://cloud.google.com/appengine/docs/standard/python3/how-instances-are-managed) and StackOverflow posts [like this](https://stackoverflow.com/questions/56269651/please-explain-app-engine-instances-parameters), I think it means that we usually have 1 instance which is _idle_. Whether the activity that flips an instance from idle to active invokes a cold start I do not know.

_However_, now that the refresh is being triggered by an external cron job and the cache we are refreshing is externalized to Redis, I don't think it matters anymore whether we have 0 or 1 minimum instances, actually. Those crons will run and that cache will persist regardless of the current scale status of GAE. So I think we can close this ticket out now, but it might be worth giving some brief thought as to whether we should undo that `min_instances=1` config just for the sake of simplicity since it seems no longer required.
