### ISSUE TITLE
[API-Fast-Follow] Investigate and apply cache-control header setting that has best performance on IE11 

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#661]
**What needs to be done? Why does it need to be done?**
Investigate and apply cache-control header setting that has best performance on IE11. Investigate both the options in both the request and response headers. It is possible that we will want to add this header for IE11 and not for other browsers.

**Additional context**
Add any other context about the task here.

**Comment by daschi** [comment]
I looked into the web caching on both Chrome and IE11 and I think they're working as expected. After chatting with @jovergaag we decided that given the recent changes to the API and the increased performance on IE11, we don't need to put any more time towards fine tuning the browser caching.
