### ISSUE TITLE
[API] Respond to metric files being updated/added in the bucket

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#662]
**What needs to be done? Why does it need to be done?**
Allow the API to respond to a google cloud function event which fires when a metric file is changed or added to the dashboard metric file bucket. Receiving of this event will initiate the fetching/subsetting logic. 

We should leave the manual trigger in place in case we want to manually refresh the cache at any time.

**Additional context**
Add any other context about the task here.

**Comment by ageiduschek** [comment]
Closing - the cron job that runs a few hours after the metric export is sufficient for now
