### ISSUE TITLE
[MO District Restricted View] Build endpoint for serving small reference table files that are stored in memory

### ISSUE THREAD

**Issue by ageiduschek** [Recidiviz/pulse-dashboard#668]
**What needs to be done? Why does it need to be done?**
This endpoint will be used to quickly load the list of MO district supervisors and the districts (level_1_supervision_locations) they can view data for.

This potentially will be queried from an Auth0 rule or the app frontend itself.

**Additional context**
Anna's investigation doc here: https://paper.dropbox.com/doc/MO-District-Supervisor-Backend-Investigation--BBcadyez1WVzvwwFGstF4mw8Ag-Sy4PPw9jqeQyd3GE9oeAS

**Comment by jovergaag** [comment]
closed by #707
