### ISSUE TITLE
Enable SSO integration with our primary Dashboard app

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#701]
**Is your feature request related to a problem? Please describe.**
Managing a separate set of credentials specific to our Dashboard app comes with some downsides:
- Users have to remember another password and keep it secure
- We have to ensure that departing staff in partner organizations don't keep accounts that they should no longer have access to
- We run into compliance issues in particular jurisdictions

**Describe the solution you'd like**
Add the ability to integrate with major SSO providers in partner organizations.

**Describe alternatives you've considered**
N/A

**Additional context**
More context can be retrieved from @jessex and @cawarren.

This is filed as an epic because there are likely multiple thrusts of effort here:
- Enabling separate sets of login options per tenant/state
- Selecting, enabling, and testing our initial provider(s) to integrate with
- Deploy SSO into production with those providers for each requesting state

Those tickets should be filed once we begin serious work on the initiative.

**Comment by Catacola** [comment]
I'm going to go ahead and close this. We've enabled SSO for three states and have another 4 in the pipeline. We can track this work separately.
