### ISSUE TITLE
Fetch and save the districts for the DistrictFilter in a different store

### ISSUE THREAD

**Issue by daschi** [Recidiviz/pulse-dashboard#704]
**Is your feature request related to a problem? Please describe.**
We are currently fetching and filtering the data for the `DistrictsFilter` inside the `RevocationsOverTimeStore`. This is confusing and we should move the districts out of this store.   

We have a feature coming down the pipe where we will receive a file `supervision_location_ids_to_names.json` which will list all the district numbers and map them to their name to be displayed in the filter. When we implement that we will use that as the list of districts for the filter. Until then, parsing them from the `RevocationsOverTime` metric file is fine, but the logic for getting the districts in the store should live somewhere else.

**Describe the solution you'd like**
We could either fetch and filter the districts data in its own `DistrictsStore`, or we could add it as part of the `FiltersStore`. Since it is a filter, it seems like it would fit with the `FiltersStore`, but we would need to see how that affects the UI interaction given that currently the `FiltersStore` is not fetching any data. 

**Describe alternatives you've considered**
We are already fetching and setting the districts data in one of the revocation chart's data stores, which is not ideal, but works for now. The alternative to using the FiltersStore would be to create a DistrictsStore, but I'm not sure if it really needs its own store since this data is only used to generate the filter options.

**Additional context**
See discussion: https://github.com/Recidiviz/pulse-dashboard/pull/694#discussion_r560511230

**Comment by jovergaag** [comment]
To add a little more detail here, our different Lantern Tenants will utilize the level_1 and level_2 supervision locations differently. Therefore, we will want to store the list of `level_1_supervision_location_external_ids` and `level_2_supervision_location_external_ids` and be able to work with them both individually. 

US_MO is should use the `level_1_supervision_location_external_id` as the display field in the district filter options, as well as the value used when filtering districts, and the labels on the x-axis of the district chart.

As it stands today, US_PA is should use the `level_2_supervision_location_external_id` as the display field in the district filter options, as well as the value used when filtering districts, and the labels on the x-axis of the district chart.

In the issues that will follow this week, US_PA will eventually start using the `level_2_supervision_location_name` as the display field in the district filter options and as the label on the x-axis of the district chart, but the id will be used for filtering. Eventually, the district sub-office feature will be implemented in US_PA in which case both the level_1 and level_2 supervision location names will be used in the district filter, and their corresponding ids for filtering.
