### ISSUE TITLE
Remove case type dropdown from PA Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#711]
**What needs to be done? Why does it need to be done?**
Remove the case type dropdown from the Pennsylvania Lantern dashboard.

If this happens before the calculate change to remove case types from the dashboard views, make sure case type = all 

**Additional context**
Do **not** remove the case type filter on the Missouri Lantern dashboard.

cc @jovergaag in case you want to add more details for this FE task.

**Comment by jovergaag** [comment]
This will be changed in `filterOptions.js`. For PA, the case type filter will be disabled, and `defaultValue = "All"`, similar to the SUPERVISON_TYPE filter!
