### ISSUE TITLE
New chart design for race charts

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#712]
**What needs to be done? Why does it need to be done?**
The is the frontend task to update the design of the race chart on the Lantern dashboard.

More context in the epic. Product requirements are detailed here: https://docs.google.com/document/d/1B_tBAHkQqZWvMdzjL3fmjXU_76D3fx6DUpJFSPMgdLs/edit?ts=5f3e86df#heading=h.564wn9rza708

Mocks: https://www.figma.com/file/KV2EfvaHMwFcWZg7QzF9OQ/Race-%2F-Gender-Charts?node-id=215%3A2

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/2e1b5855-ca6b-49ba-8980-5bd9b488c6da)

User interactions - as specified [here](https://docs.google.com/document/d/1B_tBAHkQqZWvMdzjL3fmjXU_76D3fx6DUpJFSPMgdLs/edit?ts=5f3e86df#heading=h.c29ll7o2tvsa)

* Users should be able to click the different race  options and have the charts update to display that race
* (Like the rest of the dashboard) - The bars for “supervised population” and “revoked population” should abide by the selected top-line filters (time period, district, case type, supervision type) and violation history matrix (most severe violation type, number of violations)
* (Like the existing charts) - when users hover over the graph, the actual counts powering the graph for this demographic should be visible. 
    * Ex. if caucasian is selected, whenever hovering over the graph you should see:
“Revoked population: X 
Supervised population: Y
Overall population: Z”
* (Like existing charts) - bars are shaded if the underlying count is too small to be significant. 

**Additional context**
This should be done for all states, but Missouri should be prioritized, if it makes a difference.

**Comment by jessex** [comment]
Heads up to our Inobright friends, it will probably be helpful / easier to do this one simultaneously to #713.

**Comment by jovergaag** [comment]
@AlexK-ino The fixtures now have the data you need to support this new chart design. The "revocations_matrix_distribution_by_race" and "state_race_ethnicity_population" fixtures are what feeds this chart. It might be helpful to look at the attribute changes that were merged recently in issue #709.

The attributes that will be used for this new chart are:
- "Those who were revoked": `revocation_count` numerator and `revocation_count_all` denominator
- "Supervision population" bar: `supervision_population_count` numerator and `supervision_count_all` denominator
- "Overall population" bar: `population_count` numerator and `total_state_population_count` denominator (both from the "state_race_ethnicity_population")

The "state_race_ethnicity_population" is not currently being served by the API, you will need to add is as a file fetched from the `newRevocations` endpoint.

Let me know if you have any questions!

**Comment by AlexK-ino** [comment]
Hello, @jovergaag!
Thank's for the comments!

Faced this problem:
The library used does not support the ability to use the names of the graph graph above the graph.

I currently see 3 development paths:
1. Make your own custom diagram
2. Use absolute positioning over the canvas
3. Unfortunately, move away from the layout and leave the description to the left of the diagram.

I would like to hear your opinion or suggestions. Thank's

**Comment by jovergaag** [comment]
Hi @AlexK-ino. I talked about this with @sychang and we think going ahead with #3 makes sense for now. 

This is a fairly high priority feature so modifying the design in support of finishing it sooner is ideal. Go ahead and move the labels to the left of the bars, in a way that makes sense. Once you push up the modified chart, I will show it to the designer to get sign off and make any styling tweaks as necessary!

Thanks,
Jen

**Comment by AlexK-ino** [comment]
Hello @jovergaag!

Unfortunately the task took much longer than I expected.

Faced the problem that state_race_ethnicity_population is not being adapted for the data the diagram receives.

I've tried a variety of ways to get it to work, but to no avail. 
(The extreme problem was that the diagram required total_data_points, which were undefined)

I saw that a matrix and metadata is used everywhere, is there any way to translate state_race_ethnicity_population into that format?

Thanks,
Alexander

**Comment by jovergaag** [comment]
@AlexK-ino I think the issue that you're running into is that the `state_race_ethnicity_population.json` file is in '.json' format, but the code you have written is expecting it to be in the '.txt' optimized format with metadata. I went ahead and modified the `BaseDataStore` so that it fetches the population file and parses it such that the data is now useable in `RevocationsByRace`. Take a look at the commit in my branch `jovergaag/request-state-population`. Does that help unblock you? Feel free to cherry-pick that commit into your branch if it is helpful (it probably needs some tests if so)!

If that does not solve your issue, please push up your branch and I will take a look.

Thanks!!

**Comment by AlexK-ino** [comment]
Thanks, Jen, that helped

**Comment by jovergaag** [comment]
@sychang Do we have updated methodology copy to accompany the UI change?

**Comment by jovergaag** [comment]
Also - @sychang  and @soniachokshi What do we want the tooltips to look like? In the implementation that @AlexK-ino has finished so far (shown below), each tooltip shows the count for every bar - which is similar to what we are doing in the existing race chart. However, with the new design it seems a bit off. Should we only show the count for the bar currently under hover?

![Screen Shot 2021-02-12 at 12.46.20 PM.png](https://images.zenhubusercontent.com/5f68f900f5589b314e6a6ec3/ea362bf5-9c88-4daf-bb99-7690b70e355a)

Apologies if I missed the tooltip in the designs!

**Comment by soniachokshi** [comment]
Ah thanks for flagging this! Yes, let's only show the count for the bar currently on hover. So, in the example above, the tooltip would show some version of that second line "Supervision population (612088/4038580)". Obviously, showing the orange color is not critical, so we can remove that depending on whatever's easiest.

We do something similar with our tooltip on the Spotlight Racial Disparities page:
![image](https://user-images.githubusercontent.com/6492875/107828538-494f3c80-6d46-11eb-957c-af1f7771561e.png)

**Comment by sychang** [comment]
Here is the updated methodology for [MO](https://docs.google.com/document/d/1q06zsWlTK3O4sqykPQQ4NQixScQyvjbqsFViH1GXfVQ/edit?ts=602b434c#heading=h.hxnhkd7s4d08) and [PA](https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit#). The race and gender sections are both updated for both states.

A couple of notes that @terinpw noticed in QA - let me know if I should file separate tickets for each of these:
- Summing across the race/ethnicities should add up to 100% but they currently do now - is that working as intended because of staging data? If not, there may be a calculation bug.
- One requested copy change to be more consistent and concise: change "Those who were revoked" to "Admitted Population" for both Missouri and Pennsylvania.
