### ISSUE TITLE
New gender/sex chart on Lantern dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#713]
**What needs to be done? Why does it need to be done?**
The is the frontend task to update the design of the gender (in Missouri) and sex (in Pennsylvania) chart on the Lantern dashboard.

More context in the epic. Product requirements are detailed here: https://docs.google.com/document/d/1B_tBAHkQqZWvMdzjL3fmjXU_76D3fx6DUpJFSPMgdLs/edit?ts=5f3e86df#heading=h.564wn9rza708

Mocks: https://www.figma.com/file/KV2EfvaHMwFcWZg7QzF9OQ/Race-%2F-Gender-Charts?node-id=215%3A2

The design should be the same as for the race charts.

User interactions - as specified [here](https://docs.google.com/document/d/1B_tBAHkQqZWvMdzjL3fmjXU_76D3fx6DUpJFSPMgdLs/edit?ts=5f3e86df#heading=h.c29ll7o2tvsa)

* Users should be able to click the different race  options and have the charts update to display that race
* (Like the rest of the dashboard) - The bars for “supervised population” and “revoked population” should abide by the selected top-line filters (time period, district, case type, supervision type) and violation history matrix (most severe violation type, number of violations)
* (Like the existing charts) - when users hover over the graph, the actual counts powering the graph for this demographic should be visible. 
    * Ex. if caucasian is selected, whenever hovering over the graph you should see:
“Revoked population: X 
Supervised population: Y
Overall population: Z”
* (Like existing charts) - bars are shaded if the underlying count is too small to be significant. 

**Additional context**
This should be done for both Lantern states, Missouri and Pennsylvania. All labels should say "gender" in MO and "sex" in PA.

**Comment by jessex** [comment]
Heads up to our Inobright friends, it will probably be helpful / easier to do this one simultaneously to #712.

**Comment by jovergaag** [comment]
The fixtures now have the data you need to support this new chart design. The "revocations_matrix_distribution_by_gender" and "state_gender_population" fixtures are what feeds this chart. It might be helpful to look at the attribute changes that were merged recently in issue #709.

The attributes that will be used for this new chart are:
- "Those who were revoked": `revocation_count` numerator and `revocation_count_all` denominator
- "Supervision population" bar: `supervision_population_count` numerator and `supervision_count_all` denominator
- "[State name] population" bar: `population_count` numerator and `total_state_population_count` denominator (both from the "state_gender_population")

The "state_gender_population" is not currently being served by the API, you will need to add is as a file served from the `newRevocations` endpoint.

Let me know if you have any questions!
