### ISSUE TITLE
Update admission type filter dropdown options

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#715]
**What needs to be done? Why does it need to be done?**
The frontend for the admission type dropdown for the Pennsylvania Lantern dashboard was enabled in #423. After data investigations and feedback conversations, we will be updating the nested dropdown to have fewer values:

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/15368701-0299-4de8-8ac0-3c35b27a6e71)

The following will the new values:

All
Revocation
SCI - short-term
- 6-month
- 9-month
- 12-month
PVC

**Additional context**
@jjdressel11 add view change / backend dependencies if there are any.

**Comment by jovergaag** [comment]
@sychang Once the data is ready and the values are changed - do we enable this filter in PA? Should this issue encompass both the changing of values and enabling?

**Comment by sychang** [comment]
Yes we should! Happy to let this issue encompass it or track it in a new one - whichever makes most sense workflow-wise
