### ISSUE TITLE
Update chart title and description to reflect new shortened violations lookback period

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#716]
**What needs to be done? Why does it need to be done?**
There was recently a change to update the revocations matrix lookback period to be 9 months instead of 12 ([ticket](https://app.zenhub.com/workspaces/-lantern--5f2cdf04d4d9670013da86ed/issues/recidiviz/pulse-dashboard/411)). The title of the violation history chart should be updated accordingly. 

Old text: "Admissions by violation history (in year prior to their last reported violation)"
New text: "Admissions by violation history (in 9 months prior to their last reported violation)"

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/3fb6d76c-798f-4d24-b450-3fb21357881c)

For the chart description next to the bubble chart, the text describing the one year lookback period should be updated as well. "One year" should be replaced with "9 months"

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/6183b8b7-85e2-439c-8deb-63bb9f7c93b8)

There will be a separate ticket to update the methodology.

This should be done for both Missouri and Pennsylvania (all Lantern states).

**Additional context**
@jjdressel11 FYI.

**Comment by jovergaag** [comment]
@sychang Do we change the time description below the title for each chart as well?
![Screen Shot 2021-01-26 at 9 28 29 AM](https://user-images.githubusercontent.com/5872651/105881059-e7a67880-5fb8-11eb-90e7-a4ef41975cdf.png)

**Comment by sychang** [comment]
No, this is referencing a different time period. The time description on the charts represent the time period filter. The new 9 month lookback period is referencing how far back in the past we count violation history. No change on the time descriptions!
