### ISSUE TITLE
Quantify FTR Participation by County + Month

### ISSUE THREAD

**Issue by VincentLa14** [Recidiviz/pulse-dashboard#72]
**TLDR: Figure out takeup of FTR Participation by County + Month** 

Goal is to figure out if there is different takeup so that we can do a diff-in-diff analysis. 

Maybe do one at member level and then do one provider level?

**Comment by jessex** [comment]
@VincentLa14 did you mean to file this issue against recidiviz-data? I imagine so as that is where we track everything on the data platform.

**Comment by VincentLa** [comment]
@jessex sorry yes!
