### ISSUE TITLE
v2: Add "Recommended for revocation" bar to race and gender charts.

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#734]
**What needs to be done? Why does it need to be done?**
Building upon #712 and #713, an additional bar should be added to the race and gender/sex charts for Lantern states for "Those recommended for revocation". This bar should be inserted below "Those who were revoked" but above "Supervised population"

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/4ff31720-637e-49b7-8f59-1bda21b5490c)

This should be done for both the race and the gender/sex chart for all states. This task is blocked by the calc changes.

cc @terinpw 

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang I can't remember what we decided this morning. Is this feature still a go considering #849 (removing officer recommendation from the case table).

We will want to add it for MO, but the question is on PA...

**Comment by sychang** [comment]
Confirmed with CSG this afternoon - we want to add it for MO but **not** add the bar for PA!
