### ISSUE TITLE
Add suboffices to district chart in PA

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#735]
**What needs to be done? Why does it need to be done?**
Show sub offices on the district chart, in addition to districts.

Options discussed here. If the alternate introduces less complexity, let's do that one instead: https://docs.google.com/document/d/1KNUaP6IMrEshJ-9buVdR1NlmhMW8tk7qc16KthGgWMM/edit

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang Can you confirm what we decided to display in the district chart?

I believe we had decided on showing only the district offices (not the sub-offices) for both PA and MO. 
* For PA we should display the `level_2_supervision_location_name` (Allentown DO or Pittsburgh DO) which matches the label in the filter (top level - prior to adding sub-office vfilter)
* For MO we should display the `level_1_supervision_location_external_id` (04, WMCC) which will match the label in the filter.

Is this correct?

cc: @daschi
