### ISSUE TITLE
Update UI for top-level navigation bar

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#777]
**What needs to be done? Why does it need to be done?**
This ticket involves the redesign of the current ND top-level navigation. This task involves only new UI and visual updates of the existing ND views - no changes to the actual page hierarchy.

Mocks: https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=1521%3A43

Existing nav:
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/5206dda9-a6ac-44f9-907e-ade815972414)

New nav: 
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/04d03b2d-ab49-49b0-85fc-4711a6fcacb8)

On hover:
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/593a3a96-9af9-4202-a7f6-166fd2ce94fd)

Dropdown (the options here should be "Facilities", "Community", and "Programming" to match what currently exists in ND instead of what is shown here):
![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/07ab2a55-d5d7-4da3-8930-845958b965d8)

The default page order should be: 
1. Facilities
2. Community 
3. Programming

When the dropdown is showing, the current page should be at the top of the list, followed by the other two pages in the default order. For example, if the user is currently on the "Community" page, the dropdown should be in this order: Community, Facilities, Programming. 

A new navigation bar enables:
- Extensibility to match UP's future structure
- Hierarchies the page more based on the user
- The navigation to be less obtrusive and take up less room
- Focus on accessibility

@soniachokshi to add more details

**Additional context**
CC @Catacola this could be a good FE starter task since it's UI polish building atop our current ND dash, unless it conflicts with how you are thinking through the overall infrastructure for UP.

**Comment by jovergaag** [comment]
@sychang Is this assigned to @Catacola so that he can keep an eye on it or is he going to implement it? I just want to make sure this is still intended to be implemented by Inobright since it is in their queue. Thanks!

**Comment by sychang** [comment]
To keep an eye on!
