### ISSUE TITLE
Change "Not Assessed" copy to "No Score"

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#800]
**What needs to be done? Why does it need to be done?**
This task involves two pieces: 
1. Updating the copy for the "Not Assessed" bar of the risk level chart to say "No Score" 
2. Updating the [MO](https://docs.google.com/document/d/1q06zsWlTK3O4sqykPQQ4NQixScQyvjbqsFViH1GXfVQ/edit?ts=602b434c#) and [PA](https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit) methodologies to reflect the change. Note, there are 2 places in the methodology where "Unassessed" should be changed to "No Score" once in the risk level chart and second in the caseload table.

This bar is currently causing some confusion in Missouri because MODOC makes an important distinction in what they consider to be an “unassessed” risk level. It’s not just whether someone is missing a risk assessment, but that the person on supervision has been on supervision for longer than 45 days and still does not have an assessment.  Currently in the MO dashboard, it looks like “unassessed” and “missing” are combined and called “Unassessed”. Additionally, for district TCSTL, MO typically uses any risk assessment on file, not just the Community Supervision Screening Tool and/or the Community Supervision Tool. 

Because this chart was not designed to account for actual assessment completion logic and policy, and because we have Torch features coming that will actually help leadership and supervisors determine whether risk assessments are overdue per-policy, we will not go down the rabbithole of implementing the overdue logic but instead minimize confusion by removing the Not Assessed bar entirely. Since the goal of this chart is to correlate patterns of revocations with risk level, the Not Assessed bar doesn't currently add much information.

Alternates:
1.  Remove the "Not Assessed" bar entirely but then that would mess up the supervision denominator summing.

**Additional context**

**Comment by Catacola** [comment]
We have a task out to add unassessed people to the ND dash: https://github.com/Recidiviz/recidiviz-data/issues/5910

Would this conflict with your plans?

@alexabatino

**Comment by sychang** [comment]
This should not conflict, as this is only on the Lantern views for MO and PA, but thank you for flagging! This makes me think we may want to opt for the alternate in which we do not filter these out in case we run into the same issues in MO and PA, and for consistency. Will discuss with the Lantern team in sprint planning this week.
