### ISSUE TITLE
Middle charts not working on initial law violation bubble selection

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#852]
**What needs to be done? Why does it need to be done?**
To repro:
- In staging, select a law violation bubble in PA (also broken in MO)
- Look at district chart, no data shows up. However, if you switch to another chart then back to the district chart, it shows up.
- Sex and race charts are also behaving strangely upon toggling bubbles and charts (shows one race/sex as 100% of the supervised and admitted population)

Suspected API-related

**Additional context**
cc @jjdressel11 if there are other details you want to add.

**Comment by jjdressel11** [comment]
Also seeing risk level chart disappear when a violation bubble is selected:

![image.png](https://images.zenhubusercontent.com/5ee7bf01c27d95a89f9adc41/4fbc7c54-0dfc-49ae-a777-2a885ea313fa)
