### ISSUE TITLE
Fix incompatible IE11 styles

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/pulse-dashboard#877]
**What needs to be done? Why does it need to be done?**
Search the app for incompatible IE11 styles like `<main>` and update them to be IE11 compatible.

**Additional context**
Add any other context about the task here.

**Comment by AlexK-ino** [comment]
Hi @jovergaag !
I did not see any problem with IE11.
And the fact that not <main> is not supported by IE - it still shows it as <div> to which styles are applied through a class. Redoing <main> is not a problem, does it make sense?

Also, I really didn't see any problems with IE at the moment, but I admit that I might have missed something that wasn't noticed by me.

**Comment by jovergaag** [comment]
Hi @AlexK-ino! This is a task that @MeloncholyShiro has wanted to take on. He found some styles that were not IE11 compatible. I think for now, just removing any `<main>` tags and looking through the console in IE11 to remove any other incompatibility warnings is enough for this issue!
