### ISSUE TITLE
Move existing ND goals to top-level page in dashboard

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#897]
**What needs to be done? Why does it need to be done?**
Things to note:
1) Many of the chart design changes overlap with #904, so feel free to combine changes for both in common diffs.
2) There's a lot going on here, so you can split the work up into multiple PRs if needed.
3) Please base your work and PRs against `feature/core-header-refresh`

To consolidate the hierarchy, have a centralized place for all states to view their goals, and limit the number of pages on the current ND dashboard, we will consolidate the goals pages into a single top-level goals page. The path of this page will be `\goals\` and it should be an option under the main dropdown in the upper left.

The following charts should be moved to the new top-level goals page in the following order:
- REVOCATION ADMISSIONS BY MONTH
- SUCCESSFUL COMPLETION OF SUPERVISION
- LSI-R SCORE CHANGES (AVERAGE)
- PRISON ADMISSIONS DUE TO REVOCATION
- DAYS AT LIBERTY (AVERAGE)
- REINCARCERATIONS BY MONTH

In order to make the page more consistent and to gradually update the UI to our new design system, let's make the following design tweaks:

1. Update the page background color to #F4F5F5.

2. Update all of the lines to be #4C6290 – the "Indigo" color in the Data section of our [new design system](https://www.figma.com/file/v7ei7OnUkPkwJO6ukOvTjl/System-v2?node-id=30%3A32).

3. Update the highlighted text ("19 revocations" in the example below) to also be #4C6290.
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/fb150705-0b8a-400d-a460-f3f4636f5a73)

4. Update all fonts to "Libre Franklin." See example below.
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/ede84c95-23f0-4d25-a7ae-aa0480cb2c53)

5. There are two styles of line chart that exist on the Goals pages of our current dashboard (see below). Update all of the line charts to use the style of the gray line chart on the left (rounded line with smaller dots). 
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/8d53453e-5694-43a9-8b6b-4bafdcc7d57c)

6. Some charts have both horizontal and vertical gridlines (like the chart on the left), and others only have horizontal gridlines (like the chart on the right). Update all of the charts to only have horizontal gridlines.  
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/dd169be3-c425-47d1-a94c-6435d2c8564c) 

7. We're changing our card styles to include an inner shadow and rounded corners (see before and after below). See examples in Figma [here](https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=1521%3A43). Update the chart card style to include the following attributes:
- background: #FFFFFF;
- box-shadow: inset 0px -1px 1px rgba(19, 44, 82, 0.3);
- border-radius: 8px;
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/fc559cdf-0518-4249-acd4-2dd8368fad00)

**Additional context**
Three new goals will be added soon to this view, likely on top of these existing goals. Separate ticket incoming for that.

**Comment by Catacola** [comment]
Note: #915 creates the new routes and moves the plots there.
