### ISSUE TITLE
Add a Glossary/Methodology view

### ISSUE THREAD

**Issue by jessex** [Recidiviz/pulse-dashboard#9]
For the sake of transparency and sanity checking with experts, it will be useful to have a view that describes terminology as we mean it and methodology for how we calculate key metrics. Some of that material would be more static and region-agnostic, while some may be dynamic and region-specific, e.g. the definition of key recidivism metrics may be more general while the way in which we identify revocations of parole will vary based on how a jurisdiction conducts parole and its legal code.

Much of the material can be lifted and streamlined from our _Measuring Recidivism_ paper.

Acceptance Criteria:
- A Glossary (or Methodology) page defines terminology and metrics shown in the app
- The same view describes the methodology for particular calculations where appropriate
- We should consider standardized tooltips in the app that provide brief descriptions and link to the glossary for more information

**Comment by jessex** [comment]
This may also contain a list of key metrics we are tracking for a given region.

We want this all to be as human-readable as possible.

**Comment by matthewroot** [comment]
I wonder about whether or not an explicit page is the right way to go here or doing things like providing on-hover definitions in key places. We could also do both.

It would be helpful to being to list out the key terms and methods that we want to explain. We can build these into a data structure that can be put to use in a variety of ways, flexibly.

**Comment by sychang** [comment]
Closing this issue because we are doing this as part of unifying the tools!
