### ISSUE TITLE
Update chart styling on the Facilities, Community, and Programming "Explore" pages

### ISSUE THREAD

**Issue by soniachokshi** [Recidiviz/pulse-dashboard#904]
**What needs to be done? Why does it need to be done?**
**What needs to be done? Why does it need to be done?**
Things to note:
1) Many of the chart design changes overlap with #897, so feel free to combine changes for both in common diffs.
2) There's a lot going on here, so you can split the work up into multiple PRs if needed.
3) Please base your work and PRs against `feature/core-header-refresh`

In order to gradually update our dashboard to our new design system, we will start by changing chart colors and styling. See the [new design system ](https://www.figma.com/file/v7ei7OnUkPkwJO6ukOvTjl/System-v2?node-id=0%3A1) in Figma.

1. Update all line charts to use the "indigo" color: #4C6290. 

2. Update all bar charts to use the color palette below, in that order. There are multiple bar charts on the Explore pages, each with a different number of colors. If the bar chart has two colors, use the first two colors in the palette. If the bar chart chart has three colors, use the first three colors, etc. Access the palette in Figma [here](https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=2208%3A41).

![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/fed4760f-2eee-441d-a3bc-6664200d3a4e) 

In the examples below, here's how the color palette would be applied:
- For the chart on the left, Probation would use "forest" and Parole would use "gold".
- For the chart on the right, Absconsion would use "forest", New Offense would use "gold", Technical would use "crimson" and Unknown Type would use "indigo".  
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/e6e09022-2860-491f-976d-c885cdbfc874)

3. Update the page background to #F4F5F5.

4. We're changing our card styles to include an inner shadow and rounded corners (see before and after below). See examples in Figma [here](https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=1521%3A43). Update the chart card style to include the following attributes:
- background: #FFFFFF;
- box-shadow: inset 0px -1px 1px rgba(19, 44, 82, 0.3);
- border-radius: 8px;
![image.png](https://images.zenhubusercontent.com/5f20518de59ddb3bd53d57b9/211780a5-fdb1-413b-b1b2-679d9e3aee16)

5. Update all fonts to "Libre Franklin."

**Additional context**
Add any other context about the task here.

**Comment by AlexK-ino** [comment]
@soniachokshi Hello!
I noticed that there may have been an error in the [figma](https://www.figma.com/file/v7ei7OnUkPkwJO6ukOvTjl/System-v2?node-id=0%3A1). The rgba color in the "Data" palette is wrong.

What is there to lean on?
The rgba specified in the layout or the specified color? 
![image](https://user-images.githubusercontent.com/75606430/111170517-130b1400-85b5-11eb-8c19-c8a995d2d531.png)
