### ISSUE TITLE
Redirect users to login page if accessing unauthenticated

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/pulse-dashboard#91]
If a user tries to access dashboard.recidiviz.org unauthenticated, have the site automatically redirect to the recidiviz.auth0 login page instead of showing the dashboard with the "Login to get started" message. This is currently working for any non-home-page view (e.g. /snapshots), but should also work for the landing page.

**Comment by jessex** [comment]
This is what the Dashboard does today, no? [Open this in an incognito window](https://dashboard.recidiviz.org/revocations).
