### ISSUE TITLE
Consolidate core api calls

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#916]
**Is your feature request related to a problem? Please describe.**
The api for both goals and community/explore are split across two calls:
- goals:  `community/goals` and `facilities/goals`
- explore: `community/explore` and `programming/explore`

**Describe the solution you'd like**

Let's consolidate so we have but two endpoints: `\goals` and `\community\explore`

**Describe alternatives you've considered**
We will run both in parallel now to get this app out.

**Comment by daschi** [comment]
This could also tie in well with moving the data fetching out of the `useChartData` hook and into the `MetricsStore` (See: https://github.com/Recidiviz/pulse-dashboard/pull/1018)
