### ISSUE TITLE
Make small visual edits to the recidiviz.auth0 login page

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/pulse-dashboard#92]
- Tone down the heavy black drop shadow behind the modal
- The title of the modal dialog should stay ‘Recidiviz Dashboard’ when the use clicks ‘Sign Up’... It shouldn’t change to ‘Sign Up’
- Make the favicon and page title match the Recidiviz Dashboard (right now it’s an Auth0 favicon, and the page title in the browser window is ‘Sign in with Auth0’)

**Comment by jjdressel11** [comment]
Favicon and page title updated to match the Recidiviz Dashboard. Other visual updates are lower priority.

**Comment by Catacola** [comment]
Sing Up title is fixed
