### ISSUE TITLE
Switch stores to typescript

### ISSUE THREAD

**Issue by Catacola** [Recidiviz/pulse-dashboard#935]
**Is your feature request related to a problem? Please describe.**
The stores are not in TS yet, so we need to do a lot of ts-ignore when using strings we get from it.

**Describe the solution you'd like**
Switch the store files to play nice with TS.

**Describe alternatives you've considered**
Not using TS and sprinkling ts-ignore calls everywhere. This road leads to frustrating bugs.

**Additional context**
<img width="434" alt="Screen Shot 2021-03-19 at 3 33 06 PM" src="https://user-images.githubusercontent.com/5516210/111839191-69839580-88c8-11eb-8ebb-8f1dc9a1682e.png">

**Comment by daschi** [comment]
Since the LanternStore is the only store that is not in Typescript and we are soon deprecating it in favor of Pathways/Practices, this is no longer needed!
