### ISSUE TITLE
Change "Admissions" to "Recommitments" in PA lantern dash

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#957]
**What needs to be done? Why does it need to be done?**
We are showing board decisions on the PA Lantern dashboard, which represents "recommitments," so saying "Admissions" is causing confusing. 

This task involves changing all instances of "Admissions", "Admission", and "Admitted" on the frontend to "Recommitments", "Recommitment", and "Recommitted."

The PA methodology doc is also updated: https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit#

**Additional context**
Add any other context about the task here.

**Comment by jovergaag** [comment]
@sychang Where does this fall in priority compared to the ND pages launch?

**Comment by sychang** [comment]
This one is higher than the ND pages launch, and the race and gender one is lower pri (but should be completed before 4/29 rollout meeting).
