### ISSUE TITLE
Show all race and genders on the same chart, to match ND's designs

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#963]
**What needs to be done? Why does it need to be done?**
During the PA launch meeting, they provided feedback that the race and gender charts would be more user-friendly if they could see all races and genders on the same chart, similar to how it appears in the revocations by race rate chart on the ND dashboard.

I flagged that the smaller race categories might get hard to distinguish with that design, and less easy to compare across stages of the funnel, which is why we stayed away from it. However, their primary use case is comparing across races for a particular part of the funnel (i.e., supervision population), so that is less of an issue.

This task involves 
- updating the race and gender chart UI to show all races/genders on the same chart, rather than having toggle pills between the races
In addition.
- Changing the race groupings in PA to be "White," "Black," "Hispanic," and "Other," which are the categories most relevant for them.

cc @soniachokshi and @terinpw for mocks or any concerns.

**Additional context**
Open question for Serena: would MO be alright with this change as well.

**Comment by sychang** [comment]
This one lower pri than ND, but should be completed by 4/29 supervisor training. Still waiting confirmation on whether MO would be ok with this updated chart so we can change them both at once rather than maintaining two versions.

**Comment by jovergaag** [comment]
@sychang Any chance you confirmed with MO whether this will be ok on their dashboard as well?

**Comment by sychang** [comment]
Confirmed, and unfortunately MO needs to keep the race/gender charts as is since 
1. The team just completed a set of trainings with district directors, so it's better to avoid change management.
2. MO are generally hesitant to compare races together on the same chart.

Here's a quick sketch that confirmed the concept PA is going for (matches ND dashboard with fewer categories), cc @soniachokshi in case there is an actual mock handy:
![image](https://user-images.githubusercontent.com/6633887/114640927-b32c8980-9c96-11eb-9ee4-17dcc1360a83.png)

**Comment by jovergaag** [comment]
@soniachokshi Do you have a mock of this to pull the colors from? Are the colors above the final colors?

**Comment by sychang** [comment]
I think we can use same colors for White, Black, Hispanic, and make Other the purple that is what Asian is, but defer to @soniachokshi if you have a better palette
